### ISSUE TITLE
Ce+SP

### ISSUE THREAD

**Issue by Reyhanehe** [TRIQS/dft_tools#108]
Dear all
Hi
I want run dmft calculation considering spin-polarized coupling for Ce.
I used the case.struct such as below:

"
F   LATTICE,NONEQUIV.ATOMS:  1
MODE OF CALC=RELA unit=bohr
  9.750000  9.750000  9.750000 90.000000 90.000000 90.000000
ATOM   1: X=0.00000000 Y=0.00000000 Z=0.00000000
          MULT= 1          ISPLIT= 2
Ce         NPT=  781  R0=0.00001000 RMT= 2.50000     Z: 58.0
"
then I initillaized it in WIEN2k by the command : init_lapw and considering spin-polarization in it.
then I run the "runsp_lapw" script in wien2k.
I used from the below case.indmftpr and case.py in my calculation:
"1                ! Nsort
1                ! Mult(Nsort)
3                ! lmax
cubic            ! choice of angular harmonics
1 1 1 2          ! l included for each sort
0 0 0 0          ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
0                !
-0.40 0.40       ! t2g + eg + Op
"

"import pytriqs.utility.mpi as mpi
from pytriqs.operators.util import *
from pytriqs.archive import HDFArchive
from pytriqs.applications.impurity_solvers.cthyb import *
from pytriqs.gf.local import *
from pytriqs.applications.dft.sumk_dft import *
from pytriqs.applications.dft.converters.wien2k_converter import *

dft_filename='ce'
U = 6.0
J = 0.7
beta = 40
loops = 10                      # Number of DMFT sc-loops
sigma_mix = 0.8                  # Mixing factor of Sigma after solution of the AIM
delta_mix = 0.8                  # Mixing factor of Delta as input for the AIM
dc_type = 0                      # DC type: 0 FLL, 1 Held, 2 AMF
use_blocks = True                # use bloc structure from DFT input
prec_mu = 0.01
h_field = 0.0

# Solver parameters
p = {}
p["max_time"] = -1
p["random_seed"] = 123 * mpi.rank + 567
p["length_cycle"] = 200
p["n_warmup_cycles"] = 100000
p["n_cycles"] = 1000000
p["perform_tail_fit"] = True
p["fit_max_moment"] = 4
p["fit_min_n"] = 30
p["fit_max_n"] = 60

Converter = Wien2kConverter(filename=dft_filename, repacking=True)
Converter.convert_dft_input()
mpi.barrier()

previous_runs = 0
previous_present = False
if mpi.is_master_node():
    f = HDFArchive(dft_filename+'.h5','a')
    if 'dmft_output' in f:
        ar = f['dmft_output']
        if 'iterations' in ar:
            previous_present = True
            previous_runs = ar['iterations']
    else:
        f.create_group('dmft_output')
    del f
previous_runs    = mpi.bcast(previous_runs)
previous_present = mpi.bcast(previous_present)

SK=SumkDFT(hdf_file=dft_filename+'.h5',use_dft_blocks=use_blocks,h_field=h_field)

n_orb = SK.corr_shells[0]['dim']
l = SK.corr_shells[0]['l']
spin_names = ["up","down"]
orb_names = [i for i in range(n_orb)]

# Use GF structure determined by DFT blocks
gf_struct = SK.gf_struct_solver[0] 
# Construct U matrix for density-density calculations
Umat, Upmat = U_matrix_kanamori(n_orb=n_orb, U_int=U, J_hund=J)
# Construct Hamiltonian and solver
h_int = h_int_density(spin_names, orb_names, map_operator_structure=SK.sumk_to_solver[0], U=Umat, Uprime=Upmat, H_dump="H.txt")
S = Solver(beta=beta, gf_struct=gf_struct)

if previous_present:
  chemical_potential = 0
  dc_imp = 0
  dc_energ = 0
  if mpi.is_master_node():
      S.Sigma_iw << HDFArchive(dft_filename+'.h5','a')['dmft_output']['Sigma_iw']
      chemical_potential,dc_imp,dc_energ = SK.load(['chemical_potential','dc_imp','dc_energ'])
  S.Sigma_iw << mpi.bcast(S.Sigma_iw)
  chemical_potential = mpi.bcast(chemical_potential)
  dc_imp = mpi.bcast(dc_imp)
  dc_energ = mpi.bcast(dc_energ)
  SK.set_mu(chemical_potential)
  SK.set_dc(dc_imp,dc_energ)

for iteration_number in range(1,loops+1):
    if mpi.is_master_node(): print "Iteration = ", iteration_number

    SK.symm_deg_gf(S.Sigma_iw,orb=0)                        # symmetrise Sigma
    SK.set_Sigma([ S.Sigma_iw ])                            # set Sigma into the SumK class
    chemical_potential = SK.calc_mu( precision = prec_mu )  # find the chemical potential for given density
    S.G_iw << SK.extract_G_loc()[0]                         # calc the local Green function
    mpi.report("Total charge of Gloc : %.6f"%S.G_iw.total_density())

    # Init the DC term and the real part of Sigma, if no previous runs found:
    if (iteration_number==1 and previous_present==False):
        dm = S.G_iw.density()
        SK.calc_dc(dm, U_interact = U, J_hund = J, orb = 0, use_dc_formula = dc_type)
        S.Sigma_iw << SK.dc_imp[0]['up'][0,0]

    # Calculate new G0_iw to input into the solver:
    if mpi.is_master_node():
        # We can do a mixing of Delta in order to stabilize the DMFT iterations:
        S.G0_iw << S.Sigma_iw + inverse(S.G_iw)
        ar = HDFArchive(dft_filename+'.h5','a')['dmft_output']
        if (iteration_number>1 or previous_present):
            mpi.report("Mixing input Delta with factor %s"%delta_mix)
            Delta = (delta_mix * delta(S.G0_iw)) + (1.0-delta_mix) * ar['Delta_iw']
            S.G0_iw << S.G0_iw + delta(S.G0_iw) - Delta
        ar['Delta_iw'] = delta(S.G0_iw)
        S.G0_iw << inverse(S.G0_iw)
        del ar

    S.G0_iw << mpi.bcast(S.G0_iw)

    # Solve the impurity problem:
    S.solve(h_int=h_int, **p)

    # Solved. Now do post-processing:
    mpi.report("Total charge of impurity problem : %.6f"%S.G_iw.total_density())

    # Now mix Sigma and G with factor sigma_mix, if wanted:
    if (iteration_number>1 or previous_present):
        if mpi.is_master_node():
            ar = HDFArchive(dft_filename+'.h5','a')['dmft_output']
            mpi.report("Mixing Sigma and G with factor %s"%sigma_mix)
            S.Sigma_iw << sigma_mix * S.Sigma_iw + (1.0-sigma_mix) * ar['Sigma_iw']
            S.G_iw << sigma_mix * S.G_iw + (1.0-sigma_mix) * ar['G_iw']
            del ar
        S.G_iw << mpi.bcast(S.G_iw)
        S.Sigma_iw << mpi.bcast(S.Sigma_iw)

    # Write the final Sigma and G to the hdf5 archive:
    if mpi.is_master_node():
        ar = HDFArchive(dft_filename+'.h5','a')['dmft_output']
        if previous_runs: iteration_number += previous_runs
        ar['iterations'] = iteration_number
        ar['G_tau'] = S.G_tau
        ar['G_iw'] = S.G_iw
        ar['Sigma_iw'] = S.Sigma_iw
        ar['G0-%s'%(iteration_number)] = S.G0_iw
        ar['G-%s'%(iteration_number)] = S.G_iw
        ar['Sigma-%s'%(iteration_number)] = S.Sigma_iw
        del ar

    # Set the new double counting:
    dm = S.G_iw.density() # compute the density matrix of the impurity problem
    SK.calc_dc(dm, U_interact = U, J_hund = J, orb = 0, use_dc_formula = dc_type)

    # Save stuff into the dft_output group of hdf5 archive in case of rerun:
    SK.save(['chemical_potential','dc_imp','dc_energ'])

if mpi.is_master_node():
    ar = HDFArchive("dftdmft.h5",'w')
    ar["G_tau"] = S.G_tau
    ar["G_iw"] = S.G_iw
    ar["Sigma_iw"] = S.Sigma_iw
"
then I  executed:1)x lapw2 -almd -up
2)x lapw2 -almd -dn
3)dmftproj -sp
and finally when I run the "runsp -qdmft 1" command in my calculation I have the below error.

"
 LAPW0 END
 LAPW1 END
 LAPW1 END
 LAPW2 END
 LAPW2 END
Welcome in DMFTPROJ: PROJECTION TO LOCALIZED BASIS

This prgm will build the Wannier projectors to the
localized orbitals of an atom onto which DMFT will be applied.

You are performing a computation
without Spin-Orbit.
using Spin-Polarized Wien2k input files.
=======================================
Sorts of atoms =   1
Equivalent sites per each sort: 1

-------------------------------------
For the sort  1 :
The orbital l= 0 is included.
The orbital l= 1 is included.
The orbital l= 2 is included.
The orbital l= 3 is included.

The Eigenstates are projected in an energy window from   -0.40000 Ry  to     0.40000 Ry around the Fermi level.

=======================================
Basis representation for each sort.

-------------------------------------
For the sort  1 :
The atomic sort 1 is studied in the cubic basis representation.

The basis for s-orbital is still    1.000000
The basis for orbital l= 1 has the following properties :
 - number of ireps :  1
 - degree of each ireps :  3
The transformation matrix is block diagonal in the spin-space. The up/up and down/down blocks are the same and defined as :
    0.707107    0.000000    0.000000    0.707107    0.000000    0.000000
    0.000000    0.000000    0.000000    0.000000    1.000000    0.000000
   -0.707107    0.000000    0.000000    0.707107    0.000000    0.000000

The basis for orbital l= 2 has the following properties :
 - number of ireps :  2
 - degree of each ireps :  2  3
The transformation matrix is block diagonal in the spin-space. The up/up and down/down blocks are the same and defined as :
    0.000000    0.000000    0.707107    0.000000   -0.707107    0.000000    0.000000    0.000000    0.000000    0.000000
    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.707107    0.000000    0.707107    0.000000
    1.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   -0.707107    0.000000    0.707107    0.000000
    0.000000    0.000000    0.707107    0.000000    0.707107    0.000000    0.000000    0.000000    0.000000    0.000000

The basis for orbital l= 3 has the following properties :
 - number of ireps :  4
 - degree of each ireps :  2  1  2  2
The transformation matrix is block diagonal in the spin-space. The up/up and down/down blocks are the same and defined as :
    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.707107    0.000000    0.000000    0.707107    0.000000    0.000000    0.000000
    0.000000    0.000000    0.707107    0.000000    0.000000    0.707107    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.707107    0.000000    0.000000    0.707107    0.000000
    1.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.707107    0.000000    0.000000   -0.707107    0.000000
    0.000000    0.000000    0.707107    0.000000    0.000000   -0.707107    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.707107    0.000000    0.000000   -0.707107    0.000000    0.000000    0.000000

=======================================
Precisions about correlated orbitals.

-------------------------------------
For the sort  1 :
The whole orbital l= 3 is included as correlated.

=======================================
Symmetry operations of the system

Number of Symmetries =   48

Properties of the symmetry operations :
   alpha, beta, gamma are their Euler angles.
   iprop is the value of their determinant.

 SYM.OP.  alpha      beta     gamma     iprop
    1       0.0     180.0     180.0       1
    2      90.0      90.0      90.0      -1
    3       0.0       0.0       0.0      -1
    4     270.0      90.0     270.0       1
    5     270.0       0.0       0.0      -1
    6     270.0      90.0     180.0       1
    7       0.0     180.0      90.0       1
    8      90.0      90.0       0.0      -1
    9     180.0      90.0     270.0       1
   10       0.0      90.0       0.0      -1
   11     180.0      90.0      90.0      -1
   12       0.0      90.0     180.0       1
   13       0.0     180.0     270.0       1
   14      90.0       0.0       0.0      -1
   15      90.0      90.0     180.0      -1
   16     270.0      90.0       0.0       1
   17     180.0       0.0       0.0      -1
   18       0.0     180.0       0.0       1
   19     270.0      90.0      90.0       1
   20      90.0      90.0     270.0      -1
   21       0.0      90.0      90.0      -1
   22     180.0      90.0       0.0       1
   23       0.0      90.0     270.0       1
   24     180.0      90.0     180.0      -1
   25     180.0      90.0     180.0       1
   26       0.0      90.0     270.0      -1
   27     180.0      90.0       0.0      -1
   28       0.0      90.0      90.0       1
   29      90.0      90.0     270.0       1
   30     270.0      90.0      90.0      -1
   31       0.0     180.0       0.0      -1
   32     180.0       0.0       0.0       1
   33     270.0      90.0       0.0      -1
   34      90.0      90.0     180.0       1
   35      90.0       0.0       0.0       1
   36       0.0     180.0     270.0      -1
   37       0.0      90.0     180.0      -1
   38     180.0      90.0      90.0       1
   39       0.0      90.0       0.0       1
   40     180.0      90.0     270.0      -1
   41      90.0      90.0       0.0       1
   42       0.0     180.0      90.0      -1
   43     270.0      90.0     180.0      -1
   44     270.0       0.0       0.0       1
   45     270.0      90.0     270.0      -1
   46       0.0       0.0       0.0       1
   47      90.0      90.0      90.0       1
   48       0.0     180.0     180.0      -1

-------------------------------------
Global-to-local-coordinates rotations

Properties of the symmetry operations :
   alpha, beta, gamma are their Euler angles.
   iprop is the value of their determinant.

  SORT    alpha      beta     gamma     iprop
    1       0.0       0.0       0.0       1

=======================================

Reading of the file ce.almblmup
Reading of the file ce.almblmdn

The value of the Fermi Energy is    0.61215 Ry.
All the considered energies are now given with respect to this value. (E_Fermi is now 0 Ry)

=======================================
Computation of the Occupancies and Density Matrices up to E_Fermi

Creation of the projectors...
Evaluation of the density matrices...

-------------------------------------
Density Matrices for the Correlated States :

  Sort =   1  Atom =   1  and Orbital l =   3
Writing the matrix as : [ block up/up |      0      ] with
                        [      0      | block dn/dn ]
   # For the Up/Up block     :
    0.130808    0.000000   -0.000000   -0.000000   -0.000000   -0.000000   -0.000000   -0.000000    0.000000    0.000000   -0.000000   -0.000000   -0.000000   -0.000000
   -0.000000    0.000000    0.029907   -0.000000   -0.000000   -0.000000   -0.000000    0.000000   -0.000000    0.000000    0.000000   -0.000000   -0.000000    0.000000
   -0.000000    0.000000   -0.000000    0.000000    0.186996    0.000000   -0.000000    0.000000    0.000000   -0.000000   -0.000000    0.000000   -0.000000    0.000000
   -0.000000    0.000000   -0.000000   -0.000000   -0.000000   -0.000000    0.092970    0.000000    0.048848    0.000000    0.000000   -0.000000   -0.000000   -0.000000
    0.000000   -0.000000   -0.000000   -0.000000    0.000000    0.000000    0.048848   -0.000000    0.067745   -0.000000   -0.000000    0.000000    0.000000   -0.000000
   -0.000000    0.000000    0.000000    0.000000   -0.000000   -0.000000    0.000000    0.000000   -0.000000   -0.000000    0.092970   -0.000000   -0.048848   -0.000000
   -0.000000    0.000000   -0.000000   -0.000000   -0.000000   -0.000000   -0.000000    0.000000    0.000000    0.000000   -0.048848    0.000000    0.067745   -0.000000
   # For the Down/Down block :
    0.043047   -0.000000    0.000000    0.000000   -0.000000   -0.000000   -0.000000   -0.000000    0.000000    0.000000   -0.000000   -0.000000   -0.000000   -0.000000
    0.000000   -0.000000    0.011093    0.000000   -0.000000   -0.000000    0.000000    0.000000   -0.000000    0.000000    0.000000   -0.000000    0.000000    0.000000
   -0.000000    0.000000   -0.000000    0.000000    0.089162    0.000000   -0.000000    0.000000    0.000000   -0.000000    0.000000    0.000000   -0.000000    0.000000
   -0.000000    0.000000    0.000000   -0.000000   -0.000000   -0.000000    0.031064   -0.000000    0.015469    0.000000   -0.000000   -0.000000   -0.000000   -0.000000
    0.000000   -0.000000   -0.000000   -0.000000    0.000000    0.000000    0.015469   -0.000000    0.023076   -0.000000   -0.000000    0.000000    0.000000   -0.000000
   -0.000000    0.000000    0.000000    0.000000    0.000000   -0.000000   -0.000000    0.000000   -0.000000   -0.000000    0.031064    0.000000   -0.015469   -0.000000
   -0.000000    0.000000    0.000000   -0.000000   -0.000000   -0.000000   -0.000000    0.000000    0.000000    0.000000   -0.015469    0.000000    0.023076    0.000000

The charge of the orbital is :    0.92073

-------------------------------------
Density Matrices for all the States of the System :

  Sort =   1  Atom =   1  and Orbital l =   0
    1.008124    0.000000      0.000000    0.000000
    0.000000    0.000000      1.005635    0.000000

The charge of the orbital is :    2.01376

  Sort =   1  Atom =   1  and Orbital l =   1
Writing the matrix as : [ block up/up |      0      ] with
                        [      0      | block dn/dn ]
   # For the Up/Up block     :
    0.881253    0.000000    0.000000    0.000000   -0.000000    0.000000
    0.000000    0.000000    0.881253    0.000000    0.000000    0.000000
   -0.000000    0.000000    0.000000    0.000000    0.881253    0.000000
   # For the Down/Down block :
    0.879304    0.000000    0.000000    0.000000   -0.000000    0.000000
    0.000000    0.000000    0.879304    0.000000    0.000000    0.000000
   -0.000000    0.000000    0.000000    0.000000    0.879304    0.000000

The charge of the orbital is :    5.28167

  Sort =   1  Atom =   1  and Orbital l =   2
Writing the matrix as : [ block up/up |      0      ] with
                        [      0      | block dn/dn ]
   # For the Up/Up block     :
    0.065659    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   -0.000000    0.000000
   -0.000000    0.000000    0.065659    0.000000   -0.000000   -0.000000    0.000000    0.000000    0.000000   -0.000000
    0.000000   -0.000000   -0.000000    0.000000    0.079791    0.000000    0.000000   -0.000000    0.000000    0.000000
    0.000000   -0.000000    0.000000   -0.000000    0.000000    0.000000    0.079791    0.000000   -0.000000   -0.000000
   -0.000000   -0.000000    0.000000    0.000000    0.000000   -0.000000   -0.000000    0.000000    0.079791    0.000000
   # For the Down/Down block :
    0.064030    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   -0.000000    0.000000
   -0.000000   -0.000000    0.064030   -0.000000    0.000000    0.000000    0.000000    0.000000   -0.000000   -0.000000
    0.000000   -0.000000    0.000000   -0.000000    0.076668    0.000000    0.000000   -0.000000    0.000000   -0.000000
    0.000000   -0.000000    0.000000    0.000000    0.000000    0.000000    0.076668   -0.000000    0.000000   -0.000000
   -0.000000    0.000000   -0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.076668    0.000000

The charge of the orbital is :    0.72875

  Sort =   1  Atom =   1  and Orbital l =   3
Writing the matrix as : [ block up/up |      0      ] with
                        [      0      | block dn/dn ]
   # For the Up/Up block     :
    0.130900    0.000000   -0.000000   -0.000000   -0.000000   -0.000000   -0.000000   -0.000000    0.000000    0.000000   -0.000000   -0.000000   -0.000000   -0.000000
    0.000000    0.000000    0.029978   -0.000000   -0.000000   -0.000000   -0.000000    0.000000   -0.000000    0.000000    0.000000   -0.000000   -0.000000    0.000000
   -0.000000    0.000000   -0.000000    0.000000    0.187133    0.000000   -0.000000    0.000000    0.000000   -0.000000   -0.000000    0.000000   -0.000000    0.000000
   -0.000000    0.000000   -0.000000   -0.000000   -0.000000   -0.000000    0.093054   -0.000000    0.048859    0.000000    0.000000   -0.000000   -0.000000   -0.000000
    0.000000   -0.000000   -0.000000   -0.000000    0.000000    0.000000    0.048859   -0.000000    0.067824   -0.000000   -0.000000    0.000000    0.000000   -0.000000
   -0.000000    0.000000    0.000000    0.000000   -0.000000   -0.000000    0.000000    0.000000   -0.000000   -0.000000    0.093054   -0.000000   -0.048859   -0.000000
   -0.000000    0.000000   -0.000000   -0.000000   -0.000000   -0.000000   -0.000000    0.000000    0.000000    0.000000   -0.048859    0.000000    0.067824   -0.000000
   # For the Down/Down block :
    0.043164    0.000000   -0.000000    0.000000   -0.000000   -0.000000   -0.000000   -0.000000    0.000000    0.000000   -0.000000   -0.000000   -0.000000   -0.000000
    0.000000   -0.000000    0.011169    0.000000   -0.000000   -0.000000    0.000000    0.000000   -0.000000    0.000000    0.000000   -0.000000    0.000000    0.000000
   -0.000000    0.000000   -0.000000    0.000000    0.089349   -0.000000   -0.000000    0.000000    0.000000   -0.000000    0.000000    0.000000   -0.000000    0.000000
   -0.000000    0.000000    0.000000   -0.000000   -0.000000   -0.000000    0.031166    0.000000    0.015489    0.000000   -0.000000   -0.000000   -0.000000   -0.000000
    0.000000   -0.000000   -0.000000   -0.000000    0.000000    0.000000    0.015489   -0.000000    0.023168   -0.000000   -0.000000    0.000000    0.000000   -0.000000
   -0.000000    0.000000    0.000000    0.000000    0.000000   -0.000000   -0.000000    0.000000   -0.000000   -0.000000    0.031166   -0.000000   -0.015489   -0.000000
   -0.000000    0.000000    0.000000   -0.000000   -0.000000   -0.000000   -0.000000    0.000000    0.000000    0.000000   -0.015489    0.000000    0.023168   -0.000000

The charge of the orbital is :    0.92212
TOTAL CHARGE =    12.00000

=======================================
Computation of the total Charge below the lower limit of the energy window :  -0.40000 Ry

Creation of the projectors...
Evaluation of the density matrices...

TOTAL CHARGE =     8.00000

=======================================
Computation of the Occupancies and Density Matrices in the desired energy window [   -0.40000;    0.40000]

Creation of the projectors...
Orthonormalization of the projectors...

Evaluation of the density matrices...

-------------------------------------
Density Matrices for the Correlated States :

  Sort =   1  Atom =   1  and Orbital l =   3
Writing the matrix as : [ block up/up |      0      ] with
                        [      0      | block dn/dn ]
   # For the Up/Up block     :
    0.139722   -0.000000    0.000000   -0.000000   -0.000000    0.000000   -0.000000   -0.000000    0.000000    0.000000   -0.000000   -0.000000   -0.000000   -0.000000
    0.000000   -0.000000    0.031660    0.000000   -0.000000   -0.000000   -0.000000    0.000000   -0.000000    0.000000    0.000000   -0.000000   -0.000000    0.000000
   -0.000000   -0.000000   -0.000000    0.000000    0.200107    0.000000   -0.000000    0.000000    0.000000   -0.000000   -0.000000    0.000000   -0.000000    0.000000
   -0.000000    0.000000   -0.000000   -0.000000   -0.000000   -0.000000    0.099199    0.000000    0.052315   -0.000000    0.000000   -0.000000   -0.000000   -0.000000
    0.000000   -0.000000   -0.000000   -0.000000    0.000000    0.000000    0.052315    0.000000    0.072183   -0.000000   -0.000000    0.000000    0.000000   -0.000000
   -0.000000    0.000000    0.000000    0.000000   -0.000000   -0.000000    0.000000    0.000000   -0.000000   -0.000000    0.099199    0.000000   -0.052315    0.000000
   -0.000000    0.000000   -0.000000   -0.000000   -0.000000   -0.000000   -0.000000    0.000000    0.000000    0.000000   -0.052315   -0.000000    0.072183   -0.000000
   # For the Down/Down block :
    0.045671   -0.000000    0.000000    0.000000   -0.000000   -0.000000   -0.000000   -0.000000    0.000000    0.000000   -0.000000   -0.000000   -0.000000   -0.000000
    0.000000   -0.000000    0.011729    0.000000   -0.000000    0.000000    0.000000   -0.000000   -0.000000    0.000000    0.000000   -0.000000    0.000000    0.000000
   -0.000000    0.000000   -0.000000   -0.000000    0.095075   -0.000000   -0.000000    0.000000    0.000000   -0.000000    0.000000   -0.000000   -0.000000    0.000000
   -0.000000    0.000000    0.000000    0.000000   -0.000000   -0.000000    0.032943   -0.000000    0.016432    0.000000   -0.000000   -0.000000   -0.000000   -0.000000
    0.000000   -0.000000   -0.000000   -0.000000    0.000000    0.000000    0.016432   -0.000000    0.024457   -0.000000   -0.000000    0.000000    0.000000    0.000000
   -0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   -0.000000    0.000000   -0.000000   -0.000000    0.032943   -0.000000   -0.016432   -0.000000
   -0.000000    0.000000    0.000000   -0.000000   -0.000000   -0.000000   -0.000000    0.000000    0.000000   -0.000000   -0.016432    0.000000    0.024457   -0.000000

The charge of the orbital is :    0.98153
Writing the file case.ctqmcout...
Writing the file case.symqmc...
Writing the file case.parproj...
Writing the file case.sympar...
Writing the file case.outbwin...

END OF THE PRGM
[cm7:43977] mca_base_component_repository_open: unable to open mca_patcher_overwrite: /usr/lib64/openmpi/lib/openmpi/mca_patcher_overwrite.so: undefined symbol: mca_patcher_base_patch_t_class (ignored)
[cm7:43977] mca_base_component_repository_open: unable to open mca_shmem_mmap: /usr/lib64/openmpi/lib/openmpi/mca_shmem_mmap.so: undefined symbol: opal_show_help (ignored)
[cm7:43977] mca_base_component_repository_open: unable to open mca_shmem_sysv: /usr/lib64/openmpi/lib/openmpi/mca_shmem_sysv.so: undefined symbol: opal_show_help (ignored)
[cm7:43977] mca_base_component_repository_open: unable to open mca_shmem_posix: /usr/lib64/openmpi/lib/openmpi/mca_shmem_posix.so: undefined symbol: opal_shmem_base_framework (ignored)
--------------------------------------------------------------------------
It looks like opal_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during opal_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_shmem_base_select failed
  --> Returned value -1 instead of OPAL_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  opal_init failed
  --> Returned value Error (-1) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Error" (-1) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[cm7:43977] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
forrtl: severe (24): end-of-file during read, unit 32, file /home/Ebrahimi/WIEN2k/ce/ce.qdmftup
Image              PC                Routine            Line        Source             
lapw2              000000000055139C  Unknown               Unknown  Unknown
lapw2              0000000000580AA9  Unknown               Unknown  Unknown
lapw2              000000000040E483  qdmft_mp_readdata          56  qdmft_tmp_.F
lapw2              00000000004532FC  MAIN__                    312  lapw2_tmp_.F
lapw2              000000000040360E  Unknown               Unknown  Unknown
libc-2.25.so       00002AB9FE21C50A  __libc_start_main     Unknown  Unknown
lapw2              000000000040352A  Unknown               Unknown  Unknown

>   stop error
"
I rerun my calculation with hubbard1 mehod too. but I had this error too. I do not know why when I add Spin-polarized coupling in my calculation this error is created.
I need your help to fix it. Are you help me to solve my problem?
thank you very much
the best
REyhaneh

**Comment by Wentzell** [comment]
Please keep your issue discription **MINIMAL** and to the point.
Also an issue needs to be reproducible for us in order to analyze the problem if there exists one in the application. You seem to have a problem with your openmpi setup that we cannot solve for you.
