### ISSUE TITLE
Error putting real-frequency self energy into SumkDFT

### ISSUE THREAD

**Issue by johanjoensson** [TRIQS/dft_tools#113]
Hello!
I am trying to plot the momentum resolved spectral function obtained from a self-consistent DMFT run. I have performed analytic continuation using the MaxEnt package ([https://triqs.github.io/maxent/master/]()), however when I try to put the rel frequency self energy into the SumkDFT class I get the following error:

>  Traceback (most recent call last):
>   File "BAND.py", line 16, in <module>
>     SK.set_Sigma(Sigma_imp = [Sigma_w])
>   File "/TRIQS/install/lib/python2.7/site-packages/triqs_dft_tools/sumk_dft.py", line 579, in set_Sigma
>     self.put_Sigma(Sigma_imp)
>   File "/TRIQS/install/lib/python2.7/site-packages/triqs_dft_tools/sumk_dft.py", line 626, in put_Sigma
>     ind1_sumk, ind2_sumk] << Sigma_imp[ish][block][ind1, ind2]
>   File "/TRIQS/install/lib/python2.7/site-packages/pytriqs/gf/gf.py", line 328, in __getitem__
>     dat = self._data[ self._rank * [slice(0,None)] + key_lst ] 
> IndexError: index 1 is out of bounds for axis 2 with size 1

This is (the relevant part of) the code I run
```
SK = sk.SumkDFT(hdf_file = lda_filename + '.h5')
SK.analyse_block_structure()

with ta.HDFArchive(lda_filename + '_ME.h5', 'r') as ar:
	isc = ar['isc']

Sigma_w = isc.S_w
print Sigma_w['up_0'].data.shape
SK.set_Sigma(Sigma_imp = [Sigma_w])

```
and the shape of Sigma_w['up_0'].data is

> (4000, 1, 1)

I am afraid I don't know how to proceed.

Best regards,
Johan

**Comment by mzingl** [comment]
Hi Johan,
there seems to be something wrong with the block/matrix structure of your self-energy.
Can you print the shape of each block of your Sigma(iw) and of your Sigma(w)?
These should be the same.
Best, Manuel

**Comment by johanjoensson** [comment]
Thank you for your reply!
I had forgotten to set the threshold parameter in the analyse_block_structure call. Now it seems the block structures do match!

Best regards
Johan

**Comment by mzingl** [comment]
Yes, this explains the error. I'm closing this issue.
