### ISSUE TITLE
transport calculation

### ISSUE THREAD

**Issue by Reyhanehe** [TRIQS/dft_tools#115]
Dear Groups members
Hi
I want to calculate transport properties for SrVO3 compound using triqs code. 
So I run LDA+DMFT calculation using the python script (dft_dmft_cthyb.py) that is in "https://triqs.github.io/dft_tools/2.1.x/tutorials/srvo3.html" address But for full charge self-consistency and considering spinpolarization interaction in this compound. 
after LDA+DMFT calculation and using Analytic Continuation / MaxEnt I use the below script for transport calculation:
"
beta = 40

Converter = Wien2kConverter(filename='case', repacking=True)
Converter.convert_dft_input()
Converter.convert_transport_input()

SK = SumkDFTTools(hdf_file='case.h5', use_dft_blocks=True)

with HDFArchive('case.h5', 'r') as ar:
    isc = ar['isc']
Sigma = isc.S_w

ar = HDFArchive('case_Sigma.h5', 'a')
ar['dmft_transp_input']['Sigma'] = Sigma
SK.set_Sigma([Sigma])
ar['dmft_transp_input']['chemical_potential'] = SK.chemical_potential
ar['dmft_transp_input']['dc_imp'] = SK.dc_imp
del ar

SK.transport_distribution(directions=['xx'], broadening=0.0, energy_window=[-0.3,0.3], Om_mesh=[0.00, 0.02] , beta=beta, with_Sigma=True)
SK.save(['Gamma_w','Om_mesh','omega','directions'])
SK.load(['Gamma_w','Om_mesh','omega','directions'])
SK.conductivity_and_seebeck(beta=beta)
SK.hdf_file = 'case_transp.out.h5'
SK.save(['seebeck','optic_cond'])
"
But I do not know why the dc_imp, chemical potential and Sigma set to zero during the calculation of transport calculation (while these parameters are not zero after my DFT+DMFT calculation) and then the result of seebeck coefficient is 102*10^-6 V/K !!!! while I know that the experimental value for this parameter is 11*10^-6 V/K.
Could you please help me to solve this problem?
Thank you very much
Sincerely Yours 
Reyhaneh

**Comment by mzingl** [comment]
As described in the transport code documentation: https://triqs.github.io/dft_tools/master/guide/transport.html
you need to set your self-energy, dc and chemical_potential from the DMFT calculation.

**Comment by Reyhanehe** [comment]
Dear Mzingl
I read https://triqs.github.io/dft_tools/master/guide/transport.html before my calculation.
and about the self-energy, dc and so on I add these lines to my script too:
"
ar=HDFArchive('case.h5','a')
ar['dc'] = -0.004687675298281441
ar['chemical_potential'] = 0.176181862752
 HDFArchive('case.h5', 'r') as ar:
    chemical_potential = ar['chemical_potential']
    dc_energ = ar['dc'] 
    dc_imp = ar['dc_imp']
"
But these parameters are set to zero again :(
Are you have any idea to this problem?
Thank you very much
Reyhaneh

**Comment by mzingl** [comment]
But you need to set the parameters in SK.

**Comment by Reyhanehe** [comment]
Dear Mzingl
I set them in SK with the following script too:
ar = HDFrchive('case_Sigma.h5', 'a')
ar['dmft_transp_input']['Sigma'] = Sigma
SK.set_Sigma([Sigma])
ar['dmft_transp_input']['chemical_potential'] = SK.chemical_potential
ar['dmft_transp_input']['dc_imp'] = SK.dc_imp
"
But I have this error again :(
could you please help me to solve this problem?
Thanks a lot

**Comment by Reyhanehe** [comment]
notice that I read these parameters from my DFT+DMFT calculation before and then add them into SK.
