### ISSUE TITLE
README links to wrong webpage of dft tools?

### ISSUE THREAD

**Issue by the-hampel** [TRIQS/dft_tools#116]
Hi,

Really a small thing, but still I guess it should be quickly fixed. In the Readme the link to the dft tools webpage is not correct anymore:
http://ipht.cea.fr/triqs/applications/dft_tools/
Should be now:
https://triqs.github.io/dft_tools/2.1.x/
Right?

That would be nice. 

Best,
Alex H.

**Comment by Wentzell** [comment]
Hey Alex,

Thanks for pointing this out! This is fixed now.
