### ISSUE TITLE
dmftproj error

### ISSUE THREAD

**Issue by cmtcl18** [TRIQS/dft_tools#122]
Dear Sir,
I am trying to analyze the properties of  SrVO3. During dmftproj, I am getting the following error.

wien2k_19/SrVO3$ dmftproj
Welcome in DMFTPROJ: PROJECTION TO LOCALIZED BASIS

This prgm will build the Wannier projectors to the
localized orbitals of an atom onto which DMFT will be applied.

You are performing a computation
without Spin-Orbit.
using Paramagnetic Wien2k input files.
=======================================
Sorts of atoms =   3
Equivalent sites per each sort: 3 1 1

-------------------------------------
For the sort  1 :
The orbital l= 0 is included.

-------------------------------------
For the sort  2 :
The orbital l= 0 is included.
The orbital l= 1 is included.
The orbital l= 2 is included.

-------------------------------------
For the sort  3 :
The orbital l= 0 is included.
The orbital l= 1 is included.

The Eigenstates are projected in an energy window from   -0.11000 Ry  to     0.14000 Ry around the Fermi level.

=======================================
Basis representation for each sort.

At line 140 of file /src/triqs_dft_tools/fortran/dmftproj/set_ang_trans.f
Fortran runtime error: Bad real number in item 1 of list input

Error termination. Backtrace:
#0  0x1495e60c731a
#1  0x1495e60c7ec5
#2  0x1495e60c868d
#3  0x1495e6235d42
#4  0x1495e6237ad5
#5  0x1495e62390f9
#6  0x55b1f5bc2624
#7  0x55b1f5bbaec6
#8  0x55b1f5bb5b2e
#9  0x1495e5726b96
#10  0x55b1f5bb5b69
#11  0xffffffffffffffff

I will be thankful for your suggestion.

Best Regards,
CMTCL

**Comment by cmtcl18** [comment]
Dear Developers,
I am not getting the exact solution for above issues still now. Can any one give suggestion regarding the issues? 

I am waiting for your valuable suggestion.

Thank You,
CMTCL

**Comment by mzingl** [comment]
I guess there is something wrong in your .indmftpr file.
Did you follow: https://triqs.github.io/dft_tools/2.1.x/tutorials/srvo3.html ?
Do you have exactly the same information in your .indmftpr file as given
in the section 'Wannier orbitals' ?

Best, Manuel

**Comment by cmtcl18** [comment]
Dear Sir,
The SrVO3.indmftpr file is formed according to the SrVO3.struct file. Here the SrVO3.struct file and the SrVO3.indmftpr file is attached.

SrVO3.struct file
P   LATTICE,NONEQUIV.ATOMS:  3221_Pm-3m                                        
MODE OF CALC=RELA unit=ang                                                     
  7.365851  7.365851  7.365851 90.000000 90.000000 90.000000                   
ATOM  -1: X=0.50000000 Y=0.00000000 Z=0.00000000
          MULT= 3          ISPLIT=-2
      -1: X=0.00000000 Y=0.50000000 Z=0.00000000
      -1: X=0.00000000 Y=0.00000000 Z=0.50000000
O 1        NPT=  781  R0=0.00010000 RMT= 1.74       Z:  8.0000                 
LOCAL ROT MATRIX:    0.0000000 0.0000000 1.0000000
                     0.0000000 1.0000000 0.0000000
                    -1.0000000 0.0000000 0.0000000
ATOM   2: X=0.50000000 Y=0.50000000 Z=0.50000000
          MULT= 1          ISPLIT= 2
Sr4        NPT=  781  R0=0.00001000 RMT= 2.50000    Z: 38.0000                 
LOCAL ROT MATRIX:    1.0000000 0.0000000 0.0000000
                     0.0000000 1.0000000 0.0000000
                     0.0000000 0.0000000 1.0000000
ATOM   3: X=0.00000000 Y=0.00000000 Z=0.00000000
          MULT= 1          ISPLIT= 2
V 5        NPT=  781  R0=0.00005000 RMT= 1.92       Z: 23.0000                 
LOCAL ROT MATRIX:    1.0000000 0.0000000 0.0000000
                     0.0000000 1.0000000 0.0000000
                     0.0000000 0.0000000 1.0000000
  48      NUMBER OF SYMMETRY OPERATIONS
 1 0 0 0.00000000
 0 1 0 0.00000000
 0 0 1 0.00000000
       1
 0-1 0 0.00000000
 1 0 0 0.00000000
 0 0 1 0.00000000
       2
-1 0 0 0.00000000
 0-1 0 0.00000000
 0 0 1 0.00000000
       3
 0 1 0 0.00000000
-1 0 0 0.00000000
 0 0 1 0.00000000
       4
 1 0 0 0.00000000
 0 0-1 0.00000000
 0 1 0 0.00000000
       5
 1 0 0 0.00000000
 0-1 0 0.00000000
 0 0-1 0.00000000
       6
 1 0 0 0.00000000
 0 0 1 0.00000000
 0-1 0 0.00000000
       7
 0 0 1 0.00000000
 0 1 0 0.00000000
-1 0 0 0.00000000
       8
-1 0 0 0.00000000
 0 1 0 0.00000000
 0 0-1 0.00000000
       9
 0 0-1 0.00000000
 0 1 0 0.00000000
 1 0 0 0.00000000
      10
 0 0 1 0.00000000
 1 0 0 0.00000000
 0 1 0 0.00000000
      11
 0 1 0 0.00000000
 0 0 1 0.00000000
 1 0 0 0.00000000
      12
 0-1 0 0.00000000
 0 0-1 0.00000000
 1 0 0 0.00000000
      13
 0 0 1 0.00000000
-1 0 0 0.00000000
 0-1 0 0.00000000
      14
 0-1 0 0.00000000
 0 0 1 0.00000000
-1 0 0 0.00000000
      15
 0 0-1 0.00000000
-1 0 0 0.00000000
 0 1 0 0.00000000
      16
 0 0-1 0.00000000
 1 0 0 0.00000000
 0-1 0 0.00000000
      17
 0 1 0 0.00000000
 0 0-1 0.00000000
-1 0 0 0.00000000
      18
 0 1 0 0.00000000
 1 0 0 0.00000000
 0 0-1 0.00000000
      19
 0-1 0 0.00000000
-1 0 0 0.00000000
 0 0-1 0.00000000
      20
-1 0 0 0.00000000
 0 0 1 0.00000000
 0 1 0 0.00000000
      21
-1 0 0 0.00000000
 0 0-1 0.00000000
 0-1 0 0.00000000
      22
 0 0 1 0.00000000
 0-1 0 0.00000000
 1 0 0 0.00000000
      23
 0 0-1 0.00000000
 0-1 0 0.00000000
-1 0 0 0.00000000
      24
-1 0 0 0.00000000
 0-1 0 0.00000000
 0 0-1 0.00000000
      25
 0 1 0 0.00000000
-1 0 0 0.00000000
 0 0-1 0.00000000
      26
 1 0 0 0.00000000
 0 1 0 0.00000000
 0 0-1 0.00000000
      27
 0-1 0 0.00000000
 1 0 0 0.00000000
 0 0-1 0.00000000
      28
-1 0 0 0.00000000
 0 0 1 0.00000000
 0-1 0 0.00000000
      29
-1 0 0 0.00000000
 0 1 0 0.00000000
 0 0 1 0.00000000
      30
-1 0 0 0.00000000
 0 0-1 0.00000000
 0 1 0 0.00000000
      31
 0 0-1 0.00000000
 0-1 0 0.00000000
 1 0 0 0.00000000
      32
 1 0 0 0.00000000
 0-1 0 0.00000000
 0 0 1 0.00000000
      33
 0 0 1 0.00000000
 0-1 0 0.00000000
-1 0 0 0.00000000
      34
 0 0-1 0.00000000
-1 0 0 0.00000000
 0-1 0 0.00000000
      35
 0-1 0 0.00000000
 0 0-1 0.00000000
-1 0 0 0.00000000
      36
 0 1 0 0.00000000
 0 0 1 0.00000000
-1 0 0 0.00000000
      37
 0 0-1 0.00000000
 1 0 0 0.00000000
 0 1 0 0.00000000
      38
 0 1 0 0.00000000
 0 0-1 0.00000000
 1 0 0 0.00000000
      39
 0 0 1 0.00000000
 1 0 0 0.00000000
 0-1 0 0.00000000
      40
 0 0 1 0.00000000
-1 0 0 0.00000000
 0 1 0 0.00000000
      41
 0-1 0 0.00000000
 0 0 1 0.00000000
 1 0 0 0.00000000
      42
 0-1 0 0.00000000
-1 0 0 0.00000000
 0 0 1 0.00000000
      43
 0 1 0 0.00000000
 1 0 0 0.00000000
 0 0 1 0.00000000
      44
 1 0 0 0.00000000
 0 0-1 0.00000000
 0-1 0 0.00000000
      45
 1 0 0 0.00000000
 0 0 1 0.00000000
 0 1 0 0.00000000
      46
 0 0-1 0.00000000
 0 1 0 0.00000000
-1 0 0 0.00000000
      47
 0 0 1 0.00000000
 0 1 0 0.00000000
 1 0 0 0.00000000
      48

SrVO3.indmftpr

3                ! Nsort
3 1 1            ! Mult(Nsort)
3                ! lmax
complex          ! choice of angular harmonics
1 0 0 0          ! l included for each sort
0 0 0 0          ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
cubic            ! choice of angular harmonics
1 1 2 0          ! l included for each sort
0 0 2 0          ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
01               !
0                ! SO flag
complex          ! choice of angular harmonics
1 1 0 0          ! l included for each sort
0 0 0 0          ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
-0.11 0.14

Best Regards,
CMTCL

**Comment by mzingl** [comment]
In your struct file the V atom is the 3rd atom, but in your .indmftpr file it is the 2nd atom!

I don't know what you are doing to get such a struct file.
To check this for you, I took the given struct file from here:
https://triqs.github.io/dft_tools/2.1.x/tutorials/srvo3.html
and ran it through the wien2k init. The order of atoms does not change, Sr, V, and then O.
I only get the additional lines for the 48 symmetries.

**Comment by cmtcl18** [comment]
Dear Sir,
I took the SrVO3.struct file from the  https://triqs.github.io/dft_tools/2.1.x/tutorials/srvo3.html and followed the process. The same error is again occurring. 

/WIEN2k/SrVO3$ dmftproj
Welcome in DMFTPROJ: PROJECTION TO LOCALIZED BASIS


This prgm will build the Wannier projectors to the
localized orbitals of an atom onto which DMFT will be applied.


You are performing a computation
without Spin-Orbit.
using Paramagnetic Wien2k input files.
=======================================
Sorts of atoms =   3
Equivalent sites per each sort: 1 1 3


-------------------------------------
For the sort  1 :
The orbital l= 0 is included.

-------------------------------------
For the sort  2 :
The orbital l= 0 is included.
The orbital l= 1 is included.
The orbital l= 2 is included.

-------------------------------------
For the sort  3 :
The orbital l= 0 is included.
The orbital l= 1 is included.


The Eigenstates are projected in an energy window from   -0.11000 Ry  to     0.14000 Ry around the Fermi level.


=======================================
Basis representation for each sort.

At line 140 of file /src/triqs_dft_tools/fortran/dmftproj/set_ang_trans.f
Fortran runtime error: Bad real number in item 1 of list input

Error termination. Backtrace:
#0  0x14758746131a
#1  0x147587461ec5
#2  0x14758746268d
#3  0x1475875cfd42
#4  0x1475875d1ad5
#5  0x1475875d30f9
#6  0x55bfadd17624
#7  0x55bfadd0fec6
#8  0x55bfadd0ab2e
#9  0x147586ac0b96
#10  0x55bfadd0ab69
#11  0xffffffffffffffff


Sir, is there any problem in installation? How can I confirm that the installation have been done in a proper way?

Thank you for your suggestion.

Best Regards,
CMTCL

**Comment by cmtcl18** [comment]
Dear All,
Can any one suggest, how should I resolve above error.  

Best Regards,
CMTCL

**Comment by mzingl** [comment]
I suspect that you still have an error in your case.indmftpr file.
How does your struct file look like, how does your .indmftpr file look like?

**Comment by cmtcl18** [comment]
Dear Sir,
I am giving the srvo3.struct and srvo3.indmftpr file here.
srvo3.indmft file:
3                ! Nsort
1 1 3            ! Mult(Nsort)
3                ! lmax
complex          ! choice of angular harmonics
1 0 0 0          ! l included for each sort
0 0 0 0          ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
cubic            ! choice of angular harmonics
1 1 2 0          ! l included for each sort
0 0 2 0          ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
01               !
0                ! SO flag
complex          ! choice of angular harmonics
1 1 0 0          ! l included for each sort
0 0 0 0          ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
-0.11 0.14

srvo3.struct file:

SrVO3
P   LATTICE,NONEQUIV.ATOMS:  3221_Pm-3m
MODE OF CALC=RELA unit=bohr
  7.261300  7.261300  7.261300 90.000000 90.000000 90.000000
ATOM   1: X=0.00000000 Y=0.00000000 Z=0.00000000
          MULT= 1          ISPLIT= 2
Sr         NPT=  781  R0=0.00001000 RMT=   2.50000   Z: 38.0
LOCAL ROT MATRIX:    1.0000000 0.0000000 0.0000000
                     0.0000000 1.0000000 0.0000000
                     0.0000000 0.0000000 1.0000000
ATOM   2: X=0.50000000 Y=0.50000000 Z=0.50000000
          MULT= 1          ISPLIT= 2
V          NPT=  781  R0=0.00005000 RMT=   1.91      Z: 23.0
LOCAL ROT MATRIX:    1.0000000 0.0000000 0.0000000
                     0.0000000 1.0000000 0.0000000
                     0.0000000 0.0000000 1.0000000
ATOM  -3: X=0.00000000 Y=0.50000000 Z=0.50000000
          MULT= 3          ISPLIT=-2
      -3: X=0.50000000 Y=0.00000000 Z=0.50000000
      -3: X=0.50000000 Y=0.50000000 Z=0.00000000
O          NPT=  781  R0=0.00010000 RMT=   1.70      Z:  8.0
LOCAL ROT MATRIX:    0.0000000 0.0000000 1.0000000
                     0.0000000 1.0000000 0.0000000
                    -1.0000000 0.0000000 0.0000000
  48      NUMBER OF SYMMETRY OPERATIONS

For installation of TRIQS, DFTTools, CTHYB I followed  the commands from Debain package for ubuntu. I have not followed the commands of Compiling from source.  Shall I follow the commands from Compiling from source for the installation?


thank you for your response

Best Regards,
CMTCL
