### ISSUE TITLE
error in SrVO3.h5 

### ISSUE THREAD

**Issue by cmtcl18** [TRIQS/dft_tools#123]
Dear developers,
I am not able to read the SrVO3.h5 file. It is appearing as

<89>HDF^M
^Z
^@^@^@^@^@^H^H^@^D^@^P^@^@^@^@^@^@^@^@^@^@^@^@^@ÿÿÿÿÿÿÿÿ<80>÷3^@^@^@^@^@ÿÿÿÿÿÿÿÿ^@^@^@^@^@^@^@^@`^@^@^@^@^@^@^@^A^@^@^@^@^@^@^@<88>^@^@^@^@^@^@^@¨^B^@^@^@^@^@^@^A^@^A^@^A^@^@^@^X^@^@^@^@^@^@^@^Q^@^P^@^@^@^@^@<88>^@^@^@^@^@^@^@¨^B^@^@^@^@^@^@TREE^@^@^A^@ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ^@^@^@^@^@^@^@^@à^E^@^@^@^@^@^@p^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@HEAP^@^@^@^@°^@^@^@^@^@^@^@x^@^@^@^@^@^@^@à<95>#^@^@^@^@^@^A^@^D^@^A^@^@^@^X^@^@^@^@^@^@^@^P^@^P^@^@^@^@^@<80><9d>#^@^@^@^@^@p^@^@^@^@^@^@^@^A^@^D^@^A^@^@^@^X^@^@^@^@^@^@^@^P^@^P^@^@^@^@^@^HS&^@^@^@^@^@p^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^A^@^A^@^A^@^@^@^X^@^@^@^@^@^@^@^Q^@^P^@^@^@^@^@H^C^@^@^@^@^@@@     
Can you say what is the error here? I want to calculate density of states and band structures of SrVO3.
Any suggestion is appreciated.

Best Regards,
CMTCL

**Comment by cmtcl18** [comment]
Dear Sir,
I have been trying to short out this issue from last couple of weeks. I have installed TRIQS, DFTTools, CTHYB, MAXENT.  Can any one tell where I have done mistake with my SrVO3.h5 file, why it is not in the readable form? 
I will be thankful for your suggestion.

Best Regards,

CMTCL

**Comment by Wentzell** [comment]
Dear @cmtcl18,

HDF5 files are not intended to be opened in text editors .. 
Please follow the [tutorial](https://triqs.github.io/dft_tools/2.1.x/tutorials/srvo3.html#the-dmft-calculation) which shows how to use the `HDFArchive` class to access these files.
