### ISSUE TITLE
dmftproj -band error 

### ISSUE THREAD

**Issue by cmtcl18** [TRIQS/dft_tools#125]
Dear All,
I got the density of states (DOS) for SrVO3. I want to calculate the correlated band structure, for which it needs the SrVO3.outband file. I run the following command before calculating the  correlated band structures.
`x lapw1 -band`
`x lapw2 -band -almd`
`dmftproj -band`
During  `dmftproj -band` I am getting the following error.
At line 524 of file /home/jatin/triqs/src/fortran/dmftproj/dmftproj.f (unit = 7, file = 'SrVO3.indmftpr')
Fortran runtime error: End of file

Error termination. Backtrace:
#0  0x1512cbb0831a
#1  0x1512cbb08ec5
#2  0x1512cbb0968d
#3  0x1512cbc7fa33
#4  0x1512cbc789c4
#5  0x1512cbc7a0f9
#6  0x55a8630043f9
#7  0x55a862ffeb2e
#8  0x1512cb167b96
#9  0x55a862ffeb69
#10  0xffffffffffffffff

Can I know what is the error here?

I got large number of .dat file for DOS_parproj, Which will  represent the total DOS among them? If you need any extra information, I will happy to provide.

I will be thankful for your suggestion.

Best Regards
CMTCL

**Comment by cmtcl18** [comment]
Dear All,
In order to solve above problem, I edit the` SrVO3.in2` file and replaced `TOT with QTL` and `TETRA with ROOT` and I provided the Fermi energy. But still I am getting the same error. 

I will be happy for your suggestion.

Best Regards
CMTCL

**Comment by cmtcl18** [comment]
Dear Alex,
can you give any suggestion why at `dmftproj -band`  I am getting the above error. I have many `DOS_parproj_up.dat` and `DOS_parproj_down.dat`, so which should my totoal DOS?  I want to reproduce the correlated DOS and band structure from 'M Aichhorn, L Pourovskii, P Seth, V Vildosola, M Zingl, OE Peil, X Deng, ...
Computer physics communications 204, 200-208'.


Best Regards
CMTCL

**Comment by mzingl** [comment]
Dear CMTCL,

there is something wrong with your SrVO3.indmftpr file.
If you used the same file for your DFT+DMFT calculation and dmftproj worked without error, 
then you might miss the last line with the DFT Fermi level. Just add it as the last line, because
this information is necessary for -band calculations.
See the detailed [dmftproj documentation](https://triqs.github.io/dft_tools/latest/_downloads/TutorialDmftproj.pdf), 
where the structure of the indmftpr file is described in section 2.3.

Best, Manuel

**Comment by cmtcl18** [comment]
Dear Manuel,
Thank you very much for your suggestion. I followed the steps that you mentioned above. Now I have  `Akw_down.dat`_  and  `Akw_up.dat`  in my SrVO3 directory. I tried to plot the correlated band structure. I am getting the following plots.

band_up.
![band_up](https://user-images.githubusercontent.com/54096875/68656545-0c4f3580-0558-11ea-9f71-c53c08557c85.png) 

band_down.

![down_band](https://user-images.githubusercontent.com/54096875/68656697-50423a80-0558-11ea-8e9a-c4e1d6610c30.png)

For the density of states, I am getting a plenty of `DOS_parproj_up.dat` and `DOS_parproj_down.dat` file.

As I am doing the non-magnetic calculation, I have not define any `up` or `down` spin. 

Can you tell where is the error here and why the correlated band structure apperaing as straight line.

Best regards
CMTCL

**Comment by aichhorn** [comment]
The reason is simple. The files Akw_up.dat and Akw_down.dat do NOT contain data for a 2D plot. Look at the files, they contain data in three columns like
k   omega   value
So you need to do a 3D, or 2D greyscale, or similar, plot to visualize the data.
BTW, for paramagnetic solutions, up and down have to be identical.

**Comment by cmtcl18** [comment]
Dear Aichhorn,
Thank you for your suggestion. I tried to plot the correlated band structure using  'https://triqs.github.io/dft_tools/latest/faqs/faqs.html#how-do-i-plot-the-output-of-spaghettis'. I obtained the following plots.

![GMXZMG_Akw_up](https://user-images.githubusercontent.com/54096875/68736740-838fd280-0607-11ea-8954-9efce5a3cf74.png)

![GMXZMG_Akw_down](https://user-images.githubusercontent.com/54096875/68736747-8be80d80-0607-11ea-94b4-527cf94c29e7.png)

Both the band structures are similar, but I am getting only two bands.  

I have used `U = 4.0 & J = 0.65` and energy window `[-0.11,0.14]`. 
In order to reproduce  the correlated DOS and band structure from 'M Aichhorn, L Pourovskii, P Seth, V Vildosola, M Zingl, OE Peil, X Deng, ...
Computer physics communications 204, 200-208', Should I consider the same U, J and energy range?

Can you suggest, what is the error here?

**Comment by aichhorn** [comment]
I don't know what you mean by 'only two bands'. You have along some lines degeneracies of the bands as expected, but in the path from M to G you clearly see 3 excitations for each k point. So there is no error. You just calculate only t2g bands here. If you want the EXACT same picture of the CPC paper, you should use the EXACT same projection windos, U, and J.

**Comment by cmtcl18** [comment]
Dear Aichhorn,
Thank you very much for your suggestion. In order to get discrete and(multiple i.e more than one) t2g  bands, what should I do in   'https://triqs.github.io/dft_tools/latest/faqs/faqs.html#how-do-i-plot-the-output-of-spaghettis' as in  order to analyze the band structure, I should have multiple discrete bands.

**Comment by the-hampel** [comment]
It is not quite clear to me what you want to do. In your plot all t2g orbitals are visible, as you also did the calculation for those orbitals. If you want a similar plot as shown in https://arxiv.org/pdf/1511.01302.pdf Fig.5 , you should start by plotting first your DFT band structure. Than add in the same plot the data that you show above. That will bring you closer to what you want I guess. But, in Fig.5 or https://arxiv.org/pdf/1511.01302.pdf, they actually make a completely different calculation, by using a larger energy window constructing als localized orbitals for the Oxygen p states. 

You should maybe start by taking a look here: https://arxiv.org/abs/0906.3735 and pay special attention to the choice of correlated subspace. This is eplained there and especially in Appendix A the two different schemes of a "t2g only" versus a larger energy window "ddp" subspace is discussed for SrVO3. Hope that helps.

**Comment by the-hampel** [comment]
As far as I understood from your other issue #128 your problem as been solved right? I will close this here now. Please open another issue, if you still have problems.
