### ISSUE TITLE
put_Sigma: give exactly one Sigma for each inequivalent corr. shell

### ISSUE THREAD

**Issue by cmtcl18** [TRIQS/dft_tools#130]
Dear All,
During the self-consistency cycle for Spin Polarization (SP) calculation, I am getting the following error.

> Iteration =  1
Traceback (most recent call last):
  File "DMFTSC.py", line 65, in <module>
    SK.set_Sigma([ S.Sigma_iw ])                            # put Sigma into the SumK class
  File "/usr/lib/python2.7/dist-packages/triqs_dft_tools/sumk_dft.py", line 575, in set_Sigma
    self.put_Sigma(Sigma_imp)
  File "/usr/lib/python2.7/dist-packages/triqs_dft_tools/sumk_dft.py", line 592, in put_Sigma
    Sigma_imp) == self.n_inequiv_shells, "put_Sigma: give exactly one Sigma for each inequivalent corr. shell!"
AssertionError: put_Sigma: give exactly one Sigma for each inequivalent corr. shell!. 

Is there anything else should be introduced  for spin polarization calculation?

Best Regards
CMTCL

**Comment by hschnait** [comment]
Hi,

I assume this is from a calculation beginning with your SrIrO3.indmftpr from issue #128 ?
There you have taken two atoms as correlated

> ...
>  cubic ! choice of angular harmonics
> 1 0 2 0 ! l included for each sort
> 0 0 2 0 ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
> **01 !**
> 0 ! SO flag
> cubic ! choice of angular harmonics
> 1 1 2 0 ! l included for each sort
> 0 0 2 0 ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
> **01 !** 
> 0 ! SO flag
> ...

thus you end up with two correlated shells in your SumkDFT (your `SK.n_inequiv_shells` should give 2 I guess). In this case you would need to give a list of length 2 to `put_Sigma` (one self-energy for each correlated shell.

Now the question is, **what type of calculation** do you want to perform? For a paramagnetic calculation (with or without SOC/SP does not matter) you do not need two correlated sites - this is only necessary for e.g. antiferromagnetic calculations in a supercell.
If, on the other hand, you want to do (antiferro-)magnetic ordering, you do need this two-impurity structure. However, then you also need two self-energies to put into `put_Sigma` (so you either solve two impurity models, or you find a transformation from one impurity to the other one).

**Comment by cmtcl18** [comment]
Thank you for your response. I got this error during the self consistent calculation for `LaMnO3` with Spin Polarization. Here I am giving the `LaMnO3.indmftpr` file.

> 12                           ! Nsort
2 2 1 1 1 1 2 2 2 2 2 2      ! Mult(Nsort)
3                            ! lmax
complex                      ! choice of angular harmonics
1 0 0 0                      ! l included for each sort
0 0 0 0                      ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
complex                      ! choice of angular harmonics
1 0 0 0                      ! l included for each sort
0 0 0 0                      ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
cubic                        ! choice of angular harmonics
1 1 2 0                      ! l included for each sort
0 0 2 0                      ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
01                           !
0                            ! SO flag
cubic                        ! choice of angular harmonics
1 1 2 0                      ! l included for each sort
0 0 2 0                      ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
01                           !
0                            ! SO flag
cubic                        ! choice of angular harmonics
1 1 2 0                      ! l included for each sort
0 0 2 0                      ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
01                           !
0                            ! SO flag
cubic                        ! choice of angular harmonics
1 1 2 0                      ! l included for each sort
0 0 2 0                      ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
01                           !
0                            ! SO flag
cubic                        ! choice of angular harmonics
1 1 0 0                      ! l included for each sort
0 0 0 0                      ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
cubic                        ! choice of angular harmonics
1 1 0 0                      ! l included for each sort
0 0 0 0                      ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
cubic                        ! choice of angular harmonics
1 1 0 0                      ! l included for each sort
0 0 0 0                      ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
cubic                        ! choice of angular harmonics
1 1 0 0                      ! l included for each sort
0 0 0 0                      ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
cubic                        ! choice of angular harmonics
1 1 0 0                      ! l included for each sort
0 0 0 0                      ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
cubic                        ! choice of angular harmonics
1 1 0 0                      ! l included for each sort
0 0 0 0                      ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
-0.62  0.55      ! e_bot and e_top
 
For magnetic calculation (anti-ferromagnetic), in this case I need  four self-energy (as four Mn atoms are correlated) to put into `put_sigma`. Can you through some light explicitly, how should I pass the self-energy into `put_sigma`.

I will be thankful for your suggestion.

**Comment by the-hampel** [comment]
Hi, 
so you should do something like this:
```
sum_k.put_Sigma([solvers[icrsh].Sigma_iw for icrsh in range(sum_k.n_inequiv_shells)])
```
or equivalently
```
sigma_list = [ Sigma_iw_1 , Sigma_iw_2, Sigma_iw_3, Sigma_iw_4 ]
sum_k.put_Sigma( sigma_list )
```
Note, that you need to access the different solver instances correctly to obtain the different Sigma_iw objects. This means, that in my first example I had a list of solver instances `solvers= [solver1, solver2, ...]`.

**Comment by cmtcl18** [comment]
Dear Alex,
I supplied the `sigma_list = [ Sigma_iw_1 , Sigma_iw_2, Sigma_iw_3, Sigma_iw_4 ]` in the DMFT self-consistent loop. Now it is throwing the following error.

> Starting run with 1 MPI rank(s) at : 2020-02-07 10:39:50.358238
<triqs_dft_tools.sumk_dft.SumkDFT object at 0x1459fa8b4450>
Traceback (most recent call last):
  File "DMFTSC.py", line 63, in <module>
    sigma_list = [ Sigma_iw1, Sigma_iw2, Sigma_iw3, Sigma_iw4 ]
NameError: name 'Sigma_iw1' is not defined.

Can you tell, how should I construct different `Sigma_iw`, `solvers` for inequivalent correlated atoms.
For a point of visualization, the number of `Sigma_iw` and hence `Sigma_w` should same as the number of inequivalent correlated atoms (please correct me if I am wrong).

Best Regards
CMTCL

**Comment by the-hampel** [comment]
Hi,
`Sigma_iw_1` was just a placeholder for the variable name in python that you use. I do not know how your script looks like, but you have to extend it to multiple impurities in the manner I describe above. You can use the example on the dft_tools webpage [dft_dmft_cthyb.py](https://triqs.github.io/dft_tools/latest/_downloads/dft_dmft_cthyb.py) , but you have to extend it to multiple impurities. Which just means to create a loop in python over impurities and then store each solution of a solver run in a list.

**Comment by cmtcl18** [comment]
Dear Alex,
I tried to supply the different `solvers` to obtain different `Sigma_iw` corresponding to the inequivalent atoms. This time, I am getting the following error. 

> Starting run with 1 MPI rank(s) at : 2020-02-08 22:31:31.020519
<triqs_dft_tools.sumk_dft.SumkDFT object at 0x1541066cc4d0>
[0, 1, 2]
{'up_0': [0, 1, 2], 'down_0': [0, 1, 2]}
Iteration =  1
Traceback (most recent call last):
  File "DMFTSC.py", line 118, in <module>
    SK.put_Sigma([solvers[icrsh].Sigma_iw for icrsh in range(SK.n_inequiv_shells)])     # put Sigma into the SumK class
AttributeError: 'int' object has no attribute 'Sigma_iw' .

I am supplying the full self consistent python script here.

> ### PASS THE REQUIRE MODULE #####
from triqs_dft_tools.sumk_dft import *
from pytriqs.gf import *
from pytriqs.archive import HDFArchive
from pytriqs.operators.util import *
from triqs_cthyb import *
import pytriqs.utility.mpi as mpi


### DEFINE THE PARAMETERS #####
dft_filename = 'LaMnO3_n_FM'          # filename
U = 5.0                         # interaction parameters
J = 0.75
beta = 40                       # inverse temperature
loops = 15                      # number of DMFT loops
mix = 0.2                       # mixing factor of Sigma after solution of the AIM
dc_type = 0                     # DC type: 0 FLL, 1 Held, 2 AMF
use_blocks = True               # use bloc structure from DFT input
prec_mu = 0.0001                # precision of chemical potential
#h_field = 0.0

### INITIALIZE SumkDFT ####
SK = SumkDFT(hdf_file=dft_filename+'.h5',use_dft_blocks=use_blocks)
print SK

##### INITIALIZING THE CTHYB SOLVER #####
#### GIVE THE PARAMETERS FOR SOLVER ####
p = {}
# solver
p["random_seed"] = 123 * mpi.rank + 567
p["length_cycle"] = 200
p["n_warmup_cycles"] = 100000
p["n_cycles"] = 1000000
# tail fit
p["perform_tail_fit"] = True
p["fit_max_moment"] = 4
p["fit_min_n"] = 30
p["fit_max_n"] = 60



### TO INITIALIZE THE SOLVER CLASS, CONSISTING OF TWO STEPS ####

### 1. Calculating the multi-band interaction matrix, and constructing the interaction Hamiltonia
### 2.     Initializing the solver class itself.




n_orb = SK.corr_shells[0]['dim']
l = SK.corr_shells[0]['l']
spin_names = ["up","down"]
orb_names = [i for i in range(n_orb)]
print orb_names
gf_struct = SK.gf_struct_solver[0]
print gf_struct
# Use GF structure determined by DFT blocks:
gf_struct = [(block, indices) for block, indices in SK.gf_struct_solver[0].iteritems()]
# Construct U matrix for density-density calculations:
Umat, Upmat = U_matrix_kanamori(n_orb=n_orb, U_int=U, J_hund=J)

### CONSTRUCT THE HAMILTONIAN AND SOLVER ###
h_int = h_int_density(spin_names, orb_names, map_operator_structure=SK.sumk_to_solver[0], U=Umat, Uprime=Upmat)
S = Solver(beta=beta, gf_struct=gf_struct)

solvers = list(i for i in range(SK.n_inequiv_shells))
    



previous_runs = 0
previous_present = False
if mpi.is_master_node():
    with HDFArchive(dft_filename+'.h5','a') as f:
        if 'dmft_output' in f:
            ar = f['dmft_output']
            if 'iterations' in ar:
                previous_present = True
                previous_runs = ar['iterations']
        else:
            f.create_group('dmft_output')
previous_runs    = mpi.bcast(previous_runs)
previous_present = mpi.bcast(previous_present)



if previous_present:
  chemical_potential = 0
  dc_imp = 0
  dc_energ = 0
  if mpi.is_master_node():
      with HDFArchive(dft_filename+'.h5','r') as ar:
        S.Sigma_iw << ar['dmft_output']['Sigma_iw']
      chemical_potential,dc_imp,dc_energ = SK.load(['chemical_potential','dc_imp','dc_energ'])
  S.Sigma_iw << mpi.bcast(S.Sigma_iw)
  chemical_potential = mpi.bcast(chemical_potential)
  dc_imp = mpi.bcast(dc_imp)
  dc_energ = mpi.bcast(dc_energ)
  SK.set_mu(chemical_potential)
  SK.set_dc(dc_imp,dc_energ)



### Initialize the subgroup in the h5 file to store the result ###

if mpi.is_master_node():
    with HDFArchive(dft_filename+'.h5') as ar:
        if (not ar.is_group('dmft_output')):
            ar.create_group('dmft_output')



#### SELF-CONSISTENCY LOOP ####
for iteration_number in range(1,loops+1):
    if mpi.is_master_node(): print "Iteration = ", iteration_number

    SK.symm_deg_gf(S.Sigma_iw,orb=0)                        # symmetrizing Sigma
    SK.put_Sigma([solvers[icrsh].Sigma_iw for icrsh in range(SK.n_inequiv_shells)])     # put Sigma into the SumK class
    chemical_potential = SK.calc_mu( precision = prec_mu )  # find the chemical potential for given density
    S.G_iw << SK.extract_G_loc()[0]                         # calc the local Green function
    mpi.report("Total charge of Gloc : %.6f"%S.G_iw.total_density())

    # Init the DC term and the real part of Sigma, if no previous runs found:
    if (iteration_number==1 and previous_present==False):
        dm = S.G_iw.density()
        SK.calc_dc(dm, U_interact = U, J_hund = J, orb = 0, use_dc_formula = dc_type)
        S.Sigma_iw << SK.dc_imp[0]['up'][0,0]

    # Calculate new G0_iw to input into the solver:
    S.G0_iw << S.Sigma_iw + inverse(S.G_iw)
    S.G0_iw << inverse(S.G0_iw)

    # Solve the impurity problem:
    S.solve(h_int=h_int, **p)

    # Solved. Now do post-solution stuff:
    mpi.report("Total charge of impurity problem : %.6f"%S.G_iw.total_density())

    # Now mix Sigma and G with factor mix, if wanted:
    if (iteration_number>1 or previous_present):
        if mpi.is_master_node():
            with HDFArchive(dft_filename+'.h5','r') as ar:
                mpi.report("Mixing Sigma and G with factor %s"%mix)
                S.Sigma_iw << mix * S.Sigma_iw + (1.0-mix) * ar['dmft_output']['Sigma_iw']
                S.G_iw << mix * S.G_iw + (1.0-mix) * ar['dmft_output']['G_iw']
        S.G_iw << mpi.bcast(S.G_iw)
        S.Sigma_iw << mpi.bcast(S.Sigma_iw)

    # Write the final Sigma and G to the hdf5 archive:
    if mpi.is_master_node():
        with HDFArchive(dft_filename+'.h5','a') as ar:
              ar['dmft_output']['iterations'] = iteration_number
              ar['dmft_output']['G_0'] = S.G0_iw
              ar['dmft_output']['G_tau'] = S.G_tau
              ar['dmft_output']['G_iw'] = S.G_iw
              ar['dmft_output']['Sigma_iw'] = S.Sigma_iw

    # Set the new double counting:
    dm = S.G_iw.density() # compute the density matrix of the impurity problem
    SK.calc_dc(dm, U_interact = U, J_hund = J, orb = 0, use_dc_formula = dc_type)

    # Save stuff into the user_data group of hdf5 archive in case of rerun:
    SK.save(['chemical_potential','dc_imp','dc_energ']) .


Thanks

**Comment by cmtcl18** [comment]
Dear Alex,
I passed `sum_k.put_Sigma([solvers[icrsh].Sigma_iw for icrsh in range(sum_k.n_inequiv_shells)])` in the self-consistent cycle. While producing the loop for different impurity, it's throwing error.

> ### PASS THE REQUIRE MODULE #####
from triqs_dft_tools.sumk_dft import *
from pytriqs.gf import *
from pytriqs.archive import HDFArchive
from pytriqs.operators.util import *
from triqs_cthyb import *
import pytriqs.utility.mpi as mpi


### DEFINE THE PARAMETERS #####
dft_filename = 'LaMnO3_n_FM'          # filename
U = 5.0                         # interaction parameters
J = 0.75
beta = 40                       # inverse temperature
loops = 15                      # number of DMFT loops
mix = 0.2                       # mixing factor of Sigma after solution of the AIM
dc_type = 0                     # DC type: 0 FLL, 1 Held, 2 AMF
use_blocks = True               # use bloc structure from DFT input
prec_mu = 0.0001                # precision of chemical potential
#h_field = 0.0

### INITIALIZE SumkDFT ####
SK = SumkDFT(hdf_file=dft_filename+'.h5',use_dft_blocks=use_blocks)


##### INITIALIZING THE CTHYB SOLVER #####
#### GIVE THE PARAMETERS FOR SOLVER ####
p = {}
# solver
p["random_seed"] = 123 * mpi.rank + 567
p["length_cycle"] = 200
p["n_warmup_cycles"] = 100000
p["n_cycles"] = 1000000
# tail fit
p["perform_tail_fit"] = True
p["fit_max_moment"] = 4
p["fit_min_n"] = 30
p["fit_max_n"] = 60



### TO INITIALIZE THE SOLVER CLASS, CONSISTING OF TWO STEPS ####

### 1. Calculating the multi-band interaction matrix, and constructing the interaction Hamiltonia
### 2.     Initializing the solver class itself.




n_orb = SK.corr_shells[0]['dim']
l = SK.corr_shells[0]['l']
spin_names = ["up","down"]
orb_names = [i for i in range(n_orb)]
# Use GF structure determined by DFT blocks:
gf_struct = [(block, indices) for block, indices in SK.gf_struct_solver[0].iteritems()]
# Construct U matrix for density-density calculations:
Umat, Upmat = U_matrix_kanamori(n_orb=n_orb, U_int=U, J_hund=J)
### CONSTRUCT THE HAMILTONIAN AND SOLVER ###
h_int = h_int_density(spin_names, orb_names, map_operator_structure=SK.sumk_to_solver[0], U=Umat, Uprime=Upmat)

S = Solver(beta=beta, gf_struct=gf_struct)
#print S
for icrsh in S.Sigma_iw:
    solvers = list(solver)
    

previous_runs = 0
previous_present = False
if mpi.is_master_node():
    with HDFArchive(dft_filename+'.h5','a') as f:
        if 'dmft_output' in f:
            ar = f['dmft_output']
            if 'iterations' in ar:
                previous_present = True
                previous_runs = ar['iterations']
        else:
            f.create_group('dmft_output')
previous_runs    = mpi.bcast(previous_runs)
previous_present = mpi.bcast(previous_present)


if previous_present:
  chemical_potential = 0
  dc_imp = 0
  dc_energ = 0
  if mpi.is_master_node():
      with HDFArchive(dft_filename+'.h5','r') as ar:
        S.Sigma_iw << ar['dmft_output']['Sigma_iw']
      chemical_potential,dc_imp,dc_energ = SK.load(['chemical_potential','dc_imp','dc_energ'])
  S.Sigma_iw << mpi.bcast(S.Sigma_iw)
  chemical_potential = mpi.bcast(chemical_potential)
  dc_imp = mpi.bcast(dc_imp)
  dc_energ = mpi.bcast(dc_energ)
  SK.set_mu(chemical_potential)
  SK.set_dc(dc_imp,dc_energ)



### Initialize the subgroup in the h5 file to store the result ###

if mpi.is_master_node():
    with HDFArchive(dft_filename+'.h5') as ar:
        if (not ar.is_group('dmft_output')):
            ar.create_group('dmft_output')



#### SELF-CONSISTENCY LOOP ####
for iteration_number in range(1,loops+1):
    if mpi.is_master_node(): print "Iteration = ", iteration_number

    SK.symm_deg_gf(S.Sigma_iw,orb=0)                        # symmetrizing Sigma
    SK.put_Sigma([solvers[icrsh].Sigma_iw for icrsh in range(SK.n_inequiv_shells)])     # put Sigma into the SumK class
    chemical_potential = SK.calc_mu( precision = prec_mu )  # find the chemical potential for given density
    S.G_iw << SK.extract_G_loc()[0]                         # calc the local Green function
    mpi.report("Total charge of Gloc : %.6f"%S.G_iw.total_density())

    # Init the DC term and the real part of Sigma, if no previous runs found:
    if (iteration_number==1 and previous_present==False):
        dm = S.G_iw.density()
        SK.calc_dc(dm, U_interact = U, J_hund = J, orb = 0, use_dc_formula = dc_type)
        S.Sigma_iw << SK.dc_imp[0]['up'][0,0]

    # Calculate new G0_iw to input into the solver:
    S.G0_iw << S.Sigma_iw + inverse(S.G_iw)
    S.G0_iw << inverse(S.G0_iw)

    # Solve the impurity problem:
    S.solve(h_int=h_int, **p)

    # Solved. Now do post-solution stuff:
    mpi.report("Total charge of impurity problem : %.6f"%S.G_iw.total_density())

    # Now mix Sigma and G with factor mix, if wanted:
    if (iteration_number>1 or previous_present):
        if mpi.is_master_node():
            with HDFArchive(dft_filename+'.h5','r') as ar:
                mpi.report("Mixing Sigma and G with factor %s"%mix)
                S.Sigma_iw << mix * S.Sigma_iw + (1.0-mix) * ar['dmft_output']['Sigma_iw']
                S.G_iw << mix * S.G_iw + (1.0-mix) * ar['dmft_output']['G_iw']
        S.G_iw << mpi.bcast(S.G_iw)
        S.Sigma_iw << mpi.bcast(S.Sigma_iw)

    # Write the final Sigma and G to the hdf5 archive:
    if mpi.is_master_node():
        with HDFArchive(dft_filename+'.h5','a') as ar:
              ar['dmft_output']['iterations'] = iteration_number
              ar['dmft_output']['G_0'] = S.G0_iw
              ar['dmft_output']['G_tau'] = S.G_tau
              ar['dmft_output']['G_iw'] = S.G_iw
              ar['dmft_output']['Sigma_iw'] = S.Sigma_iw

    # Set the new double counting:
    dm = S.G_iw.density() # compute the density matrix of the impurity problem
    SK.calc_dc(dm, U_interact = U, J_hund = J, orb = 0, use_dc_formula = dc_type)

    # Save stuff into the user_data group of hdf5 archive in case of rerun:
    SK.save(['chemical_potential','dc_imp','dc_energ']).

The error is 

> Starting run with 1 MPI rank(s) at : 2020-02-10 22:03:42.112959
Traceback (most recent call last):
  File "DMFTSC.py", line 64, in <module>
    solvers = list(solver)
NameError: name 'solver' is not defined .

Can you suggest, how I should eliminate the error.

Best regards
CMTCL

**Comment by the-hampel** [comment]
This is not how you create a proper list in python. You want to create a list of solvers, and a minimal example using sumk and the cthyb solver would be
```
solvers = []
for icrsh in range(SK.n_inequiv_shells):
    solvers.append(Solver(beta=beta_value, gf_struct=SK.gf_struct_solver[icrsh]))
```
Now `solvers` contains a list of solver instances. The same needs then to be done for the interaction Hamiltonian etc. At the moment there is no such example online...

To understand this better, I urge you to take a look here: http://swcarpentry.github.io/python-novice-gapminder/ , they provide very good programming online courses. This will boost your understanding on how to use triqs! You need to develop your own python program to run such calculations you want to do. 

A very comprehensive example can be found here: https://github.com/materialstheory/soliDMFT in the file dmft_cycle.py. However, be very careful when doing this and understand the basic steps.

**Comment by cmtcl18** [comment]
Dear All,
I modified the self consistent DMFT python script according to the system I have considered. While constructing the interaction Hamiltonian, it's throwing error.  Here I am giving the full python script and the error.

> ### PASS THE REQUIRE MODULE #####
from triqs_dft_tools.sumk_dft import *
from pytriqs.gf import *
from pytriqs.archive import HDFArchive
from pytriqs.operators.util import *
from triqs_cthyb import *
import pytriqs.utility.mpi as mpi


### DEFINE THE PARAMETERS #####
dft_filename = 'LaMnO3_n_FM'          # filename
U = 5.0                         # interaction parameters
J = 0.75
beta = 40                       # inverse temperature
loops = 15                      # number of DMFT loops
mix = 0.2                       # mixing factor of Sigma after solution of the AIM
dc_type = 0                     # DC type: 0 FLL, 1 Held, 2 AMF
use_blocks = True               # use bloc structure from DFT input
prec_mu = 0.0001                # precision of chemical potential
#h_field = 0.0

### INITIALIZE SumkDFT ####
SK = SumkDFT(hdf_file=dft_filename+'.h5',use_dft_blocks=use_blocks)


##### INITIALIZING THE CTHYB SOLVER #####
#### GIVE THE PARAMETERS FOR SOLVER ####
p = {}
# solver
p["random_seed"] = 123 * mpi.rank + 567
p["length_cycle"] = 200
p["n_warmup_cycles"] = 100000
p["n_cycles"] = 1000000
# tail fit
p["perform_tail_fit"] = True
p["fit_max_moment"] = 4
p["fit_min_n"] = 30
p["fit_max_n"] = 60



### TO INITIALIZE THE SOLVER CLASS, CONSISTING OF TWO STEPS ####

### 1. Calculating the multi-band interaction matrix, and constructing the interaction Hamiltonia
### 2.     Initializing the solver class itself.


#for param_name in ('U', 'J'):
#    general_parameters = _extract_U_J_list(para_name, SK.n_inequiv_shells, general_parameters)
### The SYSTEM CONTAINS FOUR INEQUIVALENT  CORRELATED ATOMS, HENCE THE SOLVER AND INTERACTION HAMILTONIAN SHOULD BE CONTRIBUTED BY THESE COORELATED ATOMS.


h_int = []
solvers = []
for icrsh in range(SK.n_inequiv_shells):
    #ish = SK.n_inequiv_shells[icrsh]
    n_orb = SK.corr_shells[icrsh]['dim']
    print(n_orb)
    l = SK.corr_shells[icrsh]['l']
    spin_names = ["up","down"]
    orb_names = [i for i in range(n_orb)]
    # Use GF structure determined by DFT blocks:
    gf_struct = [(block, indices) for block, indices in SK.gf_struct_solver[icrsh].iteritems()]
    print(gf_struct)
    # Construct U matrix for density-density calculations:
    #if n_orb in (2,3):
    Umat, Upmat = U_matrix_kanamori(n_orb=n_orb, U_int=['U'][icrsh], J_hund=['J'][icrsh] # basis= 'cubic')
        #print Umat, Upmat  
    h_int.append(h_int_density(spin_names, orb_names, map_operator_structure=SK.SK_to_solver[icrsh], U=Umat, Uprime=Upmat))
    solvers.append(Solver(beta=beta, gf_struct=SK.gf_struct_solver[icrsh]))  
       
previous_runs = 0
previous_present = False
if mpi.is_master_node():
    with HDFArchive(dft_filename+'.h5','a') as f:
        if 'dmft_output' in f:
            ar = f['dmft_output']
            if 'iterations' in ar:
                previous_present = True
                previous_runs = ar['iterations']
        else:
            f.create_group('dmft_output')
previous_runs    = mpi.bcast(previous_runs)
previous_present = mpi.bcast(previous_present)

if previous_present:
  chemical_potential = 0
  dc_imp = 0
  dc_energ = 0
  if mpi.is_master_node():
      with HDFArchive(dft_filename+'.h5','r') as ar:
        S.Sigma_iw << ar['dmft_output']['Sigma_iw']
      chemical_potential,dc_imp,dc_energ = SK.load(['chemical_potential','dc_imp','dc_energ'])
  S.Sigma_iw << mpi.bcast(S.Sigma_iw)
  chemical_potential = mpi.bcast(chemical_potential)
  dc_imp = mpi.bcast(dc_imp)
  dc_energ = mpi.bcast(dc_energ)
  SK.set_mu(chemical_potential)
  SK.set_dc(dc_imp,dc_energ)



### Initialize the subgroup in the h5 file to store the result ###

if mpi.is_master_node():
    with HDFArchive(dft_filename+'.h5') as ar:
        if (not ar.is_group('dmft_output')):
            ar.create_group('dmft_output')

#for icrsh in range(SK.n_inequiv_shells):
    

#### SELF-CONSISTENCY LOOP ####
for iteration_number in range(1,loops+1):
    if mpi.is_master_node(): print "Iteration = ", iteration_number
    for icrsh in range(SK.n_inequiv_shells):
        SK.symm_deg_gf(solvers[icrsh].Sigma_iw, orb=icrsh)                        # symmetrizing Sigma
    SK.put_Sigma([solvers[icrsh].Sigma_iw for icrsh in range(SK.n_inequiv_shells)])     # put Sigma into the SumK class
    chemical_potential = SK.calc_mu( precision = prec_mu )  # find the chemical potential for given density
    S.G_iw << SK.extract_G_loc()[0]                         # calc the local Green function
    mpi.report("Total charge of Gloc : %.6f"%S.G_iw.total_density())

    # Init the DC term and the real part of Sigma, if no previous runs found:
    if (iteration_number==1 and previous_present==False):
        dm = S.G_iw.density()
        SK.calc_dc(dm, U_interact = U, J_hund = J, orb = 0, use_dc_formula = dc_type)
        S.Sigma_iw << SK.dc_imp[0]['up'][0,0]

    # Calculate new G0_iw to input into the solver:
    S.G0_iw << S.Sigma_iw + inverse(S.G_iw)
    S.G0_iw << inverse(S.G0_iw)

    # Solve the impurity problem:
    S.solve(h_int=h_int, **p)

    # Solved. Now do post-solution stuff:
    mpi.report("Total charge of impurity problem : %.6f"%S.G_iw.total_density())

    # Now mix Sigma and G with factor mix, if wanted:
    if (iteration_number>1 or previous_present):
        if mpi.is_master_node():
            with HDFArchive(dft_filename+'.h5','r') as ar:
                mpi.report("Mixing Sigma and G with factor %s"%mix)
                S.Sigma_iw << mix * S.Sigma_iw + (1.0-mix) * ar['dmft_output']['Sigma_iw']
                S.G_iw << mix * S.G_iw + (1.0-mix) * ar['dmft_output']['G_iw']
        S.G_iw << mpi.bcast(S.G_iw)
        S.Sigma_iw << mpi.bcast(S.Sigma_iw)

    # Write the final Sigma and G to the hdf5 archive:
    if mpi.is_master_node():
        with HDFArchive(dft_filename+'.h5','a') as ar:
              ar['dmft_output']['iterations'] = iteration_number
              ar['dmft_output']['G_0'] = S.G0_iw
              ar['dmft_output']['G_tau'] = S.G_tau
              ar['dmft_output']['G_iw'] = S.G_iw
              ar['dmft_output']['Sigma_iw'] = S.Sigma_iw

    # Set the new double counting:
    dm = S.G_iw.density() # compute the density matrix of the impurity problem
    SK.calc_dc(dm, U_interact = U, J_hund = J, orb = 0, use_dc_formula = dc_type)

    # Save stuff into the user_data group of hdf5 archive in case of rerun:
    SK.save(['chemical_potential','dc_imp','dc_energ']).


>  File "DMFTSC.py", line 86
    h_int.append(h_int_density(spin_names, orb_names, map_operator_structure=SK.SK_to_solver[icrsh], U=Umat, Uprime=Upmat))
        ^
SyntaxError: invalid syntax.


Is there any error with the interaction Hamiltonian? 
Can anyone suggest, where is the error.

**Comment by the-hampel** [comment]
This error is completely python related! (and also very hard to read, due to mixing different markdown formats!)
```
Umat, Upmat = U_matrix_kanamori(n_orb=n_orb, U_int=['U'][icrsh], J_hund=['J'][icrsh] # basis= 'cubic')
```
there is a `#` comment in this line, which then leads to the error you mentioned, because the parenthesis is not closed. Either you add a `)` before the `#`, or remove the comment. Please try to go through the basic python lectures I mentioned earlier. We do want to discuss here actual issues in dfttools.
