### ISSUE TITLE
DFT tools in ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by fellipebc** [TRIQS/dft_tools#139]
i'm trying to install the DFt tools in a 20.04 LTS Ubuntu version, but i could not find by using the command "sudo apt-get install -y triqs_dft_tools"
Aren't the package available for this ubunto version ?  
thanks

**Comment by Wentzell** [comment]
Dear @fellipebc,

The packages for Ubuntu 20.04 LTS are unfortunately not yet available.
We are investigating if we can make packages available for the 2.2 release of triqs/dft_tools given that Python 2 is no longer fully supported in 20.04.
We will definitely have packages available for the coming release (3.0.0) of triqs/dft_tools in the near future. Note that this release will be fully based on Python 3.

In the mean-time you can use the [anaconda packages](https://triqs.github.io/dft_tools/latest/install.html#anaconda-experimental) to set up an installation of triqs + dft_tools in your home-directory of Ubuntu 20.04.

**Comment by fellipebc** [comment]
Dear @Wentzell, 
thank you for the answer, i'll try using the anaconda packages

**Comment by Wentzell** [comment]
@fellipebc Did you succeed? Can we close this issue?
