### ISSUE TITLE
ATTRIBUTE ERROR IN CALULATING DOS AND BAND STRUCTURE

### ISSUE THREAD

**Issue by cmtcl18** [TRIQS/dft_tools#140]
Dear All,
The AttributeError is appearing while calculating the density of states (DOS) and band structures. The `DFTTools` is installed through `conda`.
When the `DFTTools` is installed through  `Ubuntu Debian packages`,  it's working fine. 
What I felt is that the source file will not be changed if we install through   DFTTools   or  `Ubuntu Debian packages`.   
The following error is appearing.

>  Starting run with 1 MPI rank(s) at : 2020-05-18 18:26:52.155433
/home/hp/miniconda2/lib/python2.7/site-packages/pytriqs/gf/gf.py:359: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  dat = self._data[ self._rank * [slice(0,None)] + key_lst ]
Traceback (most recent call last):
  File "DOS.py", line 14, in <module>
    SK.dos_parproj_basis(broadening=0.2, with_Sigma=True, with_dc=True, save_to_file=True)
  File "/home/hp/miniconda2/lib/python2.7/site-packages/triqs_dft_tools/sumk_dft_tools.py", line 235, in dos_parproj_basis
    om_mesh = [x.real for x in self.Sigma_imp_w[0].mesh]
AttributeError: 'SumkDFTTools' object has no attribute 'Sigma_imp_w'

I would be thankful for any suggestions, any correction on my opinion is highly appreciated. 

Best Regards
CMTCL

**Comment by the-hampel** [comment]
Hi Cmtcl, 
this error appears if no `Sigma` has been set in the SumK object. Did you put it via `SK.put_sigma([Sigma_imp_w])` ? before calling `SK.dos_parproj_basis`? Please paste your used python script here.

**Comment by cmtcl18** [comment]
Dear Alex,
you are correct. I put the real-frequency self energy via `SK.set_sigma([SigmaReFreq]).

Here I have given the python script for evaluating the electronic structures.
`

> from triqs_dft_tools.sumk_dft_tools import *

SK = SumkDFTTools(hdf_file = 'LaMnO3.h5')
SK.analyse_block_structure()

with HDFArchive('LaMnO3.h5', 'r') as ar:
    SigmaReFreq = ar['dmft_output']['Sigma_w']

SK.set_Sigma([SigmaReFreq])
chemical_potential, dc_imp, dc_energ = SK.load(['chemical_potential', 'dc_imp', 'dc_energ'])
SK.set_mu(chemical_potential)
SK.set_dc(dc_imp,dc_energ)

SK.dos_parproj_basis(broadening=0.2, with_Sigma=True, with_dc=True, save_to_file=True)
SK.spaghettis(broadening=0.8,plot_shift=0.0,plot_rang=None,ishell=None,save_to_file= 'Akw_')


Thank You

**Comment by the-hampel** [comment]
Mh, I assume that the `SigmaReFreq = ar['dmft_output']['Sigma_w']` is a real frequency Sigma not `iw` right? Can you insert a print to check if the `Sigma_w` is correctly stored in the SumK object with `print SK.Sigma_imp_w` right before you call `SK.dos_parproj_basis) ? This should give you the type of Green's function, like: `Greens Function Sigma_w_0_up_0 with mesh Linear Mesh of size 5000 and target_rank 2` . 

Furthermore, I don't see why this should not work with the Conda packages. What is the difference of `/home/hp/miniconda2/lib/python2.7/site-packages/triqs_dft_tools/sumk_dft_tools.py` and the packaged `sumk_dft_tools.py`? Python seems to be set up correctly. Otherwise it would complain earlier.

**Comment by cmtcl18** [comment]
Hi,
The print SK.Sigma_imp_w, is showing attribute error. 

> Starting run with 1 MPI rank(s) at : 2020-05-19 08:22:39.692450
/home/hp/miniconda2/lib/python2.7/site-packages/pytriqs/gf/gf.py:359: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  dat = self._data[ self._rank * [slice(0,None)] + key_lst ]
Traceback (most recent call last):
  File "DOS.py", line 14, in <module>
    print SK.Sigma_imp_w
AttributeError: 'SumkDFTTools' object has no attribute 'Sigma_imp_w'

**Comment by the-hampel** [comment]
This means, that the `SK.set_Sigma([SigmaReFreq])` did not work as you expected. Can you cross-check whether the `ar['dmft_output']['Sigma_w']` stored in the h5 archive is actually okay? This needs to be a **real** frequency mesh Green's function. You can check by simply checking the mesh: `print SigmaReFreq.mesh`. This should give you: `Linear Mesh of size 5000` or different size.

**Comment by cmtcl18** [comment]
Hi,
the ` print SigmaReFreq.mesh ` is giving Matsubara Freq Mesh of size 2050.

This is the output.
Starting run with 1 MPI rank(s) at : 2020-05-19 13:03:44.009767
Matsubara Freq Mesh of size 2050, Domain: Matsubara domain with beta = 40, statistic = Fermion, positive_only : 0
/home/hp/miniconda2/lib/python2.7/site-packages/pytriqs/gf/gf.py:359: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  dat = self._data[ self._rank * [slice(0,None)] + key_lst ]
Traceback (most recent call last):
  File "DOS.py", line 15, in <module>
    print SK.Sigma_imp_w
AttributeError: 'SumkDFTTools' object has no attribute 'Sigma_imp_w'

I did the analytical continuation for converting the self-energy on the imaginary axis to self-energy on the real axis. It should be on the real-frequency axis.

**Comment by the-hampel** [comment]
Okay but then the problem is resolved. You need to load the real frequency mesh Sigma, from the analytic continuation. Please check your script doing the continuation and the storage. Maybe you just stored the wrong Sigma in the archive. This has then nothing to do with different triqs environements.

**Comment by cmtcl18** [comment]
Hi Alex,
I stored the wrong Sigma in the archive, so the AttributeError was appearing. 
Thank you for your suggestions.
I am closing this discussion here.
