### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by chuffa** [TRIQS/dft_tools#142]
Recently, the determination of the chemical potential did not converge and I had no idea what went wrong until I realized that the self-energy I provided was defined on a much too small energy range.

Therefore I am wondering if a warning, especially in calc_mu, should be added when the bounds of the self-energy do not cover a reasonable energy range. 

Since in some cases one might want to provide a self-energy on a small energy grid to speed up the computation (not necessarily for the chemical potential) I think a warning is the best solution.

**Comment by mzingl** [comment]
Let me add that this is only relevant for real-frequency self-energies.
We could have the set_Sigma function throw a warning if the mesh of the self-energy does not full cover the energy range set by the bare DOS, e.g. the lowest/highest element in the hoppings entry in the h5 file.

**Comment by mzingl** [comment]
Has been added in a recent pull request by Jonathan (commit 46ecd2c).
