### ISSUE TITLE
ERROR: eigenvalue mismatch between equivalent shells

### ISSUE THREAD

**Issue by ZhijieFan** [TRIQS/dft_tools#150]
Hi, 

I am recent working on a one-shot DFT+DMFT of FeSb2 using QE+Wannier90+TRIQS with cthyb solver. There are two equivalent Fe atoms in the unit cell, so the FeSb2.inp file is set to be:

0 2 2 4
28.0
2
0 0 2 5 0 0
1 0 2 5 0 0

However, the Wannier90Converter gave the following error when converting the dft input:
ERROR: eigenvalue mismatch between equivalent shells! 1
Eigenvalue difference: [-1.45371156e-03  2.10248309e-05 -6.75516328e-04  1.47512513e-04  1.70690544e-04]

I understand that this error occors because the two Fe atoms have mismatch eigenvalues, but we cannot generate a hr.dat file with perfectly matched Fe eigenvalues using Wannier90. 

Is it possible to enforce equivalence of the Fe atoms by hand in the dmft script? This error leads to use_rotations = 0. How will this affect the calculation?

Thank you 

Best,
Zhijie

**Comment by phibeck** [comment]
Hi Zhijie,

at the moment I am not aware of an option to enforce symmetry between atoms. However, if you want the code to ignore the symmetry mismatch you can avoid the error by lowering the error threshold which is currently set as `w90zero = 2.e-6`. You can check if this gives reasonably results by setting up another run where you set up the two Fe sites as inequivalent and comparing the DMFT results.

However, if QE uses the symmetry that correctly identifies the two Fe atoms as identical, then I would recommend to rather investigate why within Wannier90 the two sites become inequivalent. Were you able to identify the reason for this?

Best,
Sophie

**Comment by ZhijieFan** [comment]
> Hi Zhijie,
> 
> at the moment I am not aware of an option to enforce symmetry between atoms. However, if you want the code to ignore the symmetry mismatch you can avoid the error by lowering the error threshold which is currently set as `w90zero = 2.e-6`. You can check if this gives reasonably results by setting up another run where you set up the two Fe sites as inequivalent and comparing the DMFT results.
> 
> However, if QE uses the symmetry that correctly identifies the two Fe atoms as identical, then I would recommend to rather investigate why within Wannier90 the two sites become inequivalent. Were you able to identify the reason for this?
> 
> Best,
> Sophie

**Comment by ZhijieFan** [comment]
Thank you for your suggestion. I will check if avoiding the error by lowering the error threshold can give reasonable results and comparing with inequivalent Fe sites runs.

Unfortunately, I have no control for the wannierization process. The Wannier90 part is done by another group mate and he cannot identified why the output of Wannier90 is not symmetrized. In this case, it is necessary to include all Fe-d orbtitals and Sb-p orbitals in the Wannierization to obtain reasoable MLWFs. It is difficult for this process to converge. 

Best,
Zhijie
