### ISSUE TITLE
problem with triqs version

### ISSUE THREAD

**Issue by Reyhanehe** [TRIQS/dft_tools#156]
Dear all
 Hi
Happy new year:)
 I want use hubbardI method using triqs 3.0.0 and using WIEN2k codes. But when I want to run "python ce_gamma.py" from "triqs webpage", I have following error:
 from triqs.applications.impurity_solvers.hubbard_I.hubbard_solver import Solver ModuleNotFoundError: No module named 'triqs.applications'
 Can you please help me to solve this error?
 noticable that I installed triqs and hubbardI package without any errors. I should add some lines similar to triqs.install in my bashrs? if yes, what?
 Thanks a lot
 Sincerely yours
 Reyhaneh

**Comment by the-hampel** [comment]
Hi, 

I guess this line is not correct anymore for triqs 3.x.x . Taking a look here: https://triqs.github.io/hubbardI/latest/ce.html and in the script provided in the documentation of the HubbardI solver: https://github.com/TRIQS/hubbardI/blob/3.0.x/doc/ce_input/ce.py the line to import the solver is: 
```
from triqs_hubbardI import Solver
```
However, the rest of the example is also very outdated and needs to be updated. We will work on that. I the mean time you can try the up-to-date script here: https://github.com/TRIQS/hubbardI/blob/3.0.x/doc/ce_input/ce.py and the according example here: https://triqs.github.io/hubbardI/latest/ce.html . Just use the h5 file from the wien2k converter as an input. 

Best,
Alex

**Comment by the-hampel** [comment]
I will close this issue now since it will be worked on in issue #160
