### ISSUE TITLE
Compilation of fortran sources fails on OS X

### ISSUE THREAD

**Issue by aichhorn** [TRIQS/dft_tools#19]
This is related to some changes in the main libs of triqs, but I post it here. For some reason, the fortran compiler is invoked with c++ flags on mac osx:

faepnb44:~/work/Codes/build/W2T $ make
Scanning dependencies of target dmftproj
[  5%] Building Fortran object fortran/dmftproj/CMakeFiles/dmftproj.dir/modules.f.o
gfortran: error: unrecognized command line option '-stdlib=libc++'
make[3]: *** [fortran/dmftproj/CMakeFiles/dmftproj.dir/modules.f.o] Error 1
make[2]: *** [fortran/dmftproj/CMakeFiles/dmftproj.dir/modules.f.o.provides] Error 2
make[1]: *** [fortran/dmftproj/CMakeFiles/dmftproj.dir/all] Error 2
make: *** [all] Error 2

This is new, this problem was not there until a few weeks ago. I use 1.2dev branch and c++14 support, since I want to build the doc also.

**Comment by aichhorn** [comment]
By the way, I got a similar error now also on our linux machines. The option '-std=c++1y' is passed to the gfortran compiler, and it does not like it. Removing this option from fortran/dmftproj/CMakeFiles/dmftproj.dir/flags.cmake removes the problem, and everything compiles.

**Comment by gsclauzero** [comment]
Any news on this?
I experience the same issue when compiling on OS X using Macport g95, the compiler does not like if one feeds it with the C++ flags:

Scanning dependencies of target dmftproj
[  5%] Building Fortran object fortran/dmftproj/CMakeFiles/dmftproj.dir/modules.f.o
f951: error: unrecognized command line option "-Wno-deprecated-writable-strings"
f951: error: unrecognized command line option "-stdlib=libc++"
f951: error: unrecognized command line option "-std=c++1y"

**Comment by parcollet** [comment]
Yes, strange that nobody insisted on this before.
That is an error in the CMakelist, the C++ flags are added always ...

**Comment by parcollet** [comment]
@aichhorn 
I have made the change in the library.
Please
- pull the TRIQS library and update it
- retry
To be fix during our meeting this week.

**Comment by pseth** [comment]
@gsclauzero Can you try this again too?

**Comment by gsclauzero** [comment]
Yes, I did. The changes by Olivier solved the problem, at least in my case. Thanks

**Comment by parcollet** [comment]
@aichhorn  if ok for you, then shall we close this ?
