### ISSUE TITLE
Vasp charge self-consistent scheme needs to be corrected

### ISSUE THREAD

**Issue by the-hampel** [TRIQS/dft_tools#231]
### Description

The current scheme to perform charge self-consistent DFT+DMFT calculations with Vasp is not correct and can lead to spurious results in charge ordered phases. The documentation has to be updated. In the special case of Vasp with multiple DFT scf steps between DMFT iterations it is important to update the GAMMA file with a new delta_N calculated from the new projectors in each DFT scf step. 

No code needs to be correct, only the workflow needs to be adjusted. See also https://github.com/TRIQS/solid_dmft/compare/unstable...debug_update_gamma for the necessary changes.

**Comment by merkelm** [comment]
This is a minor addition but in the [tutorial](https://triqs.github.io/dft_tools/latest/tutorials/svo_vasp/svo_notebook.html), the links to the input files do not work.

**Comment by the-hampel** [comment]
Fixed with PR 239
