### ISSUE TITLE
[1.2-dev] Bad read gf_struct_solver from h5 archive

### ISSUE THREAD

**Issue by PavlovNS** [TRIQS/dft_tools#24]
I test self-consistent calculation for 1.2-dev using one band model.
I do 1 dmft loop and try to start from it. Second loop is not calculated. The problem is related to gf_struct_solver and other.

For illustrate this problem, I print gf_struct_solver, sumk_to_solver, solver_to_sumk, solver_to_sumk_block and other before saving h5 file. It is normal:
[{'up_0': [0], 'down_0': [0]}]
[{('down', 0): ('down_0', 0), ('up', 0): ('up_0', 0)}]
[{('up_0', 0): ('up', 0), ('down_0', 0): ('down', 0)}]
[{'up_0': 'up', 'down_0': 'down'}]
[{'down': array([[ 0.]]), 'up': array([[ 0.]])}]

At second loop after read the h5 archive I print the same:
[{u'up_0': [0], u'down_0': [0]}]
[{u"('up', 0)": ('up_0', 0), u"('down', 0)": ('down_0', 0)}]
[{u"('down_0', 0)": ('down', 0), u"('up_0', 0)": ('up', 0)}]
[{u'up_0': 'up', u'down_0': 'down'}]
[{u'down': array([[ 0.]]), u'up': array([[ 0.]])}]
Symbol u is appeared. I didn't find the reason for it.
My hdf5 version is 1.8.11.
I viewed h5 file by vitables and didn't find the symbol u.

**Comment by pseth** [comment]
I believe the problem is related to calc_blocks that you probably have as input in your SK construction. Now, the block info is not stored and must be calculated on each new run, so you should remove the calc_blocks keyword. See the new lda_dmft_cthyb.py.

**Comment by pseth** [comment]
Nikita, did you manage to resolve this? Should I close the issue?

**Comment by PavlovNS** [comment]
Yes, in last version the problem is solved.
