### ISSUE TITLE
G_latt_iw' is not defined in calc_density_correction

### ISSUE THREAD

**Issue by Soumeniisc** [TRIQS/dft_tools#250]
Hi,

I am using triqs.3.2.x. I was getting the following error. G_latt_iw is not defined in calc_density_correction. However, G_latt is defined. I guess it is a bug in the new version of the code.

dN, d = SK.calc_density_correction(filename = dft_filename+'.qdmft')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/soumen/Sodtware/miniconda3/lib/python3.11/site-packages/triqs_dft_tools/sumk_dft.py", line 2220, in calc_density_correction
    f.write("%.14f\n" % (G_latt_iw.mesh.beta * self.energy_unit))
                         ^^^^^^^^^
NameError: name 'G_latt_iw' is not defined. Did you mean: 'G_latt'?

**Comment by the-hampel** [comment]
Hi @Soumeniisc, 
sorry for the slow response. Thank you for reporting this. I can confirm the bug. I am working on a fix and also extended test coverage. I hope I can push a fix the coming days. I will update you here once this is fixed.

**Comment by the-hampel** [comment]
This should now be fixed on the unstable and 3.2.x branch: https://github.com/TRIQS/dft_tools/commit/41eac4475a1665b8f875f038f6df4dd709e18cb7 . Can you either install this version manually or fix the python file in `sumk_dft.py` manually an check if now everything works? Thanks!
