### ISSUE TITLE
issue running the Vasp Ce Hubbard-I example 

### ISSUE THREAD

**Issue by LZ5278** [TRIQS/dft_tools#259]
Hello, 

I am following the Vasp Ce Hubbard-I example on this page: 
https://triqs.github.io/hubbardI/latest/ce.html
to do the same calculation for CeB6. 

I am using the current version of Triqs and DFTTools and Hubbard-I solver. 
The DFT calculation and DMFT calculation are both done. 

Then I try to use the provided "ce_local_lattice.py" and "plot_dos.py" to post-process to generate dos plots. 
In the provided "ce_local_lattice.py" script, I noticed the method "dos_wannier_basis" no longer exists. So I replaced it with "density_of_states". 
But somehow this gives a mesh error:    
```bash
Warning: could not identify MPI environment!
Starting serial run at: 2024-10-03 02:42:56.722005
WARNING: gf_struct should be a list of pairs [(str,int), ...], not a dict. Converting...
reading iteration10
Traceback (most recent call last):
  File "/home/lzhang/vasp_2_triqs/jj1_ceb6_nonSOC/local_lattice.py", line 71, in <module>
    DOS, DOSproj, DOSproj_orb = SK_tools.density_of_states(broadening=idelta, with_dc=True, with_Sigma=True)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzhang/triqs-3.3.1_dfttools/install/lib/python3.11/site-packages/triqs_dft_tools/sumk_dft_tools.py", line 127, in density_of_states
    assert isinstance(
           ^^^^^^^^^^^
AssertionError: SumkDFT.mesh must be real if with_Sigma is True
```
I don't have a clue how to fix this. Need some help here. 

Attached the script I used, called local_lattice.py. [local_lattice.zip](https://github.com/user-attachments/files/17241235/local_lattice.zip)
The .h5 file that the script runs with is too large, 95MB, can't be shared here.    

Thanks, 
Zhang

**Comment by the-hampel** [comment]
Hi @LZ5278 ,
indeed the tutorial is a little outdated. With triqs 3.1. the tutorial will still work. We have to update the tutorial to the most recent version of triqs. Thank you for bringing this to our attention - we will update you here when we fixed the tutorial. 

Best,
Alex

**Comment by LZ5278** [comment]
Hi Alex, 

Appreciate the quick response! 

Do you know if the version 3.1.x of Triqs/DFTTools works with VASP >=6.3? particularly when SOC is included in VASP calculation? 

I am asking this because I have to include SOC in DFT, for my heavy element materials. 
I actually use VASP to generate PAW spinor projectors.  
If 3.1.x works with VASP SOC calculations, then I am happily suiting myself back to 3.1.x for the moment.    
If only version 3.3.x works with VASP SOC calculations, then I have to stick with it, and my problem becomes how to correctly execute SK_tools.density_of_states to generate some dos plots, using 3.3.x.  

If it's the later case, I can initiate a discussion and provide all input (small size) files, to show you the error message when I tried to execute SK_tools.density_of_states to draw dos plots from my .h5 file. I think that would make it easier to pinpoint the issue. 

Best, 
Zhang

**Comment by the-hampel** [comment]
In principle ver 3.1.x of triqs/dft_tools works with vasp from 5.4 on. However, the conversion of spinor projectors was only merged for ver 3.3.x of dfttools. So you have to stick with it. 
Anyway, I think your problem can be solved rather quickly. By default the Sumk object is intialized on the Matsubara axis not the real frequency axis. In your script you try to use the real freq Self energy from the solver. So to make this work you have to initialize sumk with a consistent mesh, i.e. 

```
mesh_w = MeshReFreq(n_w=3001, window=[-15,15])
SK_tools = SumkDFTTools(hdf_file = filename+'.h5', use_dft_blocks = False, mesh=mesh_w)
```
and then when setting up the solver (https://triqs.github.io/hubbardI/latest/documentation.html#python-reference-manual):
```
S = Solver(beta=beta, gf_struct=gf_struct, n_w=3001, w_min=-15,w_max=15)
```
Can you try this please? Also make sure to activate the option to calculate the real frequency objects in the solver.solve command `calc_gw=True`.

Best,
Alex

**Comment by LZ5278** [comment]
Hi Alex, 

Sorry for my late response. I just got time to try your suggestion. But please allow me to describe how I got the result before my trying to plot dos. I just feel the complete picture would help to sort out things. 

The result from DFT (vasp.h5) is exactly the same as I described in https://github.com/TRIQS/solid_dmft/discussions/87

At the beginning I tried to directly run that ce.py from the tutorial page with my vasp.h5. 
It of course didn't run out of the box. I made my tries to either fix the problem or go around the problem. 

For example, if nothing is changed, line 45 of the ce.py will complain: 
```bash
Starting run with 1 MPI rank(s) at : 2024-10-10 23:41:38.002913
Traceback (most recent call last):
  File "/home/lzhang/zz_33x_jobs/jj2_ceb6_SOC_for_forum/using_nonSOCh5/ce.py", line 45, in <module>
    SK.put_Sigma([Sigma])     
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzhang/triqs-3.3.1/install/lib/python3.11/site-packages/triqs_dft_tools/sumk_dft.py", line 668, in put_Sigma
    raise ValueError("put_Sigma: Sigma_imp must have the same mesh as SumKDFT.mesh.")
ValueError: put_Sigma: Sigma_imp must have the same mesh as SumKDFT.mesh.
```
If I commented out the lines 45-54, then line 111 will complain: 
```bash
Starting run with 1 MPI rank(s) at : 2024-10-11 01:47:08.438470
Sumk to Solver: [{('up', 0): ('up_0', 0), ('up', 1): ('up_0', 1), ('up', 2): ('up_0', 2), ('up', 3): ('up_0', 3), ('up', 4): ('up_0', 4), ('up', 5): ('up_0', 5), ('up', 6): ('up_0', 6), ('down', 0): ('down_0', 0), ('down', 1): ('down_0', 1), ('down', 2): ('down_0', 2), ('down', 3): ('down_0', 3), ('down', 4): ('down_0', 4), ('down', 5): ('down_0', 5), ('down', 6): ('down_0', 6)}]
GF struct sumk: [[('up', 7), ('down', 7)]]
GF struct solver: [{'up_0': 7, 'down_0': 7}]
WARNING: gf_struct should be a list of pairs [(str,int), ...], not a dict. Converting...
/home/lzhang/triqs-3.3.1/install/lib/python3.11/site-packages/triqs/operators/util/hamiltonians.py:33: UserWarning: h_int_slater takes as a second argument the number of orbitals, not a list of orbital names
  warnings.warn("{} takes as a second argument the number of orbitals, not a list of orbital names".format(fname))
Greens function structure is: {'up_0': 7, 'down_0': 7}
Traceback (most recent call last):
  File "/home/lzhang/zz_33x_jobs/jj2_ceb6_SOC_for_forum/using_nonSOCh5/ce_mod.py", line 111, in <module>
    SK.put_Sigma(Sigma_imp = [S.Sigma_iw])              
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzhang/triqs-3.3.1/install/lib/python3.11/site-packages/triqs_dft_tools/sumk_dft.py", line 668, in put_Sigma
    raise ValueError("put_Sigma: Sigma_imp must have the same mesh as SumKDFT.mesh.")
ValueError: put_Sigma: Sigma_imp must have the same mesh as SumKDFT.mesh.
```
And, line 141 is exactly same as line 111. 

However, very interestingly, I found **`beta = 40`** (instead of 100) would solve most of the problems! 
With beta = 40, it will only complain about line 47: 
```bash
Starting run with 1 MPI rank(s) at : 2024-10-11 01:51:00.301394
Traceback (most recent call last):
  File "/home/lzhang/zz_33x_jobs/jj2_ceb6_SOC_for_forum/using_nonSOCh5/ce_mod.py", line 47, in <module>
    SK.analyse_block_structure_from_gf(G, threshold = 1e-2)      
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lzhang/triqs-3.3.1/install/lib/python3.11/site-packages/triqs_dft_tools/sumk_dft.py", line 1087, in analyse_block_structure_from_gf
    assert sp in gf[self.inequiv_to_corr[ish]].indices, f"The Green's function does not contain the block {sp}. Is the input G given in sumk block structure?"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: The Green's function does not contain the block up. Is the input G given in sumk block structure?
```


I just commented out line 47, then it run with beta=40 and finished the job without any problem. 
The script I used is exactly this one: [ce_mod.py](https://github.com/user-attachments/files/17338986/ce_mod.zip)
If you grep "##L.Zhang" you can see all the lines where I modified. 
Only a few lines are modified. It's not much different from the original ce.py.  

At this point I got the test run result in this [vasp.h5](https://github.com/user-attachments/files/17338919/vasp.zip), and I started to plot dos from here. 
(keep in mind that the result is for `beta=40` only and changing it will cause problem) 

For plotting the dos, I adopted what you suggested, then tried to follow the [ce_local_lattice.py](https://triqs.github.io/hubbardI/latest/_downloads/152a81853476ca21993ef0f6444a1035/ce_local_lattice.py) line by line. 
It still has some problem in put_Sigma. 
```bash
>>> from itertools import *
>>> import triqs.utility.mpi as mpi
>>> from h5 import *
>>> from triqs.gf import *
>>> from triqs_dft_tools.sumk_dft import *
>>> from triqs_dft_tools.sumk_dft_tools import *
>>> from triqs_hubbardI import *
>>>
>>> mesh_w = MeshReFreq(n_w=3001, window=[-15,15])
>>> filename = 'vasp'
>>> SK_tools = SumkDFTTools(hdf_file = filename+'.h5', use_dft_blocks = False, mesh=mesh_w)
>>> beta = 40
>>> Sigma = SK_tools.block_structure.create_gf(beta=beta)
>>>
>>> SK_tools.put_Sigma([Sigma])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lzhang/triqs-3.3.1/install/lib/python3.11/site-packages/triqs_dft_tools/sumk_dft.py", line 668, in put_Sigma
    raise ValueError("put_Sigma: Sigma_imp must have the same mesh as SumKDFT.mesh.")
ValueError: put_Sigma: Sigma_imp must have the same mesh as SumKDFT.mesh.
```

Back to the dmft script, beside the beta value problem, I have a question tho. 
The old tutorial ce.py did not manually set `mesh_w = MeshReFreq(n_w=3001, window=[-15,15]) ` when using Hubbard-I. 
Is this still OK for 3.3.x? or should I manually set `mesh_w` in the ce_mod.py too?  

Best, 
L. Zhang

**Comment by the-hampel** [comment]
Hi @LZ5278 ,

it is important to understand a bit some changes to Sumk of the recent releases (see for example https://triqs.github.io/dft_tools/unstable/ChangeLog.html#version-3-2-0) . THe SumK object now requires a mesh on construction that it will use coherently. By default it will be a `MeshImFreq` object with beta=40 and n_iw=1025 (for compatibility with older versions). This is why you saw the errors.  Whenever you try to do something like `put_sigma` the Sigma must have the same triqs mesh as the sumk. This is a failsafe check.

I recommend for HubbardI to run the DMFT cycle on the Matsubara axis. So in the attached script I now added such mesh. Then for the analysis of the block structure you have to once generate a local Gf without transforming to solver blocks. See comment in the script. 

I could not test these changes in the script but the script should run like this more or less. I hope that clarifies a bit the workflow. 

[ce_mod_hampel.zip](https://github.com/user-attachments/files/17346892/ce_mod_hampel.zip)

**Comment by harrisonlabollita** [comment]
Hi @LZ5278 and @the-hampel 

I've made a few changes to the relevant Ce example scripts, which can be found at this PR: https://github.com/TRIQS/hubbardI/pull/17. 

Everything should now work with the latest version of TRIQS (3.3.x). Please let us know if you're still encountering an issue.

Best,
Harry

**Comment by LZ5278** [comment]
Hi @harrisonlabollita and @the-hampel, 

Thanks to you both. What Alex pointed out last week is exactly what I missed. 
I modified my draft script over the weekend according to that and it worked. 

I have run the example scripts Harry updated, both ce.py and ce_local_lattice.py, and both run good. 
(just in ce.py the line `mesh = MeshImFreq(beta = beta, n_iw = 1025, S = 'Fermion' ` needs a right-parentheses at end) 

I think this makes the Ce Vasp example up to date. Thanks again for walking me through! 

Best, 
L. Zhang

**Comment by the-hampel** [comment]
Perfect. Thanks @harrisonlabollita and also @LZ5278 . I fixed the missing parenthesis now. I will close the issue. Please feel free to reopen it or open a new one if there is another problem.
