### ISSUE TITLE
band_window not found in hdf5

### ISSUE THREAD

**Issue by Vahid999** [TRIQS/dft_tools#263]
I am applying DMFT to bulk Ca2N through QE. There are three atoms/cell with 25 electrons/cell. The Ca2N s-states form the only band within 0.5eV of the Fermi level and this band is half filled.

A total of 15 Wannier functions reproduce the band structure. The Wannier projections are:

Ca:s
Ca:dxy,dyz,dxz,dz2,dx2-y2
N:px,py,pz

And the atoms are:

Ca            0.2656141405        0.2656141405        0.2656141405
Ca           -0.2656141405       -0.2656141405       -0.2656141405
N            -0.0000000000        0.0000000000        0.0000000000

The Ca s-states are treated as correlated. My .inp file to triqs/3.1.1 is 

0  12 12 12               
25.0                  
 2                    
 0  0  0  1  0  0     
 1  0  0  1  0  0
 7.2309

When I run a DMFT+self-consistent calculation with QE, I get the following error:

`Error in routine dmft_update (1):
hdf5 dataset Ca2N.sa.h5/dft_misc_input/band_window not found`

How can one include band_window in the hdf5 file?

Thanks,
Vahid

**Comment by phibeck** [comment]
Hi @Vahid999, the `band_window` is written into the hdf5 archive when using the Wannier90 Converter with the `bloch_basis = True` flag.
https://github.com/TRIQS/dft_tools/blob/c19cbe797165f8ead25137acde536b036c288d60/python/triqs_dft_tools/converters/wannier90.py#L327

Can you tell us more how you run your calculations, in particular how you call the Wannier90 Converter?

**Comment by Vahid999** [comment]
Hi Sophie,

After completing the wannierization and obtaining the $PREFIX_hr.dat, I run the following script:

from triqs_dft_tools.converters import Wannier90Converter
Converter = Wannier90Converter(seedname='Ca2N.sa', bloch_basis=False, rot_mat_type='hloc_diag', add_lambda=None)
Converter.convert_dft_input()

I will change bloch_basis to True and rerun.

Thanks,
Vahid

On Nov 21, 2024, at 8:30 AM, Sophie Beck ***@***.***> wrote:

CAUTION: The Sender of this email is not from within Dalhousie.


Hi @Vahid999<https://github.com/Vahid999>, the band_window is written into the hdf5 archive when using the Wannier90 Converter with the bloch_basis = True flag.
https://github.com/TRIQS/dft_tools/blob/c19cbe797165f8ead25137acde536b036c288d60/python/triqs_dft_tools/converters/wannier90.py#L327

Can you tell us more how you run your calculations, in particular how you call the Wannier90 Converter?

**Comment by phibeck** [comment]
Hi @Vahid999, sounds good. Let us know if you run into other issues with the charge self-consistency. 

You may find these resources helpful:

- https://triqs.github.io/solid_dmft/tutorials/Ce2O3_csc_w90/tutorial.html
- https://iopscience.iop.org/article/10.1088/1361-648X/ac5d1c/meta

**Comment by Vahid999** [comment]
Hi Sophie,

I have followed the QE example 14 in PW/examples and used the following converter for wannier90:

from triqs_dft_tools.converters import Wannier90Converter
Converter = Wannier90Converter(seedname='Ca2N.sa', bloch_basis=True, rot_mat_type='hloc_diag', add_lambda=None)
Converter.convert_dft_input()

When I run the self-consistent calculation, I get the following error:

     hdf5 group Ca2N.sa.h5/dft_update not found

What should I add to the converter in order to include dft_update in the h5 file? Or is this a QE issue in which case I should ask the QE forum?

Thanks,
Vahid

On Nov 21, 2024, at 8:44 AM, Sophie Beck ***@***.***> wrote:

CAUTION: The Sender of this email is not from within Dalhousie.


Hi @Vahid999<https://github.com/Vahid999>, sounds good. Let us know if you run into other issues with the charge self-consistency.

You may find these resources helpful:

  *   https://triqs.github.io/solid_dmft/tutorials/Ce2O3_csc_w90/tutorial.html
  *   https://iopscience.iop.org/article/10.1088/1361-648X/ac5d1c/meta

**Comment by phibeck** [comment]
Hi @Vahid999,

it might be a bug reading the hdf5 correctly due to the additional . in the filename. Can you open the h5 archive in python or with bash and check whether `dft_update` is there or not? See e.g. here for instructions: https://triqs.github.io/triqs/3.3.x/userguide/python/tutorials/Basics/02-Archiving_your_data.html

**Comment by Vahid999** [comment]
Hi Sophie,

The command

!h5ls Ca2N.sa.h5

returns the following:

-bash: !h5ls: event not found

Maybe I should change the filenames from Ca2N.sa.h5 to Ca2N.h5 as you hinted and see what happens.

Thanks,
Vahid

On Nov 27, 2024, at 8:51 AM, Sophie Beck ***@***.***> wrote:

CAUTION: The Sender of this email is not from within Dalhousie.


Hi @Vahid999<https://github.com/Vahid999>,

it might be a bug reading the hdf5 correctly due to the additional . in the filename. Can you open the h5 archive in python or with bash and check whether dft_update is there or not? See e.g. here for instructions: https://triqs.github.io/triqs/3.3.x/userguide/python/tutorials/Basics/02-Archiving_your_data.html

**Comment by phibeck** [comment]
Hi @Vahid999, any updates with the changed filename?

The return message you got just tells you that the command `h5ls` is not available on your system. Please try to follow the instructions in the link I sent to read from an archive using python to confirm whether the `dft_update` group was written successfully to the HDF5 archive or not.

Edit: Thanks @aichhorn for the correction, I didn't notice the exclamation mark. Indeed, it should be either `h5ls` in bash or `!h5ls` in a jupyter notebook.

**Comment by aichhorn** [comment]
Hi,
I guess you entered the command in a bash shell (not in a jupyter notebook). Then you have to remove the exclamation mark in the beginning, it must not start with !h5ls but only with h5ls. Can you try that?

**Comment by Vahid999** [comment]
Hi Sophie and Markus,

I redid the wannier90 using Ca2N.win instead of Ca2N.sa.win. The python approach of opening the file gave me indentation errors. Removing the exclamation did work on bash. For the content of the h5 file, I used "h5dump -n Ca2N.h5” and I get the following:

HDF5 "Ca2N.h5" {
FILE_CONTENTS {
 group      /
 group      /dft_input
 dataset    /dft_input/SO
 dataset    /dft_input/SP
 group      /dft_input/T
 dataset    /dft_input/T/0
 dataset    /dft_input/bz_weights
 dataset    /dft_input/charge_below
 group      /dft_input/corr_shells
 group      /dft_input/corr_shells/0
 dataset    /dft_input/corr_shells/0/SO
 dataset    /dft_input/corr_shells/0/atom
 dataset    /dft_input/corr_shells/0/dim
 dataset    /dft_input/corr_shells/0/irep
 dataset    /dft_input/corr_shells/0/l
 dataset    /dft_input/corr_shells/0/sort
 group      /dft_input/corr_shells/1
 dataset    /dft_input/corr_shells/1/SO
 dataset    /dft_input/corr_shells/1/atom
 dataset    /dft_input/corr_shells/1/dim
 dataset    /dft_input/corr_shells/1/irep
 dataset    /dft_input/corr_shells/1/l
 dataset    /dft_input/corr_shells/1/sort
 group      /dft_input/corr_to_inequiv
 dataset    /dft_input/corr_to_inequiv/0
 dataset    /dft_input/corr_to_inequiv/1
 dataset    /dft_input/density_required
 group      /dft_input/dim_reps
 dataset    /dft_input/dim_reps/0
 dataset    /dft_input/energy_unit
 dataset    /dft_input/hopping
 group      /dft_input/inequiv_to_corr
 dataset    /dft_input/inequiv_to_corr/0
 dataset    /dft_input/k_dep_projection
 dataset    /dft_input/kpt_weights
 dataset    /dft_input/kpts
 dataset    /dft_input/n_corr_shells
 dataset    /dft_input/n_inequiv_shells
 dataset    /dft_input/n_k
 dataset    /dft_input/n_orbitals
 group      /dft_input/n_reps
 dataset    /dft_input/n_reps/0
 dataset    /dft_input/n_shells
 dataset    /dft_input/proj_mat
 group      /dft_input/rot_mat
 dataset    /dft_input/rot_mat/0
 dataset    /dft_input/rot_mat/1
 group      /dft_input/rot_mat_time_inv
 dataset    /dft_input/rot_mat_time_inv/0
 dataset    /dft_input/rot_mat_time_inv/1
 group      /dft_input/shells
 group      /dft_input/shells/0
 dataset    /dft_input/shells/0/atom
 dataset    /dft_input/shells/0/dim
 dataset    /dft_input/shells/0/l
 dataset    /dft_input/shells/0/sort
 group      /dft_input/shells/1
 dataset    /dft_input/shells/1/atom
 dataset    /dft_input/shells/1/dim
 dataset    /dft_input/shells/1/l
 dataset    /dft_input/shells/1/sort
 dataset    /dft_input/symm_op
 dataset    /dft_input/use_rotations
 group      /dft_misc_input
 dataset    /dft_misc_input/band_window
 dataset    /dft_misc_input/dft_fermi_energy
 dataset    /dft_misc_input/dft_fermi_weights
 dataset    /dft_misc_input/kpts_cart
 }
}

The dft_update seems to be missing.

Regards,
Vahid

On Nov 28, 2024, at 6:48 AM, Markus Aichhorn ***@***.***> wrote:

CAUTION: The Sender of this email is not from within Dalhousie.


Hi,
I guess you entered the command in a bash shell (not in a jupyter notebook). Then you have to remove the exclamation mark in the beginning, it must not start with !h5ls but only with h5ls. Can you try that?

**Comment by phibeck** [comment]
Thank you for this, that's very helpful. It also tells us that there are no `DMFT_results` group in the h5 archive, so that explains why there is no `dft_update`, since this is generated at the end of a successful DMFT run. Can you tell us more about how you run the DMFT calculations?

**Comment by Vahid999** [comment]
Attached please see the input files I used based on example14 in the PW/examples/. Here are the steps:

1. run scf.in
2. run nscf.in
3. do the Wannier90 calculations with Ca2N.win and Ca2N.pw2wan.in
4. run triqs with triqs.in
5. run scf_dmft.in

In step 5, QE stops asking for dft_update.

Please let me know if you require other details.

Thanks,
Vahid



On Nov 28, 2024, at 7:47 AM, Sophie Beck ***@***.***> wrote:

CAUTION: The Sender of this email is not from within Dalhousie.


Thank you for this, that's very helpful. It also tells us that there are no DMFT_results group in the h5 archive, so that explains why there is no dft_update, since this is generated at the end of a successful DMFT run. Can you tell us more about how you run the DMFT calculations?

**Comment by the-hampel** [comment]
Hi @Vahid999,
unfortunately email attachments are not relied to github. Please attach them online. Can you explain to me what 
```
4. run triqs with triqs.in
```
is? 
As far as I know example 14 included in Quantum Espresso is not actually performing any DMFT calculations. It just emulates a DMFT calculation. 

Best,
Alex

**Comment by Vahid999** [comment]
Hi Alex,

I uploaded the files to https://drive.google.com/file/d/1a6bMxnAim4X3y2_FynmncEFhOykyLGh7/view?usp=sharing.

Step 4 involves loading the triqs module on ComputeCanada and running “python triqs.in” where triqs.in is the following:

from triqs_dft_tools.converters import Wannier90Converter
Converter = Wannier90Converter(seedname='Ca2N', bloch_basis=True, rot_mat_type='hloc_diag', add_lambda=None)
Converter.convert_dft_input()

Best,
Vahid

On Nov 28, 2024, at 8:46 AM, Alexander Hampel ***@***.***> wrote:

CAUTION: The Sender of this email is not from within Dalhousie.


Hi @Vahid999<https://github.com/Vahid999>,
unfortunately email attachments are not relied to github. Please attach them online. Can you explain to me what

4. run triqs with triqs.in


is?
As far as I know example 14 included in Quantum Espresso is not actually performing any DMFT calculations. It just emulates a DMFT calculation.

Best,
Alex

**Comment by phibeck** [comment]
Dear @Vahid999,

step 4 just runs the Wannier90Converter. In the list you sent in your previous message you are missing the actual DMFT calculation (that should be step 5) before returning to step 6 run scf_dmft.in.

I recommend you take a look at the two TRIQS projects, that outline in great depth how to setup a DMFT calculation (depending on what you want to do):
- DFTTools: https://triqs.github.io/dft_tools/latest/
- solid_dmft: https://triqs.github.io/solid_dmft/

Let us know if you have any questions.

**Comment by Vahid999** [comment]
Dear Sophie,

Thank you for the links and for the clarification. My goal is to compare the QE band structure of Ca2N (no magnetism and no SOC) with and without DMFT.

My guess is that the Sr2MgOsO6_noSOC example is closest to my case but I might be wrong. In addition, in that example, the basis is rotated but it seems that the SrVO3 example does not follow the same rotation step. Then we have the U and J parameters. Do the choice of these parameters affect the outcome, i.e., band energies? And is there any documentation that explains why for example p["fit_min_n"] = 30 and not 100?

Thanks,
Vahid

On Dec 3, 2024, at 5:20 AM, Sophie Beck ***@***.***> wrote:

CAUTION: The Sender of this email is not from within Dalhousie.


Dear @Vahid999<https://github.com/Vahid999>,

step 4 just runs the Wannier90Converter. In the list you sent in your previous message you are missing the actual DMFT calculation (that should be step 5) before returning to step 6 run scf_dmft.in.

I recommend you take a look at the two TRIQS projects, that outline in great depth how to setup a DMFT calculation (depending on what you want to do):

  *   DFTTools: https://triqs.github.io/dft_tools/latest/
  *   solid_dmft: https://triqs.github.io/solid_dmft/

Let us know if you have any questions.

**Comment by Vahid999** [comment]
Dear Sophie,

It seems that the best way to proceed is not the dft_tools but solid_dmft. I think the tutorial on Ce2O3_csc_w90 is what I was looking for.

Best,
Vahid

On Dec 4, 2024, at 8:28 AM, Vahid Askarpour ***@***.***> wrote:

Dear Sophie,

Thank you for the links and for the clarification. My goal is to compare the QE band structure of Ca2N (no magnetism and no SOC) with and without DMFT.

My guess is that the Sr2MgOsO6_noSOC example is closest to my case but I might be wrong. In addition, in that example, the basis is rotated but it seems that the SrVO3 example does not follow the same rotation step. Then we have the U and J parameters. Do the choice of these parameters affect the outcome, i.e., band energies? And is there any documentation that explains why for example p["fit_min_n"] = 30 and not 100?

Thanks,
Vahid

On Dec 3, 2024, at 5:20 AM, Sophie Beck ***@***.***> wrote:

CAUTION: The Sender of this email is not from within Dalhousie.


Dear @Vahid999<https://github.com/Vahid999>,

step 4 just runs the Wannier90Converter. In the list you sent in your previous message you are missing the actual DMFT calculation (that should be step 5) before returning to step 6 run scf_dmft.in.

I recommend you take a look at the two TRIQS projects, that outline in great depth how to setup a DMFT calculation (depending on what you want to do):

  *   DFTTools: https://triqs.github.io/dft_tools/latest/
  *   solid_dmft: https://triqs.github.io/solid_dmft/

Let us know if you have any questions.

**Comment by phibeck** [comment]
Hi @Vahid999,

I'm glad you found a tutorial that is helpful for what you intend to do. I will close this issue now, but feel free to open a new one if there are other questions (as you already did).
