### ISSUE TITLE
potential typo in spherical_to_cubic(l, convention='') function  from U_matrix.py

### ISSUE THREAD

**Issue by dymkowsk** [TRIQS/dft_tools#28]
Dear All,
By comparing rotational matrix T for l=2 in U_matrix.py  and 
tutorial materials from workshop which I have attended some time ago I observed some discrepancy. 

Here is a link to tutorial:
http://www.cond-mat.de/events/correl11/manuscripts/correl11.pdf

Please look at page 206, there is T matrix I have  compared (it is called M there).  

I am not sure if by mistake xy is swapped with x^2-y^2 in rotational matrix in  U_matrix.py, or maybe in that tutorial there is a typo ?

**Comment by pseth** [comment]
I think this just depends on sign convention, but doesn't affect the result.
Chris agrees.
