### ISSUE TITLE
how to get the solver_multiband?

### ISSUE THREAD

**Issue by xiaoyukaka** [TRIQS/dft_tools#29]
Hi,
I have installed triqs, dft_tools, cthyb and hubbardI. When i test multi-band solver by 'from pytriqs.applications.dft.solver_multiband import *', there is ImportError: No module named solver_multiband. How to get the solver_multiband? -.-

**Comment by mferrero** [comment]
Hi! We are in the process of upgrading the dft tools package. Some of the documentation still has to be updated. There is no solver_multiband anymore. The new documentation will be available soon.

**Comment by PavlovNS** [comment]
You may use "lda_dmft_cthyb.py" for LDA+DMFT calculations.
