### ISSUE TITLE
[version 1.0] Orbitals sequence affects to result of LDA+DMFT calculations

### ISSUE THREAD

**Issue by PavlovNS** [TRIQS/dft_tools#30]
I found some problem using version 1.0 in LDA+DMFT calculations.
I do 2 calculations with equivalent start parameters except orbital sequence in Hamiltonian and in U matrix (density-density). In first case I use Wien2k orbital sequence in Hamiltonian and in U matrix (3z2-r2, x2-y2, xy, yz, xz). In second case LMTO orbital sequence in Hamiltonian and in U matrix (xy, yz, 3z2-r2, xz, x2-y2). These two results are different. After first iteration degenerate orbitals (yz, xz) become different in case LMTO orbital sequence. In both calculations "use_segment_picture" is true.
Why orbitals sequence affects to result?

**Comment by aichhorn** [comment]
The resulst must not differ. If the degeneracies are correct in the fiurst case, then I assume that the U matrix is not correct in the second case. Are you sure that you did not use the Wien2k convention in connection with LMTO? If you use only density-density interactions, you can easily check if the matrices are correct by looking at the U and U^' matrices directly. t2g's have to remain t2g's...

**Comment by PavlovNS** [comment]
Thank you! I found my mistake. I have changed U and U' matrices only on master node. Now, the results are equal. Also I compare results of triqs 1.0 and triqs 1.2. It is same.
