### ISSUE TITLE
DFT+DMFT for Ce-gamma

### ISSUE THREAD

**Issue by Soumeniisc** [TRIQS/dft_tools#31]
Hi!
I got DFT+DMFT converged energy value for Ce diffent from what was mentioned in we tutorial.
I stated DFT calculation with the structure file (no of symmetry=0)mentioned in the web tutorial. But at the end it calculated with symmetry.  After LDA+DMFT energy comming to be 

:ENE  : ********** TOTAL ENERGY IN Ry =       -17730.87948820
:ENE  : ********** TOTAL ENERGY IN Ry =       -17730.87663309
:ENE  : ********** TOTAL ENERGY IN Ry =       -17730.87523305
:ENE  : ********** TOTAL ENERGY IN Ry =       -17730.87243746
:ENE  : ********** TOTAL ENERGY IN Ry =       -17730.87727413
:ENE  : ********** TOTAL ENERGY IN Ry =       -17730.87834269
:ENE  : ********** TOTAL ENERGY IN Ry =       -17730.87895017
:ENE  : ********** TOTAL ENERGY IN Ry =       -17730.87741727
:ENE  : ********** TOTAL ENERGY IN Ry =       -17730.88594246
:ENE  : ********** TOTAL ENERGY IN Ry =       -17730.88391215
============================================================
instead of  ~17717.77

Any help will be appreciated. 
Thanks

**Comment by leopo** [comment]
check your exchange-correlation, in the tutorial example it was set to LDA, vxc=5 in init_lapw -b , while if you generate the input with the default value, i. e. without specifying vxc, it employs GGA, vxc=13

**Comment by Soumeniisc** [comment]
Thanks leopo, It worked.
