### ISSUE TITLE
reading struct in convert_misc_input fails

### ISSUE THREAD

**Issue by leopo** [TRIQS/dft_tools#32]
Hi,

I noticed that  reading of the struct files in convert_misc_input fails in the case of hcp structures. The reason is that in this case there is no space between the unit cell angles 90 and 120 in case.struct:

Title
H   LATTICE,NONEQUIV.ATOMS:  1
MODE OF CALC=RELA unit=ang
  4.095012  4.095012  6.552019 90.000000 90.000000120.000000
....

and str.split() apparently does not work correctly in this case.

**Comment by mzingl** [comment]
Should be fixed. Please check if it works.
