### ISSUE TITLE
Potentially dangerous line in the example 'lda_dmft_cthyb.py'

### ISSUE THREAD

**Issue by opeil** [TRIQS/dft_tools#33]
The example provided in dft_tools/src/lda_dmft_cthyb.py contains the following line
  S.G_iw << SK.extract_G_loc()

  This line looks rather dangerous for a simple reason: operator "<<" copies the GF block by block but there is no guarantee that the blocks are ordered consistently. Indeed, the GF in the solver is constructed from a dictionary SK.gf_struct_solver and dictionaries are not ordered data structures in Python, which implies that the blocks of S.GF might be ordered in a completely arbitrary fashion, different from that in SumK.
   I beleive this copy operation must be performed with the help of maps 'solver_to_sumk' or 'sumk_to_solver'.

**Comment by aichhorn** [comment]
No, this line is safe. The operator "<<" does not copy item by item randomly, but it copies the blocks name by name. So if you try to use two GF's with different names of the blocks, this functionality will not work. The point is that it is not an iterator over a dictionary, which indeed would produce random order. At least that is my understanding of the __lshift__ function in block_gf.py

**Comment by opeil** [comment]
Well, I used to have the same impression about the way 'lshift' works until
a similar line in my script resulted in a messed up solver GF and the
problem was fixed when I performed copying in an explicit loop over block
indices. I will check whether a problem could be reproduced in a minimal
script.

**Comment by aichhorn** [comment]
Did you have maybe the same problem as reported in issue #21 ? There was a problem with the orbital sequence, but this should have been fixed a couple of weeks before christmas.

**Comment by opeil** [comment]
Yes, it looks similar to that issue. If one looks at the order of indices they are different in the solver and in SumK. In my case they look like this:

  solver GF indices: ['down_0', 'down_1', 'up_0', 'up_1']
  sumk GF indices (1): ['up_0', 'up_1', 'down_1', 'down_0']

But this should not be a problem if the copy is performed by block name.
I checked that indeed, when I copy like this "gf1 << gf2" the order of indices and the final values are correct.

However if one does something like this: "gf1 << gf1 + gf2 * const", i.e. there is an expression on the RHS the problem with messed up indices remains.
Here is a very simple example (I make a copy-paste because I am not sure one can attach a source file). The two last outputs (for gf2) must be the same.

from pytriqs.gf.local import *
from pytriqs.gf.local.descriptors import *

gf1_struct = ['up-0', 'do-1', 'up-1']
gf2_struct = ['do-1', 'up-1', 'up-0']

gf1 = BlockGf(name_block_generator=[(s, GfImFreq(beta=40.0, indices=[0])) for s in gf1_struct])
gf2 = BlockGf(name_block_generator=[(s, GfImFreq(beta=40.0, indices=[0])) for s in gf2_struct])

gf1['up-0'] << A_Omega_Plus_B(1.0, -0.1, Invert=True)
gf1['do-1'] << A_Omega_Plus_B(1.0, 0.1, Invert=True)
gf1['up-1'] << A_Omega_Plus_B(1.0, 0.0, Invert=True)

print " gf1:"
print gf1.density()

print "  Simple copy:"
gf2 << gf1
print " gf2:"
print gf2.density()

print "  Expression:"
gf2.zero()
gf2 << gf2 + gf1 * 1.0
print " gf2:"
print gf2.density()

**Comment by opeil** [comment]
Forgot to paste the output in the previous message.
This is the output of the above example using my version of triqs1.2:

 gf1:
{'do-1': array([[ 0.98201379]]), 'up-0': array([[ 0.01798621]]), 'up-1': array([[ 0.5]])}
  Simple copy:
 gf2:
{'do-1': array([[ 0.98201379]]), 'up-0': array([[ 0.01798621]]), 'up-1': array([[ 0.5]])}
  Expression:
 gf2:
{'do-1': array([[ 0.01798621]]), 'up-0': array([[ 0.5]]), 'up-1': array([[ 0.98201379]])}

**Comment by aichhorn** [comment]
That is interesting. In fact, this is a problem that is not even related to dft_tools, but a problem in the library itself. Oleg, can you put an issue to the triqs issue list? I think this has to be checked and fixed!

**Comment by opeil** [comment]
You are right, Markus. I have created a new issue in TRIQS and this one can be closed.
