### ISSUE TITLE
S.G0.delta() problem for SrVO3

### ISSUE THREAD

**Issue by Soumeniisc** [TRIQS/dft_tools#34]
Hi,
I am using triqs1.0. I got the following problem during LDA+DMFT calcualtion for SrVO3
   File "SRVO-DMFT.py", line 83, in <module>
    ar['DeltaF'] = S.G0.delta()
  File "/home/soumen/INSTALLPACKAGES/triqs/lib/python2.7/dist-packages/pytriqs/gf/local/block_gf.py", line 359, in delta
    self.__check_attr("delta")
  File "/home/soumen/INSTALLPACKAGES/triqs/lib/python2.7/dist-packages/pytriqs/gf/local/block_gf.py", line 350, in __check_attr
    raise RuntimeError, "The blocks of this Green Function do not possess the %s method"%ATTR
RuntimeError: The blocks of this Green Function do not possess the delta method

=====================
link for SRVO-DMFT.py is https://gist.github.com/Soumeniisc/0eeb9a4a103b0947d9e0
Is the current version of DFT_tool_1.2.0 beta version??
Thanks
Soumen

**Comment by parcollet** [comment]
I think this function has simply been moved in 1.2, maybe the script has not been updated ?@pseth

**Comment by pseth** [comment]
You need to do the following: 
delta(S.G0_iw)

Until the doc is updated, I recommend that you look at the lda_dmft_cthyb.py script provided in the sources should anything fail..

**Comment by Soumeniisc** [comment]
Now I am getting following error:

ar['DeltaF'] = delta(S.G0_iw)
NameError: name 'delta' is not defined

NOTE::::::
1> I am using triqs1.0
2> lda_dmft_cthyb.py is present current version of dft_tools 1.2, which is not compatible with library1.0
3>Current version of triqs is in alpa1 phase. 
4> Should i install current version of triqs and dft_tool???
Thanks

**Comment by pseth** [comment]
If you use triqs1.0, then you should use the corresponding versions of other applications, i.e. cthyb_matrix and dft_tools. In this case, you shouldn't be having the delta issue.

I would recommend that you switch to the latest versions, as the older codes will not be maintained.

**Comment by Soumeniisc** [comment]
1> I have installed the latest version of triqs. there test 95 is failed.
2> still i have installed it. I used the lda_dmft_cthyb.py. I got following error
File "SRVO-DMFT.py", line 57, in <module>
    Umat, Upmat = U_matrix_kanamori(n_orb=n_orb, U_int=U, J_hund=J)
NameError: name 'U_matrix_kanamori' is not defined

**Comment by pseth** [comment]
Sorry, the U_matrix module wasn't loaded. I have pushed a fix.

**Comment by Soumeniisc** [comment]
Hi Pseth,
Is this bug fixed?
Thanks,

**Comment by pseth** [comment]
Yes.
