### ISSUE TITLE
constr_Sigma_real_axis() is missing from SumkDFTTools

### ISSUE THREAD

**Issue by krivenko** [TRIQS/dft_tools#35]
Dear dft_tools developers,
Could you explain me, what happened to the real-frequency self energy routines mentioned in `doc/analysis.rst`?
Where is `constr_Sigma_real_axis()`?
How can I use `python/build_sigma_from_txt.py` in my scripts?

**Comment by pseth** [comment]
The function is still there, but separated from the sumk_dft_tools.py, where it doesn't really belong -- it now lives in python/build_sigma_from_txt.py as you spotted.

**Comment by krivenko** [comment]
`build_sigma_from_txt.py` is apparently broken. Statements in the file have invalid indentation.
And what do I pass as `self` argument? `SumkDFTTools`?

**Comment by leopo** [comment]
One should correct it. 
However, in the case you are reading your real-energy self-energy from an h5 file, this function does not do much: it actually reads from h5 and that's it. You can probably substitute its call with:

            SigmaME=0
            if (mpi.is_master_node()):
                ar = HDFArchive('h5_filename')
                SigmaME = ar['real-energy-sigma']
                del ar
            SigmaME = mpi.bcast(SigmaME)
            mpi.barrier()

and then
            SK.put_Sigma(Sigma_imp = [ SigmaME ])

**Comment by pseth** [comment]
The point is that the txt file manipulation will not be supported/commented, and it was decided to remove this function. It was kept temporarily as a separate file to provide a template for those using Sigmas from txt files. It is not a stand-alone module.

**Comment by krivenko** [comment]
@leopo thank you for the recipe, Leonid.

> The point is that the txt file manipulation will not be supported/commented, and it was decided to remove this function. It was kept temporarily as a separate file to provide a template for those using Sigmas from txt files. It is not a stand-alone module.

O.k., this is what I actually wanted to know.
