### ISSUE TITLE
problem for SRVO3 

### ISSUE THREAD

**Issue by Soumeniisc** [TRIQS/dft_tools#36]
Hi!
I was using the same exactly same python script for DMFT as is given in source. I am getting following error.

https://gist.github.com/Soumeniisc/2bf374de807a497a066e
---------------------------------------------------------
Chemical Potential = 61.864286  
    Total Density = -0.727171
    11.364286 < Chemical Potential < 61.864286
    -1.141574 < Total Density < -0.727171
    FAILURE to adjust Chemical Potential  to the value 1.000000 after 101 iterations.
Traceback (most recent call last):
  File "SRVO-DMFT.py", line 77, in <module>
    S.G_iw << SK.extract_G_loc()[0]                         # calc the local Green function
  File "/home/soumen/INSTALLPACKAGES/23_10_15/lib/python2.7/dist-packages/pytriqs/applications/dft/sumk_dft.py", line 370, in extract_G_loc
    G_latt_iw = self.lattice_gf(ik=ik, mu=mu, iw_or_w="iw", with_Sigma=with_Sigma, with_dc=with_dc, beta=beta)
  File "/home/soumen/INSTALLPACKAGES/23_10_15/lib/python2.7/dist-packages/pytriqs/applications/dft/sumk_dft.py", line 304, in lattice_gf
    M[ibl] = self.hopping[ik,ind,0:n_orb,0:n_orb] - (idmat[ibl]*mu) - (idmat[ibl] * self.h_field * (1-2*ibl))
TypeError: unsupported operand type(s) for *: 'complex' and 'NoneType'

**Comment by pseth** [comment]
This is a problem in finding the chemical potential, potentially due to a insufficiently dense k-grid mesh. You can try two things:
1) Try with more k-points.
2) Try to set the chemical potential before the first call of calc_mu to different values (these will be the starting guesses) using SK.set_mu(mu) to help calc_mu out.

**Comment by Soumeniisc** [comment]
Hi!
Thank for your usefull instruction.This time I used 3000 k points and increased the no_cycle. Now above problem is sorted out but at 28 th LDA+DMFT iteration

**Comment by pseth** [comment]
It looks to me like a problem indeed in the wien2k part. Take a look at src/python/sumk_dft.py for the dc/chemical potential source code.

**Comment by aichhorn** [comment]
Hi, there is something seriously wrong in your setup. Your chemical potential is around 61eV!!! This cannote be. And moreover, you get a total density of -0.72!!! The density MUST be positive, it comes from the Greens function and is, up to some numerical errors, positive and normalised. 
My suggestion: You have to start again from the very first iteration, and check the very first G0 that you get from LDA if it makes sence physically. That means, the chemical potential should be around 0eV, the double counting should be around U*(N-1/2) (and not 61 for instance). It does not make sense to look for the error that you got at iteration 28, you have to sort out first what goes wrong in the very beginning. Very important: If your first iteration does not make sense, it makes no sense either to continue to the next iteration!

**Comment by mzingl** [comment]
I'd like to comment on your initial error. I usually get the same error in finding the chemical potential if quantities (G, Sigma, Delta ...) become unphysical (e.g. due to a positive imaginary part of the self-energy). It might be related to a poor statistics of your impurity solver, which leads to a lot of noise and eventually to a bad tail fit.  I don't know how many cores you are using for your calculations, but 5000 measurements (p["n_cycles"] = 5000) seems to be too little.  As Markus said you should check your first input AND also the first output of the ctqmc solver!

**Comment by pseth** [comment]
Ah oops, I didn't see your gist script. Yes, 50 warmup cycles and 5000 cycles is much too little! And remember that the number of warmup cycles needs to be independent of number of cores used as the Markov chains on each core are independent. Perhaps it was not linked to the number of kpoints after all (though that can cause mu finding issues in my experience..).

**Comment by Soumeniisc** [comment]
Hi!
Thanks for all useful comments. But in the second error (where i mentioned after 28 th iteration) i used 
p["max_time"] = -1
p["length_cycle"] = 200
p["n_warmup_cycles"] = 2000
p["n_cycles"] = 200000
i used single processor. Hopefully this didn't lead to a poor statistics of impurity solver. 
Thanks

**Comment by pseth** [comment]
The best thing to do is to take a look at the GFs and judge the correctness/noise for yourself, but 2000 warmup cycles is still not enough. I would say 50000 is a safer bet.

**Comment by mzingl** [comment]
I used at least n_cycles = 3*10^6 for SrVO3. You really need to look at your first self-energy! Usually, if you don't use a very large number of cycles you have to play around with the tail fit by setting fit_n_moments, fit_min_n and fit_max_n !

**Comment by Soumeniisc** [comment]
Hi all,
this time i used
p["max_time"] = -1
p["length_cycle"] = 200
p["n_warmup_cycles"] = 50000
p["n_cycles"] = 14*10^6

self energy is very noise. when i used the "fit_min_n"=40, self is not fitted smoothly with the  default moments. Any suggestion to deal with this. 
thanks

**Comment by aichhorn** [comment]
Can you show us in a plot what your self energy looks like? Otherwise it will be complicated to guess a solution. And please provide the text output of the FIRST DMFT iteration that you get (Wannier charge, chemical potential, double counting initialization, all this matters).

**Comment by Soumeniisc** [comment]
![sigma_gl_measure](https://cloud.githubusercontent.com/assets/4995258/7175717/4ec5d7d2-e435-11e4-9f2b-1f0b4c07642d.png)
![sigma_tau_measure](https://cloud.githubusercontent.com/assets/4995258/7175718/4ec75756-e435-11e4-8a2f-bd877e23947f.png)

**Comment by aichhorn** [comment]
The Sigma from G_tau looks okay, the data at low energy is fine. Only the tail fit goes crazy, there you have to change also the number of moments that you fit, or you use a larger fit_min_n to go further into the i/omega regime.
The Sigma from G_l looks completely crazy. What version of TRIQS and CTHYB did you use to produce this?

**Comment by Soumeniisc** [comment]
I am using triqs and dft_tool version 1.2 (recent one). 
after about w_{n=90} selfenegy is very fluctuating. In the above figures I used  number of moments=3(default) and default moments.  can anyone please let me know where and how these default moments are calculated?

**Comment by mzingl** [comment]
Your tailfit parameters are probably not ok. If you say that the self energy becomes very noisy after n=90, then try fit_min_n = 40 and fit_max_n = 90. Set fit_n_moments to 4 or 5. Look again at your self energy. Keep always in mind that you should adjust those parameters if you change the number of measurements.

**Comment by Soumeniisc** [comment]
After single sort LDA+DMFT itaration I plotted theband structore band with increased instead of decrease.
![srvo](https://cloud.githubusercontent.com/assets/4995258/7200233/8c15b6b4-e518-11e4-9836-6b2d116b0854.png)


 i run the following command to get the band structure
x lapw1 -band
x lapw2 -band -qtl
x spagetti
gv spaggeti_sp
U = 3.5
J = 0.68
beta = 40
energy after single shot LDA+DMFT(with 10 dmft iteration)
:ENE  : ********** TOTAL ENERGY IN Ry =        -8710.45826551
:ENE  : ********** TOTAL ENERGY IN Ry =        -8710.45827174
:ENE  : ********** TOTAL ENERGY IN Ry =        -8710.45914720(energy after LDA+DMFT)
DCenerg,correnerg,chemical_potential= 0.181868442213, 0.357777562245, -0.547734503006
self_energy_after_10_dmft_iteration
![self_energy_after_10_dmft_iteration](https://cloud.githubusercontent.com/assets/4995258/7200144/b3b90366-e517-11e4-8255-06cccfd26971.png)

**Comment by aichhorn** [comment]
????
What does your message mean?

**Comment by Soumeniisc** [comment]
Pls have a look at complete edited version

**Comment by aichhorn** [comment]
Oh, you try to plot the band structure like this? That does not work. What you are plotting is a modified LDA band structure, not the LDA+DMFT correlated band structure. Please go to the documentation http://ipht.cea.fr/triqs/applications/dft_tools/documentation.html
to see how this has to be done, see section 'Tools for analysis'. It involves an analytic continuation of your self energies to the REAL frequency axis, which is NOT part of TRIQS!!!!

**Comment by Soumeniisc** [comment]
Oh i see, Thanks
but I think for the recent version of triqs, documentation is not updated yet beacuse SK.check_input_dos(om_min, om_max, n_om) function is no longer there.

**Comment by mzingl** [comment]
check_input_dos() is now called dos_wannier_basis(). This function gives you the DOS in the Wannier basis. 
There is another function called dos_parproj_basis() which replaces dos_partial() and calculates the orbital resolved correlated DOS. However, you need to obtain a self energy on the real axis first!
And yes you are right - we are currently working on the documentation...

**Comment by Soumeniisc** [comment]
dos_wannier_basis() routines is not without real-frequency self energy. am i correct??

**Comment by mzingl** [comment]
1> No, just use with_Sigma=False as argument. However, what you really want to use is dos_parproj_basis and spaghetti to get your DFT+DMFT DOS and bandstructure. Here you need a real-frequency self energy!  
2> This a very general question. In principle your band structure will be "smeared out" (no discrete bands...) and your DOS will be quite different from the DFT one. Just have a look at papers with plots of DFT+DMFT  results. You will find plenty of them out ....

**Comment by Soumeniisc** [comment]
Hi 
Thanks 
this time command "x lapw2 -almd -band" giving "FERMI ERROR!"
Error in LAPW2
 'FERMI' - number of k-points inconsistent when reading kgen
 'FERMI' - check IN1 and KGEN files!
---------
the steps that i followed:
x lapw0 (worked)
x lapw1 -band  (worked)
x lapw2 -almd -band  (FERMI ERROR!)
but ...
x lapw2  -band -qtl (worked)
-----------------------------------------
Any suggestion?? please let me know if any file need to be shared.

**Comment by pseth** [comment]
I had this problem some time ago -- my solution is as follows:

1) x lapw1 -band
2) edit in2 file: replace 'TOT' with 'QTL', 'TETRA' with 'ROOT'
3) x lapw2 -almd -band
4) dmftproj -band (add the fermi energy to file, it can be found by running grep :FER *.scf)

Let me know if that works.

**Comment by Soumeniisc** [comment]
thanks,
it worked

**Comment by Soumeniisc** [comment]
Hi,

I have attaced plots for Dos of SRVO3 
case1: with out sigma
![dos_with_out_sigma](https://cloud.githubusercontent.com/assets/4995258/7586196/fb47d64e-f8c7-11e4-8e9f-6048ba694a57.png)
case2: with sigma
![dos_with_sigma](https://cloud.githubusercontent.com/assets/4995258/7586197/fbcf1ece-f8c7-11e4-852f-86a75ec131fe.png)

It clearly shows that lower and upper hubbard band is apeared. In the quasiparticle region band width is decreased(from 3 to 2). Will it be considered as band narrowing??? 

Thanks

**Comment by mzingl** [comment]
Do you use the newest version of dft_tools? I think the wrong sign was a bug, which should be corrected since a while.

**Comment by Soumeniisc** [comment]
Thanks ,

it worked
