### ISSUE TITLE
error message in SK.calc_density_correction with spin-orbit

### ISSUE THREAD

**Issue by pascaldelange** [TRIQS/dft_tools#38]
I am getting the following error message in SK.calc_density_correction in a LDA+Hub1 calculation close to the one given as example in the doc, but with spin-orbit :+1: 

Traceback (most recent call last):
  File "EuVO4.py", line 161, in <module>
    dN,d = SK.calc_density_correction(filename = lda_filename+'.qdmft')
  File "/home/delange/sources/TRIQS_1.2/install/lib/python2.7/site-packages/pytriqs/applications/dft/sumk_dft.py", line 842, in calc_density_correction
    fout.write("%.14f  %.14f "%(deltaN[bn][ik][inu,imu].real,deltaN[bn][ik][inu,imu].imag))
NameError: global name 'bn' is not defined

the same without spin-orbit (and without spin-polarization) seems to work fine.

**Comment by pseth** [comment]
Fixed. Please confirm and close.

**Comment by pascaldelange** [comment]
Seems to work, thank you.
