### ISSUE TITLE
dft-tools cmake problem

### ISSUE THREAD

**Issue by yesenia97** [TRIQS/dft_tools#40]
Dear all,

I just managed to install successfully the base set of TRIQS modules
and run the easiest examples. Now I want to move on to installing the
dft-tools but the cmake command renders this error message:

CMake Error at test/CMakeLists.txt:5 (triqs_add_test_hdf):
  Unknown CMake command "triqs_add_test_hdf".

I'm using ubuntu 14.04 with gcc/gfortran 4.8.2 and TRIQS 1.2

cmake command line and output: https://gist.github.com/yesenia97/1f8c12bd5afd94c94eb0#
CMakeCache.txt: https://gist.github.com/yesenia97/1ff37d340f30d1167486#

Thanks for any hint on this issue,
Yesenia

**Comment by mzingl** [comment]
Hi and sorry for the late response.

Try to use the absolute path of your triqs installation:
cmake -DTRIQS_PATH=/home/yesenia/Quanta/itriqs ../src-tools/

Regards,
Manuel

**Comment by mzingl** [comment]
Hi, is this issue solved?
Regards,
Manuel
