### ISSUE TITLE
I can not find the python module when using dft_tools

### ISSUE THREAD

**Issue by Joser1015** [TRIQS/dft_tools#45]
Dear Developers,

I am going to using a python script. The first line is:
from pytriqs.applications.dft.sumk_dft import *
but it complains that
No module named applications.dft.sumk_dft

In my /home/riping/software/triqs/lib/python2.7/site-packages/pytriqs/applications/dft  directory,
there is sumk_dft. 

when I "echo $PYTHONPATH", there is 
/home/riping/software/triqs/lib/python2.7/site-packages

Why it can not find the python module?

Thank you very much.

Joser
2015.2.10

**Comment by mzingl** [comment]
Dear Joser!
Do you use pytriqs testscript.py? Calling python testscript.py would give such an error.
Regards,
Manuel

**Comment by Joser1015** [comment]
Dear Manuel,

Do you mean that in triqs, I should always use  pytriqs, rather than python to run a python code?

Best regards.
Joser

**Comment by pseth** [comment]
Yes, you should always use pytriqs, which has the correct path to the triqs modules.

**Comment by Joser1015** [comment]
Dear Seth,

Can I open another issue, I will describe all the procedure of my installation.
And then I will show you my errors.

Best regards.
Riping Wang
2015.2.10

**Comment by pseth** [comment]
Ok, but please ensure that you have followed the installation instructions as outlined in the documentation first. Specifically, that you have updated your bashrc with a link to the TRIQS installation. In my setup, this is something like this:
```export PATH=$PATH:$HOME/SOURCES/TRIQS/install/bin```
