### ISSUE TITLE
Installation procedure of TRIQS and its related code

### ISSUE THREAD

**Issue by Joser1015** [TRIQS/dft_tools#46]
Dear Seth,

I installed the software " triqs, triqs/dfttools, trqis/cthyb, triqs/hubbardI"  in the following way. After describing my installation procedure, I have three questions.

I make build directories separately for each of the follow software: triqs, triqs/dfttools, trqis/cthyb, triqs/hubbardI.  And then I installed all these softwares in the one directory called triqs whose location is in parallel with the build directories.  

In each build directory, I run the following command before run "make; make install"
The cmake command for triqs is: 
cmake   -DCMAKE_INSTALL_PREFIX=/home/joser/software/triqs    ../triqs.src

The cmake command for triqs/cthyb is: 
cmake -DTRIQS_PATH=/home/joser/software/triqs  ../triqs_cthyb.src

The cmake command for triqs/dfttools is: 
cmake -DTRIQS_PATH=/home/joser/software/triqs  ../triqs_dfttools.src

The cmake command for triqs/hubbardI is: 
cmake -DTRIQS_PATH=/home/joser/software/triqs  ../triqs_hubbardI.src  

There two questions:
1. Can "triqs" directory used for all these for software with their build directories independent?
2. Is the DTRIQS_PATH correctly set?
3. Should the cthyb be installed before dfttools for after it? Does the order of intallating different codes matter?

Best regards.
Riping Wang
2016.2.10

**Comment by pseth** [comment]
It looks correct. Did you modify your bashrc?
1. the install directory has to be the same, the src and build dirs are completely independent
2. Yes, it all looks fine.
3. No, the order of applications doesnt matter. However the TRIQS library (triqs) needs to always be installed first.

**Comment by Joser1015** [comment]
Dear Seth,

Thank you very much.

I modifies the bashrc like this:

export LD_LIBRARY_PATH=/home/joser/software/trips/lib:$LD_LIBRARY_PATH
export C_INCLUDE_PATH=/home/joser/software/trips/include:$C_INCLUDE_PATH
export PATH=/home/joser/software/triqs/bin:$PATH

Is it correct?

Best regards.
Riping Wang
2016.2.10

**Comment by pseth** [comment]
That looks fine.

**Comment by pseth** [comment]
Can you confirm that you are using the latest versions of all the codes? Please update (git pull) each src directory and then reinstall. Are you still getting the same errors?

**Comment by Joser1015** [comment]
Dear Seth,

In my each source code directories fo triqs. I run "git pull".
And then I re-install from the very beginning, by removing previous installation.

Before installation, I run 
export CC=/home/riping/software/gcc-5.3.0/bin/gcc 
export CXX=/home/riping/software/gcc-5.3.0/bin/g++  

The cmake command gives the following information:
-- -------- LibClang detection -------------
-- Can not find libclang
-- Can not find the Clang compiler, hence can not find the option for libclang
-- Could NOT find LibClang (missing:  TRIQS_LIBCLANG_LOCATION TRIQS_LIBCLANG_CXX_ADDITIONAL_FLAGS) 
-- LibClang location: TRIQS_LIBCLANG_LOCATION-NOTFOUND

But the Cmake seems ok, it says that: 
-- -------- Making TRIQSConfig.cmake -------------
-- Configuring done
-- Generating done
-- Build files have been written to: /home/riping/software/triqs.build

When I run "make", it complains that:
 [ 10%] Building CXX object triqs/CMakeFiles/triqs.dir/h5/file.cpp.o
[ 10%] Building CXX object triqs/CMakeFiles/triqs.dir/h5/scalar.cpp.o
In file included from /home/riping/software/triqs.src/triqs/python_tools/wrapper_tools.cpp:7:0:
/home/riping/software/triqs.src/triqs/python_tools/./wrapper_tools.hpp:8:33: fatal error: triqs/utility/c17.hpp: No such file or directory
compilation terminated.
make[2]: *** [triqs/CMakeFiles/triqs.dir/python_tools/wrapper_tools.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 10%] Linking CXX shared library libgtest.so
[ 10%] Built target gtest
make[1]: *** [triqs/CMak


Do you have any idea?

Best regards.
Riping Wang
2015.2.11

**Comment by Joser1015** [comment]
Dear Seth,

There is no c17.hpp file in the following web:
https://github.com/TRIQS/triqs/tree/master/triqs/utility

But in triqs.src/triqs/python_tools/./wrapper_tools.hpp
#include <triqs/utility/c17.hpp>

How to deal with this issue?

Thank you very much.
Best regards.

Riping Wang
2016.2.11

**Comment by parcollet** [comment]
Hi, 
Sorry I forgot to add a file in pushing my commit yesterday night in the master branch.
Corrected.
OP

**Comment by Joser1015** [comment]
Dear Parcollet,

Thank you very much. 
I updated, and the installation now seems ok.
I can continue for tutorials now.

Best regards.
Riping Wang
2016.2.10
