### ISSUE TITLE
Installation directory of triqs/dfttools and triqs/cthyb

### ISSUE THREAD

**Issue by Joser1015** [TRIQS/dft_tools#47]
Dear Seth.

I and doing a single DFT-DFMT calculations, following the steps in the web http://ipht.cea.fr/triqs/applications/dft_tools/guide/dftdmft_singleshot.html#a-full-dft-dmft-calculation

Because I am now testing whether the pytriqs command can find the python module, I simply copied the following lines from that web to a python script and run it with pytriqs command:

from pytriqs.applications.dft.sumk_dft import *
from pytriqs.applications.impurity_solvers.cthyb import *
from pytriqs.gf.local import *
from pytriqs.archive import HDFArchive
from pytriqs.operators.util import *

It complains that it can not fined module pytriqs.applications.dft.sumk_dft and pytriqs.applications.impurity_solvers.cthyb . It can find the modules in other three lines. 

I then modified the corresponding two lines to be by removing the "pytriqs" within the lines, to be:
from applications.dft.sumk_dft import *
from applications.impurity_solvers.cthyb import *

It becomes able to find these two modules.

My questions now are:
1. Does it mean that the dfttools and cthyb are installed in "applications" directory rather than the "pytriqs/applications" directory?

2. Because the lines I copied is from the tutorial web, there must be some reason to find modules in the "pytriqs/applications" directory. For the consistency of future use, should I copy all the data in the "applications" directory to the "pytriqs/applications" directory by using the command line:
cp -rf applications/ .. /pytriqs/

Best regards.
Riping Wang
2015/2/10

**Comment by pseth** [comment]
@parcollet Do we still have these install issues?
