### ISSUE TITLE
python_with_DMFT: Command not found.

### ISSUE THREAD

**Issue by Joser1015** [TRIQS/dft_tools#50]
Dear Developers,

I am now able to run the single DFT-DMFT calculations using the script dft_dmft_cthyb.py provide on the web: https://triqs.ipht.cnrs.fr/applications/dft_tools/guide/dftdmft_singleshot.html#a-full-dft-dmft-calculation
 
I am now continue to run the self-consistent DFT-DMFT calculations using the command:
run_lapw   -qdmft  1   -NI

However, at the very beginning, it complains as follows.

Creation of the projectors...
Evaluation of the density matrices...

TOTAL CHARGE =    40.00000

=======================================
Computation of the Occupancies and Density Matrices in the desired energy window [   -0.11000;    0.14000]

Creation of the projectors...
Orthonormalization of the projectors...

Evaluation of the density matrices...

-------------------------------------
Density Matrices for the Correlated States :

  Sort =   2  Atom =   2  and Orbital l =   2

    0.000307    0.000000    0.000000   -0.000000    0.000000   -0.000000   -0.000000   -0.000000    0.000000    0.000000
    0.000000    0.000000    0.000307   -0.000000   -0.000000    0.000000    0.000000    0.000000   -0.000000    0.000000
    0.000000    0.000000   -0.000000   -0.000000    0.333303   -0.000000    0.000000   -0.000000   -0.000000    0.000000
   -0.000000    0.000000    0.000000   -0.000000    0.000000    0.000000    0.333303   -0.000000   -0.000000   -0.000000
    0.000000   -0.000000   -0.000000   -0.000000   -0.000000   -0.000000   -0.000000    0.000000    0.333303   -0.000000

The charge of the orbital is :    1.00052
Writing the file case.ctqmcout...
Writing the file case.symqmc...
Writing the file case.parproj...
Writing the file case.sympar...
Writing the file case.outbwin...

END OF THE PRGM
python_with_DMFT: Command not found.
forrtl: severe (24): end-of-file during read, unit 32, file /home/riping/TRIQS_data/SrVO3/SrVO3.qdmft
Image              PC                Routine            Line        Source             
lapw2              00000000004CE4D9  Unknown               Unknown  Unknown
lapw2              00000000004107C3  qdmft_mp_readdata          56  qdmft_tmp_.F
lapw2              000000000047D125  MAIN__                    233  lapw2_tmp_.F
lapw2              0000000000404406  Unknown               Unknown  Unknown
libc.so.6          00000034AF41ECDD  Unknown               Unknown  Unknown
lapw2              00000000004042F9  Unknown               Unknown  Unknown

>   stop error

Best regards.
Riping Wang

**Comment by aichhorn** [comment]
This is a known problem with the Wien2k run scripts. As written in the installation part of the documentation, you need to change the run_lapw file of your Wien2k. Look at the run_triqs scripts that come with TRQIS/DFTTools. You can put them into your Wien2k installation directory and use them instead of run_lapw.

**Comment by Joser1015** [comment]
Dear Aichhorn,

The current version of WIEN2k is 14.2, as written on this webL http://www.wien2k.at/

How can TRIQS user reach the 15.1 version of WIEN2k. I have license of 14.2 version.

Thank you very much.

Riping Wang
2016.2.16

**Comment by aichhorn** [comment]
Nobody (except Peter Blaha maybe) can reach version 15.1, since it is not published yet. The Wien2k developers are working on a new release, until then we have to live with the patch as described in the installation part of the DFTTools documentation.

**Comment by Joser1015** [comment]
Dear Aichhorn,

I passed the error of “python_with_DMFT: Command not found” following your instruction.
Thank you very much.

However, there is another error. I paste it in a new issue.

Riping Wang
2016.2.18
