### ISSUE TITLE
Reading .outband

### ISSUE THREAD

**Issue by Joser1015** [TRIQS/dft_tools#52]
Dear Developer,

I got the  .outband file for band structure using command "dmftproj -band".

 My questions is:
1. Do you have code to read this .outband file and plot out the bandstructure.

2. The format of  .outband is a bit strange. Is it correct or not. I attached the beginning lines of this file in this message.

Best regards.
Riping Wang
2016.2.14

    51
     3
     3
     3
     3
     3
     3
     3
     3
     3
     3
     3
     3
     3
     3
     3
     3
     5
     5
     5
     5
     5
     5
     5
     4
     4
     4
     4
     4
     4
     4
     4
     4
     4
     4
     3
     3
     3
     3
     3
     3
     3
     3
     3
     3
     3
     3
     4
     4
     5
     5
     5
  1.44674149873175754E-016  2.77935580272659128E-017  4.95403067737840122E-017
 -0.93106276428228130      -0.18220197606495514      -0.31610845816034999
  3.73009308956017094E-019 -1.14176482586126798E-019  1.37127500445107240E-019
 -0.15501838452288855       0.98184268981433009      -0.10933536186214952
  2.31499592875144771E-017 -1.50573968307231503E-016  1.62546805103848652E-017
 -0.33028989972810641       5.27954620364154484E-002  0.94240183030457436
  1.58212900882303323E-017 -1.08926144281901597E-017 -2.67625988218430848E-017
 -0.57735026277570278       0.20863537618172773       0.78939085791447627
  8.53762703086465192E-019  1.61001954392615105E-018 -8.23105898703639534E-018
  0.57735026274016787      -0.57931484840138370       0.57537896487111517
 -1.45139659482505363E-017  2.46730980906218381E-017 -1.71366038683223391E-017
 -0.57735026276713175      -0.78795022455915276      -0.21401189308195151
 -3.27053109515291015E-017 -4.41997186990391699E-018  4.48635989137662136E-017
 -0.57735027747698597      -6.54542688106497100E-002  0.81386878327430179
 -5.32358274354455272E-020  8.75934620572453018E-019 -1.20354194363013509E-018
  0.57735027747278789      -0.73755817607063900       0.35024933206235886
  3.27320131056209219E-017 -4.03285625182469632E-017  1.99748079904787125E-017
 -0.57735027747476253      -0.67210390725721414      -0.46361945121627601
 -1.35684705853312224E-018 -1.20775657313360368E-017  9.41566164362413887E-018
  0.57735026919335108       0.80824724159503136      -0.11577159606994628
 -4.25614690703868362E-019 -1.37515330490790433E-017 -5.18968403906962856E-018

**Comment by mzingl** [comment]
Dear Wang,
Converter.convert_bands_input reads the .outband file. After the conversion you simply call SK.spaghettis(). 
Have a look at "Momentum resolved spectral function (with real frequency self energy)" in: https://triqs.ipht.cnrs.fr/applications/dft_tools/guide/analysis.html#momentum-resolved-spectral-function-with-real-frequency-self-energy
Note that you need a real-frequency self-energy!
Regards,
Manuel
