### ISSUE TITLE
Can any one provide a full python script as an example of data analysis?

### ISSUE THREAD

**Issue by Joser1015** [TRIQS/dft_tools#53]
Dear Developer,

I got h5 file after a single DFT-DMFT calculations, and I am try to the results, to see using the tools of analysis. I follow the instruction on the web: https://triqs.ipht.cnrs.fr/1.4/applications/dft_tools/guide/analysis.html#analysis

There are many errors.

There first error is occurs when I run: 
ar = HDFArchive('case.h5', 'a')
SigmaReFreq = ar['dmft_output']['Sigma_w']

It complains that:
 KeyError: 'Key Sigma_w does not exist.' 

I think that this is only one of the errors. 

Can any one provide a full python script as an example of data analysis?
So that I can pass the first example, from which I can learn more.
It is 1.4 version. 
May be many things has been updated.

Thank you very much.
Riping Wang
2016.2.14

**Comment by mzingl** [comment]
Dear Wang,
for most analysis tools you have to provide a real-frequency self energy. The guide assumes that this is stored in the hdf archive 'case.h5' named 'Sigma_w' under the group 'dmft_output'. 
As stated in the documentation, tools for the analytic continuation are NOT included in the DFTTools/TRIQS package. Please have a look at this page: https://triqs.ipht.cnrs.fr/applications/dft_tools/guide/analysis.html 
Regards
Manuel

**Comment by aichhorn** [comment]
The problem is not the missing python script. You need to calculate a real-frequency self energy from your Matsubara self energy yourself. Then you store this real-frequency object in your hdf archive. Only then, you can use the analysis scripts.
