### ISSUE TITLE
error in transport calculations

### ISSUE THREAD

**Issue by Joser1015** [TRIQS/dft_tools#54]
Dear Developer,

I am now going to make transport calculations with version 1.4 of triqs/dfttools.
I follow the instruction on this web: https://triqs.ipht.cnrs.fr/applications/dft_tools/guide/transport.html

I first made .pmat file by optic calculations, and then run the command line on that web. 
I copied all the commands onto a python script dft_dmft_transport.py, and run it.

It complains the following. 

[riping@fermi SrVO3]$ pytriqs dft_dmft_transport.py 
Starting on 1 Nodes at : 2016-02-14 22:05:51.946968
Repacking the file SrVO3.h5
Reading input from SrVO3.pmat...
Traceback (most recent call last):
  File "dft_dmft_transport.py", line 9, in <module>
    Converter.convert_transport_input()
  File "/home/riping/software/triqs/lib/python2.7/site-packages/pytriqs/applications/dft/converters/wien2k_converter.py", line 590, in convert_transport_input
    R.next()
StopIteration

Can any one give a example python file for transport calculations?

Best regards.
Riping Wang
2016.2.14

**Comment by mzingl** [comment]
Dear Wang,
the code seems to have troubles reading your .pmat file. Please tell me your Wien2k version and post here a few lines of your .pmat file.
Regards,
Manuel

**Comment by Joser1015** [comment]
Dear Manuel,

I follow the instruction on the web: https://triqs.ipht.cnrs.fr/1.3/applications/dft_tools/guide/transport.html#userguide

Let me confirm some of my understanding on the calculations of .pmat file.

For the convenience of discussion, I copied down the instruction of generating .pamt file in that web here. It is:
The basics steps to calculate the matrix elements of the momentum operator with the Wien2k optics package are:1.Perform a standard Wien2k calculation for your material.
2.Run x kgen to generate a dense k-mesh.
3.Run x lapw1.
4.For metals change TETRA to 101.0 in case.in2.
5.Run x lapw2 -fermi.
6.Run x optic.

My question is 
1. After the single dft-dmft calculations,do I need to rerun the normal WIEN2k scf consistent calculation for the purpose of .pmat?
2. For SrVO3, do I need to change the TETRA to be 101.1, or leave it as 0?
3. When I run x kgen, I set the number of K point to be 12000. In this case how should I set the "number of k-points" and "NBvalMAX" in .inop file?  I set the first as 12000, and the later as 10. Is it ok?
4. Starting from the .strut file, I make initialization with -numk 3000. And after that I run_lapw, I use "x kgen" with number of K point to be 10000. It is ok? I copied my command as the following:
init_lapw -bw -vxc 5 -numk 3000  
run_lapw -cc 0.001 -NI -p
x kgen     (At this step, I set the number of K-points to be 10000)
x lapw1
x lapw2 -fermi
x optic 

5. The obtained SrVO3 file is empty. I copied down my SrVO3.inop file and the record of "x optic". Could you please check it?


SrVO3.inop:
12000 1       number of k-points, first k-point
-5.0 3.0 18 Emin, Emax for matrix elements, NBvalMAX
2             number of choices (columns in *outmat): 2: hex or tetrag. case
1             Re xx
3             Re zz
OFF           ON/OFF   writes MME to unit 4

Choices:
1......Re <x><x>
2......Re <y><y>
3......Re <z><z>
4......Re <x><y>
5......Re <x><z>
6......Re <y><z>
7......Im <x><y>
8......Im <x><z>
9......Im <y><z>


 


[riping@fermi SrVO3]$ x optic
 emin,emax,nbvalmax  -5.00000000000000        3.00000000000000               18
 creating ust
 kmin,kmax         -10         -10         -10          10          10
          10
 OPTIC END
34.077u 0.280s 0:34.54 99.4%	0+0k 0+24376io 0pf+0w



6. Could you please give a SrVO3.inop file that works? 




Best regards.
Riping Wang
2016.2.15

**Comment by aichhorn** [comment]
First thing: Get a real frequency self energy! There is no point in fiddling around with this optics stuff as long as you don't have done that.

**Comment by Joser1015** [comment]
Dear Seth,

Please close this issue first. 
I am practicing the way of getting real-frequency self energy.

Riping Wang
2016.2.24

**Comment by pseth** [comment]
Ok, I will, but FYI you can close it by clicking 'Close' below too.
