### ISSUE TITLE
Errors in fully self-consistent dft_dmft calculations

### ISSUE THREAD

**Issue by Joser1015** [TRIQS/dft_tools#57]
Dear Developers,

I am running the full self-consistent dft-dfmt calculations after passing the single dft-dfmt calculations.
I follow the instruction on the web:  https://triqs.ipht.cnrs.fr/1.3/applications/dft_tools/guide/dftdmft_selfcons.html?highlight=qdmft

However, it have three errors.

First. it has error of “Segmentation fault (11)” when the code is executing the following line: 
correnerg = 0.5 * (S.G_iw * S.Sigma_iw).total_density()
In the SrVO3.py file, the only parameter containing “total_density” is S.G_iw.total_density.
Therefore I modifies the above command to be 
correnerg = 0.5 * (S.G_iw * S.Sigma_iw)*S.G_iw.total_density()
However, I am not sure it is correct or not. Anyway, the python script can run ahead.

Second,  it stops when meeting:
correnerg -= SK.dc_energ[0]
This is for 1 impurity, not suitable for SrVO3.
I can not well master the well explained on the web I pasted at the beginning of this message on how to set  SK.dc_energ for SrVO3.  Could any one make it works for this first example. 

Third, when I commented  the line “correnerg -= SK.dc_energ[0]” to make the python go ahead. It has another error when running “    f.write("%.16f\n"%correnerg)” .It complains that “TypeError: float argument required, not BlockGf”.  

In sum, this message requests help for three message. Could you any directly provide a pythons script that works for the full self-consistent calculation for SrVO3? Without the first successful example, it is really difficult to go ahead.

Thank you very much.
Riping Wang
2016.2.19

**Comment by mzingl** [comment]
Hi,
I have checked the following lines:
`correnerg = 0.5 * (S.G_iw * S.Sigma_iw).total_density()
correnerg -= SK.dc_energ[0]
if (mpi.is_master_node()):
  f=open(dft_filename+'.qdmft','a')
  f.write("%.16f\n"%correnerg)
  f.close()`

It works without errors both in the newest version and in version 1.3.
This means that there is something wrong in your script BEFORE those lines!

Regards,
Manuel
