### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by pascaldelange** [TRIQS/dft_tools#59]
Dear all,

I have a problem when compiling dft_tools (or cthyb, actually) on the new hedin cluster at CPHT.
I am getting the following error : (the main triqs compilation and tests work)
Note that this is an older version (1.2)

> In file included from /cluster/apps/boost/gcc/1.60.0/include/boost/variant/apply_visitor.hpp:16:0,
>                  from /cluster/apps/boost/gcc/1.60.0/include/boost/variant/detail/hash_variant.hpp:23,
>                  from /cluster/apps/boost/gcc/1.60.0/include/boost/variant/variant.hpp:34,
>                  from /cluster/apps/boost/gcc/1.60.0/include/boost/variant.hpp:17,
>                  from /home/delange/sources/TRIQS_1.2/cthyb/src/c++/solver_core.cpp:26:
> /cluster/apps/boost/gcc/1.60.0/include/boost/variant/detail/apply_visitor_unary.hpp: In instantiation of ‘typename Visitor::result_type boost::apply_visitor(Visitor&, Visitable&) [with Visitor = cthyb::index_visitor; Visitable = const triqs::utility::variant_int_string; typename Visitor::result_type = void]’:
> /home/delange/sources/TRIQS_1.2/cthyb/src/c++/solver_core.cpp:62:63:   required from here
> /cluster/apps/boost/gcc/1.60.0/include/boost/variant/detail/apply_visitor_unary.hpp:70:43: error: ‘const class triqs::utility::variant_int_string’ has no member named ‘apply_visitor’
>      return visitable.apply_visitor(visitor);
>                                            ^
> /cluster/apps/boost/gcc/1.60.0/include/boost/variant/detail/apply_visitor_unary.hpp:70:43: error: return-statement with a value, in function returning 'void' [-fpermissive]
> make[2]: *** [c++/CMakeFiles/cthyb_c.dir/solver_core.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [c++/CMakeFiles/cthyb_c.dir/all] Error 2
> make: *** [all] Error 2
> [  4%] Building CXX object c++/CMakeFiles/cthyb_c.dir/solver_core.cpp.o
> In file included from /cluster/apps/boost/gcc/1.60.0/include/boost/variant/apply_visitor.hpp:16:0,
>                  from /cluster/apps/boost/gcc/1.60.0/include/boost/variant/detail/hash_variant.hpp:23,
>                  from /cluster/apps/boost/gcc/1.60.0/include/boost/variant/variant.hpp:34,
>                  from /cluster/apps/boost/gcc/1.60.0/include/boost/variant.hpp:17,
>                  from /home/delange/sources/TRIQS_1.2/cthyb/src/c++/solver_core.cpp:26:
> /cluster/apps/boost/gcc/1.60.0/include/boost/variant/detail/apply_visitor_unary.hpp: In instantiation of ‘typename Visitor::result_type boost::apply_visitor(Visitor&, Visitable&) [with Visitor = cthyb::index_visitor; Visitable = const triqs::utility::variant_int_string; typename Visitor::result_type = void]’:
> /home/delange/sources/TRIQS_1.2/cthyb/src/c++/solver_core.cpp:62:63:   required from here
> /cluster/apps/boost/gcc/1.60.0/include/boost/variant/detail/apply_visitor_unary.hpp:70:43: error: ‘const class triqs::utility::variant_int_string’ has no member named ‘apply_visitor’
>      return visitable.apply_visitor(visitor);
>                                            ^
> /cluster/apps/boost/gcc/1.60.0/include/boost/variant/detail/apply_visitor_unary.hpp:70:43: error: return-statement with a value, in function returning 'void' [-fpermissive]

The same version compiles and works on weiss... any help ?

**Comment by pseth** [comment]
Looks like a boost problem. Can you try with the latest version? Any specific reason you are using 1.2?

**Comment by pascaldelange** [comment]
Seems to be a boost issue indeed... Not worth the effort though, I'll just upgrade my scripts.
