### ISSUE TITLE
`application_pytriqs_import` screws up `import as`

### ISSUE THREAD

**Issue by opeil** [TRIQS/dft_tools#60]
`application_pytriqs_import()` in  `sitecustomize.py` messes up module names after an import.

For instance, doing something like this: `import pytriqs.applications.dft.sumk_dft as sumk` will produce an error `AttributeError: 'module' object has no attribute 'applications'`.

What is the purpose of renaming the modules?

**Comment by parcollet** [comment]
This is for Igor and Michel @mferrero

**Comment by krivenko** [comment]
Hi Oleg,
`sitecustomize.py` serves to logically construct `pytriqs` package from two physical sources, the installed Python tree (usually `${TRIQS_PATH}/lib/python2.7/site-packages/pytriqs`) and ` ${CMAKE_BINARY_DIR}/python` of your application. Normally, it affects only the tests of `dft_tools`. It allows the tests to import freshly built modules from `pytriqs.applications.dft` as if they have already been installed.

Looks like I could fix your issue by adding an ugly hack to `sitecustomize.py`, which is a sort of hack itself. So, maybe, a cleaner and easier option would be simply to avoid using `as` in the tests at all.

@parcollet @mferrero 
My package renaming trick will become obsolete as we move to Python 3. Python 3.3 implements [PEP 0420](https://www.python.org/dev/peps/pep-0420/). To sum up, this PEP prescribes the Python interpreter to scan all elements of `sys.path` in search for the requested module. Even in a situation when some subtrees of the parent package (but not the requested module) have been found

**Comment by mzingl** [comment]
Hi,
what is the status of this issue?
Best,
Manuel

**Comment by mzingl** [comment]
Ok
