### ISSUE TITLE
dmftproj not found

### ISSUE THREAD

**Issue by kashikarravi** [TRIQS/dft_tools#62]
I want to do LDA+DMFT calculations. I have installed "dfttools " properly (I think so). I am doing "Ce-gamma" test calculation, I performed Wien2k-SCF calculation. The path is  "/home/cmtcl/WIEN2k_cal/Ce/ce1"  . To do DMFT calculation , I started with "x lapw2 -almd"  in same directory and it show like this
<U|U> :  1  0    1.000000

<U|U_dot> :  1  0   -0.000000

<U_dot|U_dot> :  1  0    0.076379
   :
   :
   : 
  nLO_prn =            0
 MODUS=ALMD
 ALMBLM coeff. have been printed. lapw2 stop
 LAPW2 END
0.2u 0.0s 0:00.26 96.1% 0+0k 0+5488io 0pf+0w

After this I hit "dmftproj" its showing
dmftproj: command not found

I will be thankful if you Pls explain how to proceed after  "x lapw2 -almd" in detail

**Comment by pseth** [comment]
If you can't find dmftproj, it means it hasn't installed correctly into your path. Please follow the dft_tools installation directions online.

**Comment by kashikarravi** [comment]
I have installed dft_tools again without any error. TRIQS library is installed in "/home/cmtcl/triqs.src/cmake" path, which is working fine. I did instillation of  'CT-HYB'  and 'dft_tools' with this same path only and wrote this path in 'bashrc' file also. Now I am doing calculation in "/home/cmtcl/WIEN2k_cal/srvo/srvo" and I am unable to link these paths, so that "dmftproj" will work. please help me to solve this issue

WIEN2K installed directory is /home/cmtcl/WIEN2k_14

**Comment by mzingl** [comment]
Is this still an open issue?

**Comment by kashikarravi** [comment]
I have got the solution, you can close it.
