### ISSUE TITLE
Dos plot error

### ISSUE THREAD

**Issue by kashikarravi** [TRIQS/dft_tools#64]
I did SrVO3 dft+dmft scf calculations successfully using Hubbard I approximation. In post processing DOS caluculations I am getting following error
__________________________________
Starting on 1 Nodes at : 2016-07-14 18:20:13.899543
Repacking the file srvo1.h5
Reading input from srvo1.ctqmcout...
Reading input from srvo1.symqmc...
Reading input from srvo1.oubwin...
Reading input from srvo1.struct...
Reading input from srvo1.outputs...
Reading input from srvo1.parproj...
Reading input from srvo1.sympar...
DC after reading SK:  {'down': array([[ 1.3536943,  0.       ,  0.       ],
       [ 0.       ,  1.3536943,  0.       ],
       [ 0.       ,  0.       ,  1.3536943]]), 'up': array([[ 1.3536943,  0.       ,  0.       ],
       [ 0.       ,  1.3536943,  0.       ],
       [ 0.       ,  0.       ,  1.3536943]])}
Traceback (most recent call last):
  File "srvo1_dos.py", line 44, in <module>
    S.set_atomic_levels( eal = eal )
  File "/home/cmtcl/triqs.src/cmake/lib/python2.7/dist-packages/pytriqs/applications/impurity_solvers/hubbard_I/hubbard_solver.py", line 268, in set_atomic_levels
    self.ealmat[cnt*self.Nlm + ii,cnt*self.Nlm + jj] = self.Eff_Atomic_Levels[ind][ii,jj]
IndexError: index 3 is out of bounds for axis 1 with size 3
-------------------------------------------------------------------------------------
I have used case_dos.py file from Ce test example given in website.

**Comment by mzingl** [comment]
Hi,
I just tried a single shot calculation for SrVO3 and both example scripts run without an error. 
Have you modified those scripts?
Which TRIQS, HubbardI and DFTTools versions are you using?

**Comment by kashikarravi** [comment]
Hi
I am using all updated versions. Frequently I am facing error in case.py and case_dos.py scripts to run the scf calculations. Can you suggest what modifications I have to make to run the compound material calculation (currently I did SrVO3  scf properly but unable to get DOS).

**Comment by mzingl** [comment]
I think now I understand what you are doing.
Are you using the script  "Ce-gamma_DOS.py" from the "DFT+DMFT tutorial: Ce with Hubbard-I approximation" page together with an output from a calculation for SrVO3 with the CTHYB solver? This can never work!
Those are two completely different tutorials:

- The Cerium tutorial is only for the Hubbard I solver, so you have to use this solver also for your DMFT calculation! 

- Everything else is for SrVO3, but with the CTHYB solver.  To proceed after your sc calculation go to "Tools for Analysis", however, you will need to do an analytic continuation with MaxEnt. Note that this is not provided by TRIQS!

**Comment by kashikarravi** [comment]
Thank you for your reply. Now I am run the SrVO3 with  Hubbard I solver
(which I took from again Ce tutorial), and I hit *pytriqs srvo.py, *After
few seconds its giving error.
_______________________________________________________

cmtcl@ravi:~/WIEN2k_cal/srvo2$ pytriqs srvo2.py

Starting on 1 Nodes at : 2016-07-19 09:29:53.028192
Reading input from srvo2.ctqmcout...
Reading input from srvo2.symqmc...
Reading input from srvo2.oubwin...
Reading input from srvo2.struct...
Reading input from srvo2.outputs...
Dichotomy adjustment of Chemical Potential to obtain Total Density =
1.000000 +/- 0.000001
    Chemical Potential = 0.500000
    Total Density = 2.132907
    0.000000 < Chemical Potential < 0.500000
    0.851735 < Total Density < 2.132907
    0.057863 < Chemical Potential < 0.500000
    0.896274 < Total Density < 2.132907
    0.094948 < Chemical Potential < 0.500000
    0.978967 < Total Density < 2.132907
    0.094948 < Chemical Potential < 0.102331
    0.978967 < Total Density < 1.004420
    0.101049 < Chemical Potential < 0.102331
    0.999752 < Total Density < 1.004420
    0.101118 < Chemical Potential < 0.102331
    0.999997 < Total Density < 1.004420
    0.101118 < Chemical Potential < 0.102331
    1.000000 < Total Density < 1.004420
    Chemical Potential found in 7 iterations :
    Total Density = 1.000000;Chemical Potential = 0.101118

Traceback (most recent call last):
  File "srvo2.py", line 71, in <module>
    S.G <<= SK.extract_G_loc()[0]
  File
"/home/cmtcl/triqs.src/cmake/lib/python2.7/dist-packages/pytriqs/gf/local/block_gf.py",
line 258, in __ilshift__
    for (i,g) in self: g.copy_from(A[i])
RuntimeError: .. Error occurred at Tue Jul 19 09:30:01 2016

.. Error .. calling C++ overload
.. copy_from(gf_view<imfreq> other) -> void
.. in implementation of method GfImFreq.copy_from
.. C++ error was :
.. Triqs runtime error at
/home/cmtcl/triqs.src/triqs/./gfs/./impl/../singularity/tail.hpp : 252

tails are incompatible
.. Error occurred on node 0
--------------------------------------------------------------------------------------------------------------------------

 what modifications I have to do  in case.py file (Hubbard solver), for
compound material calculations


Ravi

Kashikarravi

**Comment by mzingl** [comment]
In this case the Hubbard I solver expects all five 3d-orbitals. However, in the case.indmftpr file the projection is only performed to the 3 t2g orbitals. You have to modify this part of your case.indmftpr file and probably also your projective energy window. 

Let me also add a word of caution here (probably you are already aware):
Playing around with those things is completely fine as a training and learning purpose and helps to understand how TRIQS works. However, keep in mind that Hubbard I is a very crude approximation and is only used in special cases (e.g. f-bands in Ce). For most materials, including SrVO3, you will most likely need to use the CTHYB solver to produce reliable results. In general, each material requires a different treatment, as you see in the case of the SrVO3 and Ce examples. Therefore, it is mutually import to understand how DFT+DMFT and TRIQS works and how the different parts play together. Let me also point to this page: [https://triqs.ipht.cnrs.fr/1.4/applications/dft_tools/basicnotions/first.html](url), which includes a reference to our github tutorials.

**Comment by kashikarravi** [comment]
Thank you for the reply.

Kashikarravi
