### ISSUE TITLE
problem with sumk.read_input_from_hdf ? 

### ISSUE THREAD

**Issue by the-hampel** [TRIQS/dft_tools#67]
Hi,

I think I have some trouble with the sumk function sumk.read_input_from_hdf. I wanted to read data from a h5 archive to post-process dmft output. I need the lattice Gf function and need therefore to set sigma in the sumk object. However, I had problems that the keys 'down' and 'up' did not match to the ones in sigma: 'down_0' / 'up_0'.  Therefore I used the function sumk.read_input_from_hdf to read the structure of the solver_to_sumk objects etc.  Here a small example:
```
sumk = SumkDFT(path+'pbnm.h5', use_dft_blocks=False)

print sumk.gf_struct_solver
print sumk.solver_to_sumk
print '-----'

# read structure from hdf archive
sumk.read_input_from_hdf(subgrp='dmft_input',things_to_read=['gf_struct_solver','solver_to_sumk'])

print sumk.gf_struct_solver
print sumk.solver_to_sumk
print '-----'

#now setting Sigma from calculation into sumk
sumk.set_Sigma([wpbnm['dmft_output-it24']['Sigma_iw_imp0']])
```
which gives the output:
```
[{'down': [0, 1], 'up': [0, 1]}]
[{('down', 1): ('down', 1), ('up', 1): ('up', 1), ('down', 0): ('down', 0), ('up', 0): ('up', 0)}]
-----
[{'up_0': [0, 1], 'down_0': [0, 1]}]
[{"('down_0', 1)": ('down', 1), "('down_0', 0)": ('down', 0), "('up_0', 0)": ('up', 0), "('up_0', 1)": ('up', 1)}]
-----
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-586-2ae72037310d> in <module>()
     20 
     21 #now I can use:
---> 22 sumk.set_Sigma([wpbnm['dmft_output-it24']['Sigma_iw_imp0']])

/home/ahampel/git/triqs/installed/lib/python2.7/dist-packages/pytriqs/applications/dft/sumk_dft.pyc in set_Sigma(self, Sigma_imp)
    562 
    563     def set_Sigma(self, Sigma_imp):
--> 564         self.put_Sigma(Sigma_imp)
    565 
    566     def put_Sigma(self, Sigma_imp):

/home/ahampel/git/triqs/installed/lib/python2.7/dist-packages/pytriqs/applications/dft/sumk_dft.pyc in put_Sigma(self, Sigma_imp)
    605                     for ind2 in inner:
    606                         block_sumk, ind1_sumk = self.solver_to_sumk[
--> 607                             ish][(block, ind1)]
    608                         block_sumk, ind2_sumk = self.solver_to_sumk[
    609                             ish][(block, ind2)]

KeyError: ('up_0', 0)
```
Somehow read_input_from_hdf puts a string rather directly the tuple into the dict of solver_to_sumk. Whereas for gf_struct_solver everything looks good. If I now convert the strings into tuples everything works:
```
sumk = SumkDFT(path+'pbnm.h5', use_dft_blocks=False)
​
print sumk.gf_struct_solver
print sumk.solver_to_sumk
print '-----'
​
# read structure from hdf archive
sumk.read_input_from_hdf(subgrp='dmft_input',things_to_read=['gf_struct_solver','solver_to_sumk'])
​
print sumk.gf_struct_solver
print sumk.solver_to_sumk
print '-----'
​
# fix string to key
sumk.solver_to_sumk[0] = {eval(k): v for k,v in sumk.solver_to_sumk[0].items()}
​
print sumk.gf_struct_solver
print sumk.solver_to_sumk
print '-----'
​
#now I can use:
sumk.set_Sigma([wpbnm['dmft_output-it24']['Sigma_iw_imp0']])
[{'down': [0, 1], 'up': [0, 1]}]
[{('down', 1): ('down', 1), ('up', 1): ('up', 1), ('down', 0): ('down', 0), ('up', 0): ('up', 0)}]
-----
[{'up_0': [0, 1], 'down_0': [0, 1]}]
[{"('down_0', 1)": ('down', 1), "('down_0', 0)": ('down', 0), "('up_0', 0)": ('up', 0), "('up_0', 1)": ('up', 1)}]
-----
[{'up_0': [0, 1], 'down_0': [0, 1]}]
[{('up_0', 0): ('up', 0), ('down_0', 0): ('down', 0), ('up_0', 1): ('up', 1), ('down_0', 1): ('down', 1)}]
-----
```
Is this a small bug in the read function, or is my h5 archive not setup correctly? Or should one not do this in this way? Thank you very much!

**Comment by gkraberger** [comment]
Hi Alex,

How did you write gf_struct_solver to the h5 file in the first place? I think that HDF does not support writing dicts with non-string keys. 
See [TRIQS doc](https://triqs.ipht.cnrs.fr/1.4/reference/hdf5/protocol1.html): _The object which can be reduced to and reconstructed from a dictionary whose keys are strings..._

A workaround would be to create a h5-exportable object instead of the dict. I tried something like that, however changing sumk.solver_to_sumk to a different object is maybe not possible without breaking backward compatibility, so we should approach this carefully.

**Comment by the-hampel** [comment]
Thanks for the quick reply Gernot!

Ok, I should have red the doc more carefully...  I think I understand the problem. I use something like:
```
sumk = SumkDFT(path+'test.h5', use_dft_blocks=False)

items_to_save = ['gf_struct_solver','sumk_to_solver','solver_to_sumk','solver_to_sumk_block','deg_shells']

f = HDFArchive(path+'test.h5','a')
## write some input parameters to the archive
f.create_group('dmft_input')
ar = f['dmft_input']

for item in items_to_save: ar[item] = getattr(sumk, item)
del f
```
to write the dmft input to the h5 file. So when I actually try to write a tuple as key into the h5 archive, it automatically converts this to a string? 

Then the quickest solution would be then to use my trick with eval afterwards or not? Probably there is a way more elegant way to write everything into the h5, but I'm not really an expert ;-)

**Comment by gkraberger** [comment]
> So when I actually try to write a tuple as key into the h5 archive, it automatically converts this to a string? 

Yes.

For now you can sure use the eval trick, however I wouldn't include this trick in the SumkDFT class because I get a bit worried when a key gets executed by python (bad stuff can happen when you start executing user-supplied strings!). I will discuss tomorrow with @aichhorn, I might have a cleaner solution...

**Comment by krivenko** [comment]
Hey,

This issue has once been discussed here https://github.com/TRIQS/triqs/issues/220.

**Comment by the-hampel** [comment]
Good Morning, 

of course it is not a good idea; one could write any code in their, which would be executed... However, thanks so far. At least I understood the problem and I see, that the problem was already discussed a year ago. I mean the other option would be to initialize sumk in the same way as I did in the actual calculation to get the same structures. In the end I just need a way to get the lattice Green's function with the correct Sigma from the h5 file.

**Comment by gkraberger** [comment]
Hi,

as I also need the functionality to save and manipulate Green's function structures and have some code doing these things lying around, I will put them into a nice class and integrate it into dft_tools (without breaking backward-compatibility). I'll keep you posted on that.

**Comment by krivenko** [comment]
> For now you can sure use the eval trick, however I wouldn't include this trick in the SumkDFT class because I get a bit worried when a key gets executed by python (bad stuff can happen when you start executing user-supplied strings!).

There is a safe alternative to `eval()` called [ast.literal_eval()](https://docs.python.org/2/library/ast.html#ast.literal_eval). It reconstructs basic Python types from their string representation, as defined by `__repr__()`.

**Comment by gkraberger** [comment]
Hi,

I finally pushed the new class. You can now save and load the SumkDFT.block_structure object.
If you need to manipulate the GF structure in ways not covered by that class, please complain ;-).

I hope the solution of saving the whole SumkDFT.block_structure object instead of the individual gf_struct_solver, sumk_to_solver, etc. is ok for you and fits into your workflow. I think it's cleaner because you cannot (or, at least, should not) change one without the others.

**Comment by the-hampel** [comment]
I just tested your new block_structure commit. So far it works like a charm! I saved data to h5 and could easily load it with the correct block structures for everything afterwards. Perfect, thank you very much!
