### ISSUE TITLE
trans_basis.rotate_gf bug

### ISSUE THREAD

**Issue by gkraberger** [TRIQS/dft_tools#68]
trans_basis.rotate_gf has a bug for all but trivial solver_to_sumk mappings

Reminder to self: fix this bug and check rest of trans_basis

**Comment by gkraberger** [comment]
Basically done, but the SK.T written by most converters is not what I expected. When choosing just the t2g subspace, should SK.T be a 3x5 matrix or a 5x5 matrix? I thought it should be 3x5, but it is 5x5. Is that a bug or is there a reason for that?

**Comment by aichhorn** [comment]
this is not used any more. closing.
