### ISSUE TITLE
HkConverter + SumkDFT class

### ISSUE THREAD

**Issue by dmantadakis** [TRIQS/dft_tools#72]
Dear All,

I have a few questions concerning the format of the Hamiltonian when using the HkConverter to create its HDF extension used in SumkClass. In my problem I have 2 equivalent t2g atoms in the unit cell but I want to include explicitly the spin-orbital degrees of freedom, so my hamiltonian for each k-point should be a 12x12 matrix (complex in general). 

**1)** When I will write down the hamitlonian into a .txt file, the sequence of the orbitals should be of the form _"Atom 1 - spin Up block  /  Atom 2 - spin Up block  /  Atom 1 - spin Down block  / Atom 2 - spin Down Block"_  OR  _"Atom 1 - spin Up block  / Atom 1 - spin Down block  /  Atom 2 - spin Up block  / Atom 2 - spin Down block"_ ??

**2)** I wrote the following preamble of the file 
```
1000   # nk points
4         # density
2         # correlated atoms
1  1  2  6
2  1  2  6
2     
1  1  2  6  1  0
2  1  2  6  1  0
2  6
2  6
```

is that correct??

**3)** In the SumkClass I have
```
SK = SumkDFT("hamitonian.h5")
SK.put_Sigma(Sigma_imp = [Sigma["full"]]) # Full (Atom1 + Atom2) self-energy 
mu = SK.calc_mu(precision  = 0.01)
SK.set_mu(mu)
Gloc << SK.extract_G_loc()[0]
```

Shouldn't be Gloc the local green's function of the correlated atom?? In my case Gloc["Atom1"] or Gloc["atom2"]... (Here I have an error about incompatible tails)

Thanks in advance!!

**Comment by mzingl** [comment]
This is a bit embarrassing that no one volunteered to help you or answer your question for such a long time. Is this still an open issue?

Best,
Manuel
