### ISSUE TITLE
Bug in elstruct.py function debug_density_matrix

### ISSUE THREAD

**Issue by the-hampel** [TRIQS/dft_tools#75]
Hi,
there is a small bug in the debug_density_matrix function. In line 140 a list of ions is created:
```
ions = list(set([param['isite'] for param in self.proj_params]))
```
The problem is, that this list is not sorted, which can result in a wrong order of atoms in the output. This gave me some trouble. Would it be possible to change the line to:
```
ions = sorted(list(set([param['isite'] for param in self.proj_params])))
```
which then gives the atoms in ascending order. 
Thanks,
Alex

**Comment by opeil** [comment]
This is why it's called 'debug_...()'. :-) I have commited a fix. Could you check that it works?

**Comment by the-hampel** [comment]
Perfect - works, thanks a lot. I changed that all the time manually, but this morning it took me 3 hours to realize what is wrong with my freshly installed dft_tools.
