### ISSUE TITLE
failing test: gf_struct is list and not dict

### ISSUE THREAD

**Issue by leopo** [TRIQS/dft_tools#89]
The test srvo3_Gloc in dft_tools fails in the latest version of [unstable]

> Traceback (most recent call last):
>   File "/home/leonid/TRIQS1.4_unst/dft_tools/src/test/srvo3_Gloc.py", line 43, in <module>
>     glist = [ GfImFreq(indices=inner,beta=beta) for block,inner in gf_struct.iteritems()]
> AttributeError: 'list' object has no attribute 'iteritems'

 The reason seems to be that gf_struct  returned by set_operator_structure in pytriqs/operators/util/op_struct.py is now a list, while in the test it is expected to be a dict (as before in 1.4). I guess, either this test or set_operator_structure should be corrected.

**Comment by Wentzell** [comment]
Hey Leonid,

Indeed the type of gf_struct has been adjusted to a list (from a dict), as previously block order was 
not properly maintained. I will look into the update of dft_tools as soon as possible.

**Comment by Wentzell** [comment]
Fixed in 72c7f57

**Comment by leopo** [comment]
Hi Nils,

I downloaded the latest [unstable] and dft_sumk.py still returns gf_struct_solver as a dict and not a list, see its definition in sumk_dft.py line 127

> 
>             self.gf_struct_solver = [dict([(sp, range(self.corr_shells[self.inequiv_to_corr[ish]]['dim']))
>                                            for sp in self.spin_block_names[self.corr_shells[self.inequiv_to_corr[ish]]['SO']]])
>                                      for ish in range(self.n_inequiv_shells)]

it is not consistent with what is expected by cthyb

**Comment by Wentzell** [comment]
Hey Leopo,

I agree. The full solution is to change the gf_struct_solver type (and potentially the
gf_struct_sumk type?) all throughout the application.

I have not started this changes that go quite deep into the application, as
discussed with @mzingl 

We should indeed keep this issue open until this is properly fixed.
