### ISSUE TITLE
User guide for calculations with SO

### ISSUE THREAD

**Issue by mzingl** [TRIQS/dft_tools#90]
This is a reminder for Gernot and me to work on the user guide with respect to calculations
with SO and off-diagonal hybridization (also in connection with PR #87).

**Comment by cmtcl18** [comment]
Dear Manuel and Gernot,
Can you tell what is the status of the documentation for Spin Orbit Coupling (SOC).

**Comment by cmtcl18** [comment]
Dear Markus, Manuel and Gernot,
Can you please supply a minimal python script for `spin polarized` calculations. When the system contains `more number of correlated atoms`, as a novice user it is getting difficult to analyze the errors. 

any suggestions would be appreciated. 

Best Regards
CMTCL

**Comment by mzingl** [comment]
This has been addressed in a recent pull request of the BSRotations branch.
