### ISSUE TITLE
find_package(TRIQS 1.5 EXACT REQUIRED) can't find TRIQS

### ISSUE THREAD

**Issue by yurivict** [TRIQS/dft_tools#96]
```
CMake Error at CMakeLists.txt:19 (find_package):
  Could not find a configuration file for package "TRIQS" that exactly
  matches requested version "1.5".

  The following configuration files were considered but not accepted:

    /usr/local/lib/cmake/triqs/TRIQSConfig.cmake, version: unknown
```

I had to remove ```EXACT``` from it to make it work.

**Comment by mzingl** [comment]
Hi,

as we have moved to version 2.0, I would advise you to install cpp2py, TRIQS, cthyb and DFTTools from scratch (always using the master branch). I just did this on my machine and it should work without cmake errors.

Best,
Manuel

**Comment by yurivict** [comment]
The last revision e187958 fails to find triqs:
```
CMake Error at CMakeLists.txt:15 (find_package):
  Could not find a configuration file for package "TRIQS" that is compatible
  with requested version "2.0".

  The following configuration files were considered but not accepted:

    /usr/local/lib/cmake/triqs/TRIQSConfig.cmake, version: unknown
```

**Comment by mzingl** [comment]
You also need to install the newest version of the TRIQS master branch. I would suggest to erase everything (build and install) and start from scratch. I did this just an hour ago with the master branch of TRIQS, cthyb and DFTTools and it works.

**Comment by mzingl** [comment]
Does it work now?

**Comment by mzingl** [comment]
There is some disconituity with the tags in the TRIQS projects (see issue TRIQS/triqs#603).
However, if you use the master of TRIQS, ctyhb and dfttools it should be working.
I'm closing this and #95 now, please reopen if this is still an issue.

**Comment by Wentzell** [comment]
> I think /usr/local/lib/cmake/triqs/TRIQSConfig.cmake is supposed to have a version 2.0 in it, and it doesn't contain any version.

There was in fact a bug in the versioning of the packages, that was resolved in https://github.com/TRIQS/triqs/commit/aa32b9372ec2e8a65d665a2b95b8d81c0668cf21

**Comment by mzingl** [comment]
Yes, but this issue is unrelated. It is newer than the mentioned commit.
