### ISSUE TITLE
dft_dmft_cthyb_slater.py does not exist

### ISSUE THREAD

**Issue by asubedi** [TRIQS/dft_tools#97]
I noticed that the file dft_dmft_cthyb_slater.py is linked in the documents, but it does not exist.

Best,
Alaska

**Comment by mzingl** [comment]
dft_dmft_cthyb.py was linked twice. Should be fixed now.

Best,
Manuel

**Comment by asubedi** [comment]
Great, the link works now.

Thanks,
Alaska
